### ISSUE TITLE
Nextcloud 14 Beta 2

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#10410]
### Stuff that didn't made it into beta 1 (#10370)

* [x] #10221 Prevent too long identifier names (PHP unit tests fail for Postgres)
* [ ] #10320 Cleanup of leftover-sorting-code from quickaccess-feature
* [ ] #10255 Add support for room shares (to be discussed)
* [ ] #10030 Do not allow RTLO char in filenames

### Added

* [x] #10421  Really cleanup the content-wrapper
* [x] #10444 small change and merged it already
* [x] #10474 Set emptyText depending on filepicker type
* [x]  #10481 Make the info available if the avatar was uploaded or generated

### Known bugs (and potential fixes)

* [x] #9242 Fix display name ignored when creating new user
* [ ] #10361 Public share note needs a better ui
* [ ] #10398 Opening details after coming from favorites view is broken
* [x] #10406 Not all sidebar entries have the "classes" attribute
* [ ] #10407 TypeError: this._reloadCall.abort
* [x] #10408 Set the favorites to the empty array on failure
* [x] #10409 Check if the favorite tag exists
* [x] #10415 Fix regex for icons
* [x] #10442 Contact list broken layout
* [x] #10416 Broken image preview without index.php rewrite
* [x]  #10417 Fix undefined constant error for STATUS_SERVICE_UNAVAILABLE
* [x] #9693 Logcondition broken
* [x] #10462 Fix duplicate inserts in the 2fa provider registry DAO
* [x]  #10443 NC14: core/img/places/contacts-dark.svg missing
* [x]  #10459 Fix caret icon on installation page
* [x] #10444 Allow to filter the unread count by verb
* [ ]  #10464 Password strength check loaded when user password cannot be changed.
* [ ] #8299 Decryption failed with s3
* [ ]  #10452 Header issues with small screens
* [x] #10420 Layout of admin tag management needs adjustments
* [x]  #10472 Add notification container to public layout template
* [x] #10471 Improve URL detection
* [x]  #10483 No margin left if the navigation is hidden
* [x] #10479  Use icon classes in personal settings
* [ ] #10476 Broken styles of results list in apps search
* [x] #10484 Append cache bump parameter to scss files URL
* [ ] #10477 App update indicator shows but there is no update 
* [x] #10486   Mobile fixes
* [ ]  #10485  Fix design of update error page
* [x]  #10465 Fix state propragation of the backup codes provider

### Apps

- [ ] https://github.com/nextcloud/files_texteditor/issues/105 Layout of the text editor if broken
- [ ] https://github.com/nextcloud/calendar/issues/876 Sidebar on adding a new event atop of calendar view
- [x] https://github.com/nextcloud/firstrunwizard/pull/73 Add image as first slide
- [ ] https://github.com/nextcloud/news/issues/311 News layout broken (and some security issues according to github, maybe we should try to update the dependencies)
- [ ] https://github.com/nextcloud/deck/issues/560 Deck layout broken
- [ ] https://github.com/nextcloud/contacts/issues/586 Contacts search error
- [x] https://github.com/nextcloud/richdocuments/issues/233 Collabora layout broken
- [x] https://github.com/nextcloud/notifications/pull/147 https://github.com/nextcloud/notifications/pull/147
- [x] https://github.com/nextcloud/notifications/pull/148 Commit the production js for the build maschine
- [ ] https://github.com/nextcloud/deck/issues/565 Can't set due date in the Deck app

### Design polishing

- [ ] #10094 Still things to polish
- [x]  #10467 Reword share comment feature
- [x] #10448 Only lower opacity of the avatar if the checkbox is checked on the content-list

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer

**Comment by MorrisJobke** [comment]
Planned release date: next week Thursday

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/10444 would be nice to have for the Talk app

**Comment by blizzz** [comment]
#10444 small change and merged it already

**Comment by MartB** [comment]
#10430 should be fixed as it is rendering nextcloud useless for people with activated encryption.
The fix itself is trivial but i will leave it up to the team to check if theres a bigger issue behind this.

**Comment by nickvergessen** [comment]
Must merge https://github.com/nextcloud/notifications/pull/147

**Comment by nickvergessen** [comment]
Also https://github.com/nextcloud/notifications/pull/148

**Comment by rullzer** [comment]
Beta2 is out. Closing
