### ISSUE TITLE
Nextcloud 14 Beta 3

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#10502]
### Stuff that didn't made it into beta 1 (#10370) and beta 2 (#10410)

* [ ] ~~#10030 Do not allow RTLO char in filenames~~ Moved to 15 for more in depth discussion
* [x] #10255 Add support for room shares (to be discussed)
* [x] #10320 Cleanup of leftover-sorting-code from quickaccess-feature

### Added

* [x] Only show checkbox on hover/focus + accessibility fixes #10482
* [x] enable pdf viewer by default https://github.com/nextcloud/files_pdfviewer/pull/90
* [x] #10569 get avatar custom status from user config
* [x] #8690 [Part2] Make thunderbird and outlook addons identifyable

### Known bugs (and potential fixes)

* [x] #8299 Decryption failed with s3
* [ ] #10361 Public share note needs a better ui
* [x] #10398 Opening details after coming from favorites view is broken
* [ ] #10407 TypeError: this._reloadCall.abort
* [x] #10430 Undefined isDirectoryHandle() method breaking encryption.
* [ ]  #10452 Header issues with small screens
* [x] #10455  File upload fails with encryption on s3 storage "ObjectUpload not found"
* [ ] #10457 issues with custom color and dark theme
* [ ] #10458 in gallery, fileslist-button is not entirely right 
* [x]  #10464 Password strength check loaded when user password cannot be changed.
* [x] #10476 Broken styles of results list in apps search
* [x] #10477 App update indicator shows but there is no update 
* [x]  #10485  Fix design of update error page
* [ ] #10489 Warnings and errors in Firefox console
* [ ] #10491 Restore button in "Deleted Files" tab doesn't work
* [ ] #10492 Incorrect behavior of "Disabled users" tab
* [ ]  #10500 2FA provider selection shown if only one provider active and backup codes generated -> https://github.com/nextcloud/server/pull/10588
* [ ] #10501 Problems with too long email in sharing dialogue
* [x] #10503 error messages in log files regarding favorites and tags
* [x] #10504 Undefined index error if I open the app store
* [x] #10508  Fix app management not providing updates for apps which got disabled
* [x] #10509 Always replace the app sidebar view when switching from a different file list
* [x] #10512 Date picker not accessible
* [ ] #10514 Remove "View in folder" action for deleted shares
* [x] #10515  Fixed design zindex
* [ ] #10516 strange behaviour of shares view details in sidebar
* [x] #10518 Long database names in apps break the update
* [x] #10519 Min height 100% on content-wrapper
* [x] #10523 Adding test for table schedulingobjects and fixing postgres LOB
* [x] #10525 Fixed notifications position
* [x] #10528 layout.public.php is broken
* [x] #10536 Combined download button not working in public share 14.0.0 Beta 2
* [x] #10541 icons-vars.css not found
* [ ] #10546 Popovermenu fix and token settings design fixes
* [x] #10550 Do not log to error loglevel when converting the error
* [x] #10556 App menu background to short 
* [x] #10558 A failing federation sync job is not an error 
* [ ] #10571 The userRow in User Management needs a way to register menu entries
* [x] #10578 Fix 2FA provider registry population on login
* [x] #10582 Fix `this` context for enter-key handler on app tokens
* [x]  #10583 Icon "confirm-white" is missing
* [x] #10586 Check if HTTP_USER_AGENT is set before using it

### Apps

- [x] https://github.com/nextcloud/files_texteditor/issues/105 Layout of the text editor if broken
- [ ] https://github.com/nextcloud/calendar/issues/876 Sidebar on adding a new event atop of calendar view
- [ ] https://github.com/nextcloud/news/issues/311 News layout broken (and some security issues according to github, maybe we should try to update the dependencies)
- [x] https://github.com/nextcloud/deck/issues/560 Deck layout broken
- [x] https://github.com/nextcloud/contacts/issues/586 Contacts search error
- [ ] https://github.com/nextcloud/deck/issues/565 Can't set due date in the Deck app
- [x] https://github.com/nextcloud/apps/pull/58 user_external
* [x] https://github.com/nextcloud/survey_client/pull/77 servery client is no longer enabled by default

### Design polishing

- [ ] #10094 Still things to polish

**Comment by rullzer** [comment]
Planned release date: next week Thursday

**Comment by tflidd** [comment]
Apps:
https://github.com/nextcloud/apps/pull/58

**Comment by AndrewErman** [comment]
Is there any estimate about the https://github.com/nextcloud/server/issues/8802 bug? It makes NextCloud nearly unusable in many cases...

**Comment by Sanookmakmak** [comment]
Is the Zero File Size Bug https://github.com/nextcloud/server/issues/3056 fixed in NC 14?

**Comment by rullzer** [comment]
Lets continue in https://github.com/nextcloud/server/issues/10605

**Comment by andyxh** [comment]
Hello Getting this error. Any help what i need to do? 
![image](https://user-images.githubusercontent.com/24574019/43905541-e5e6e980-9bb6-11e8-9856-f9d302dfada6.png)
