### ISSUE TITLE
Nextcloud 14 Beta 4

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#10605]
### Added

* [x] #10621 Add the ToS app to the enterprise bundle
* [x] #10659 Drop support for xcache
* [ ] https://github.com/nextcloud/changelog_server/pull/5 What's new info

### Known bugs (and potential fixes)

* [x] #5608 Deactivated Accounts still show up in Contacts for Chat and Videocalls
* [ ] #10361 Public share note needs a better ui
* [x] #10393 Unclear which item is currently "active"
* [x] #10407 TypeError: this._reloadCall.abort
* [x]  #10452 Header issues with small screens
* [x] #10457 issues with custom color and dark theme
* [x] #10458 in gallery, fileslist-button is not entirely right 
* [ ] #10489 Warnings and errors in Firefox console
* [x] #10491 Restore button in "Deleted Files" tab doesn't work
* [x] #10492 Incorrect behavior of "Disabled users" tab
* [x]  #10500 2FA provider selection shown if only one provider active and backup codes generated -> https://github.com/nextcloud/server/pull/10588
* [x] #10501 Problems with too long email in sharing dialogue
* [x] #10514 Remove "View in folder" action for deleted shares
* [ ] #10516 strange behaviour of shares view details in sidebar
* [x] #10543 Do not show deactivated users in sharees and contacts
* [x] #10546 Popovermenu fix and token settings design fixes
* [x] #10571 The userRow in User Management needs a way to register menu entries
* [x] #10592 Allow external actions to users list
* [x] #10598 Removed unused variable isFile
* [x] #10606 Remaining app updates seem to randomly reorder
* [x] #10607 Remove button in apps mangement sidebar broken
* [x] #10608 Fix header menu & contact popover
* [x] #10610 do not trigger counting on LDAP
* [x] #10611 Fix duplicate key violation in 2FA provider registry DAO
* [x] #10614 Do not use file as template parameter
* [x] #10615 Fix trashbin file actions
* [ ] #10616 Cannot enter Apps if manually installed apps are activated
* [x] #10618 use insertIfNotExists to store new mimetypes
* [x] #10619 Redirect to the same page after an update
* [x] #10622 Alignment issue and can no longer delete users in user management screen on 1280x720 
* [x] #10626 Fix quickaccess active indicator for folders with spaces
* [x] #10630 Error in Nextcloud 14 Beta 3 Missing "Enable recovery key" field in the admin settings
* [x] #10634 Two factor authetication is enforced even if no provider is active
* [x] #10641 White area at the bottom of public share pages without footer
* [x] #10644 Link sharing broken with enforced password protection
* [x] #10667 File picker layout is broken
* [ ] #10669 Class/service 'Tagger' not found.

### Apps

See https://github.com/orgs/nextcloud/projects/15 for to check apps still

- [ ] https://github.com/nextcloud/calendar/issues/876 Sidebar on adding a new event atop of calendar view
- [ ] https://github.com/nextcloud/news/issues/311 News layout broken (and some security issues according to github, maybe we should try to update the dependencies)
- [x] https://github.com/nextcloud/deck/issues/565 Can't set due date in the Deck app
- [x] https://github.com/nextcloud/impersonate/issues/53 Impersonate menu item not added to popovermenu

### Design polishing

- [x] #10094 Still things to polish

**Comment by rullzer** [comment]
Planned release date: next week Thursday

**Comment by andyxh** [comment]
Getting this error in NC 14 Beta 3
![image](https://user-images.githubusercontent.com/24574019/43908311-452add6a-9bbd-11e8-8292-7e826afef998.png)

**Comment by C439** [comment]
What about #10631?

**Comment by lefty78** [comment]
Waht about #10631 ?

**Comment by Claymore90** [comment]
Any news about #8802   ?

**Comment by rullzer** [comment]
Closed with #10703 

RC ticket will be opened shortly

**Comment by jospoortvliet** [comment]
ref https://github.com/nextcloud/server/issues/10713
