### ISSUE TITLE
Nextcloud 14 RC 1

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#10713]
Changes since 14.0.0 beta 4:

* #10334 Add options to create/remove groups via occ
* #10526 Support HEIC for previews
* #10539 Adds a setup and cli check for the recommended memory limit
* #10589 Retry smb stat on timeout
* #10628 Adds a permission check for app directories
* #10663 Update behat/behat requirement from ~3.3.0 to ~3.5.0 in /build/integration
* #10670 Fix max length requirements for the throttler metadata
* #10687 Don't blame randome people for background email updates
* #10697 Log entries that are hidden during file listing
* #10700 Fix share dialog sidebar in share views
* #10707 Fix public pages background
* #10710 Fix typo in IUserManager::createUser doc
* #10712 Check if a preview provider is available before using it
* #10715 Fix wrong return value of filtered whats new info
* #10718 Add occ command to recover encrypted files in case of password lost
* #10723 Fixes more apps menu and settings/user menu positions
* #10724 Improve performance when dealing with large numbers of shares
* #10731 Add deck and mail to the groupware bundle, remove talk
* #10734 Fixed a typo
* #10738 Only send an update sort order request if there is an user
* #10744 Update help.php
* #10747 Adds a vendor prefix for position sticky
* #10755 Fix comment style in config sample
* #10771 Fix backup codes column length for Argon2 values
* #10772 Fix generated migration class code
* #10773 Accessibility theme fixes
* #10775 Resolve all group memberships properly
* #10780 [3rdparty] Apply upstream patch #1025 for sabre-dav
* #10787 Fixes the app menu
* #10789 Fix loading providers of 2FA app with more than one provider
* #10801 Add sample config for HEIC image previews
* #10803 Prefer using dir instead of allinfo for getting smb file info
* #10815 Returning of $tr is expected, otherwise ending up in a JS error
* #10820 [LDAP] The WebUI Wizard also should not assign empty config IDs
* #10822 Show link to simple sign up page
* #10827 HEIC previews as JPG rather than PNGs to save space.
* #10828 Fix mimetype detection for junked uploads
* #10834 Add support for room shares
* #10835 Disallow negative mtime in dav search
* #10841 Also catch exceptions when loading apps
* [3rdparty#138](https://github.com/nextcloud/3rdparty/pull/138) Add patch #1025 for sabre-dav
* [serverinfo#123](https://github.com/nextcloud/serverinfo/pull/123) Keep the server setting at the top, right after "overview" and "basic settings"
* [serverinfo#124](https://github.com/nextcloud/serverinfo/pull/124) Fixed encoding of mac char
* [serverinfo#98](https://github.com/nextcloud/serverinfo/pull/98) Using input field for monitoring endpoint url
* [survey_client#79](https://github.com/nextcloud/survey_client/pull/79) Change description into a sentence

Pending PRs:

* [x] #10838 Public share note needs a better ui 

### Apps

See https://github.com/orgs/nextcloud/projects/15 for to check apps still

- [x] https://github.com/nextcloud/news/issues/311 News layout broken (and some security issues according to github, maybe we should try to update the dependencies)
- [ ] https://github.com/nextcloud/calendar/issues/876 Sidebar on adding a new event atop of calendar view
