### ISSUE TITLE
App support for Nextcloud 15

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#12480]
We should check out following apps for their Nextcloud 15 support and try to get new versions of them into the appstore:

* [x] announcement center @nickvergessen nextcloud/announcementcenter#120
* [x] calendar @georgehrke https://github.com/nextcloud/calendar/pull/951
* [x] contacts @skjnldsv
* [x] data_request @blizzz
* [x] external @nickvergessen nextcloud/external#123
* [x] keep or sweep @jancborchardt keeporsweep/keeporsweep#20
* [x] impersonate @blizzz
* [x] polls @dartcafe nextcloud/polls#421
* [x] Unsplash @jancborchardt @newhinton @marius-wieschollek https://github.com/jancborchardt/unsplash/pull/26
* [ ] bookmarks_fulltextsearch @daita
* [ ] cms_pico @daita
* [x] dashboard @daita
* [x] files_frommail @daita
* [x] files_fulltextsearch_tesseract @daita
* [ ] group_everyone @icewind1991
* [x] groupfolders @icewind1991
* [x] jsloader @morrisjobke
* [ ] limit_login_to_ip @rullzer
* [x] mood @daita
* [ ] orcid @daita
* [ ] privatedata @rullzer
* [x] sharepoint @blizzz
* [x] socialsharing_diaspora @schiessle
* [x] socialsharing_email @schiessle
* [x] socialsharing_facebook @schiessle
* [x] socialsharing_googleplus @schiessle
* [x] socialsharing_twitter @schiessle
* [ ] zenodo @daita

<details>
<summary>SQL query for the app store</summary>

```sql
SELECT id
FROM core_app
WHERE id NOT IN (
	SELECT DISTINCT app_id
	FROM core_apprelease
	WHERE platform_version_spec <> '>=9.0.0'
	AND platform_version_spec NOT ILIKE '%<9.%'
	AND platform_version_spec NOT ILIKE '%<10.%'
	AND platform_version_spec NOT ILIKE '%<11.%'
	AND platform_version_spec NOT ILIKE '%<12.%'
	AND platform_version_spec NOT ILIKE '%<13.%'
	AND platform_version_spec NOT ILIKE '%<14.%'
	AND platform_version_spec NOT ILIKE '%<15.0.0'
	AND is_nightly IS FALSE
)
ORDER BY id ASC;
```
</details>

<details>
<summary>Full list of apps without a non-nightly release</summary>

 * activitylog
 * admin_notifications
 * appvncsafe
 * beame_insta_ssl
 * blockscores
 * bookmarks_fulltextsearch
 * caniupdate
 * cms_pico
 * defaultgroup
 * diffuse
 * documents
 * fbsync
 * files_3d
 * files_clipboard
 * files_external_sia
 * files_frommail
 * files_fulltextsearch_mail
 * files_opds
 * files_pdfviewer
 * files_reader
 * files_rightclick
 * files_snapshots
 * folderplayer
 * githubmergetracker
 * gluusso
 * group_everyone
 * initialcheck
 * issuetemplate
 * keeweb
 * ldapcontacts
 * ldaporg
 * limit_login_to_ip
 * linkshareex
 * logreader
 * mindmaps
 * money
 * mood
 * myscan
 * nextant
 * nextnotes
 * ocdownloader
 * ocr
 * orcid
 * privatedata
 * quicknotes
 * spgverein
 * spreedme
 * theming
 * twofactor_email
 * user_cas
 * user_ispconfig
 * user_pwauth
 * workin2gether
 * zenodo
 * zimbradrive

</details>

**Comment by rullzer** [comment]
> You mean, non-nightly releases?

if possible

**Comment by xf-** [comment]
Please also add/check PHP 7.3 support, since Nextcloud 15 supports PHP 7.3 officially. Had no problems after changing the XML maxVersion setting.

Maybe helpful
- Travis already added PHP 7.3 (maybe some plugins are currently missing like xdebug).
- The official Debian PHP maintainer has a repo with  all not-EOL versions including latest PHP 7.3 RC5. https://deb.sury.org/ (Debian repo & *buntu ppa).

**Comment by xf-** [comment]
@MorrisJobke 1..2 is released with v15 support
https://github.com/nextcloud/impersonate/releases

**Comment by jancborchardt** [comment]
Both Keep or Sweep and Unsplash are ready for 15 (and 16 dev version :)

- Keep or Sweep keeporsweep/keeporsweep#20
- Unsplash jancborchardt/unsplash#26

1️⃣5️⃣

**Comment by j-ed** [comment]
Most important, the News app already supports 15 (and 16 dev version) 😄 
* News https://github.com/nextcloud/news/commit/4b1597450ad84b51eae8ebdda5dd07b3fcf1c99f

**Comment by violoncelloch** [comment]
Is user_external missing in this list? It is still shipped with 15 but not compatible and leads to errors on upgrade if enabled. See #12506

**Comment by jancborchardt** [comment]
@violoncelloch yup! Pull request about that at https://github.com/nextcloud/apps/pull/69

And discussion on moving that out of the "apps" repo as it's the only maintained one of that bunch: https://github.com/nextcloud/apps/pull/59#issuecomment-443717173

Would you also be interested to be co-maintainer of the app? :)

**Comment by Spartachetto** [comment]
@MorrisJobke the various socialsharing apps were updated

**Comment by jancborchardt** [comment]
@daita it seems all those fulltextsearch apps should be just one? It’s a lot of complicated overhead if you just want full text search to work, or contribute.

**Comment by daita** [comment]
@jancborchardt The complicated stuff is not to install multiple apps but to install and setup the elasticsearch. And it's easier to contribute this way as you just need to create a php class in your own app to index its content

**Comment by JochenHWezel** [comment]
I see that @icewind1991 already updated his sources for group_everyone for being compatible with nextcloud 15: https://github.com/icewind1991/group_everyone/blob/master/appinfo/info.xml

@MorrisJobke Do you just need to refresh some sources at your side for app group_everyone?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Do you just need to refresh some sources at your side for app group_everyone?

I simply didn't updated the list yet 😉

**Comment by MorrisJobke** [comment]
Updated the list now.

**Comment by rullzer** [comment]
That app is not officially supported. The updater is just warning you that if you update that app will not continue to work.

**Comment by MorrisJobke** [comment]
> Maybe expected by you when update is available with 15.0.3, maybe not expected behaviour when you wanted to solve it for 15.0.2 ?

This is a known issue: #12475
