### ISSUE TITLE
Nextcloud 15 RC1 polishing review (overview issue)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#12694]
@MorrisJobke and I just did a walkthrough of the current RC1 zipfile. Here’s some papercuts we found and we should fix for polishing:

## Installation

- [ ] Round off database switcher, and check if we want to update style.
- [ ] Better feedback on submit. Spinner is missing? And all elements still there.

## Log in

- [x] Not enough highlight on tab-focusing of log in button. **Pull request** #12709
- [x] Spinner on log in button is a bit too far to the right. **Pull request** #12709

## First run wizard / About @juliushaertl

- [x] Fix button position movement: possibly put buttons to sides? Issue https://github.com/nextcloud/firstrunwizard/issues/76

## Files

- [ ] Action menu popover should be centered below 3-dot-icon on desktop
- [ ] Opening "Move or copy" dialog switches everything to grid view (only on very first run)
- [ ] Move or copy dialog has broken grid view
- [ ] Grid view: File previews in other views still low-res (Recent, Favorites, Shared) #12057
- [x] Polishing of various modal dialogs. **Pull request** #12762
- [x] Arrow animation for Favorites and Shares looks out of place
- [ ] Floating blue bar for subentries looks strange → Let’s not indent the subentries here. Issue https://github.com/nextcloud/server/issues/10261
- [ ] Upload progress bar
    - [ ] No proper feedback: "13 minutes" what? Rather: "Uploading (2 min left) …"
    - [ ] Add spinner additionally
    - [ ] Make bar smaller like quota bar
    - [ ] Fix style of x button next to it (remove background and border)
- [ ] Sidebar: Tooltip of folder/file title shows even if the text is short.

## Activity @nickvergessen

- [ ] Emptycontent view should show the proper icon (for Tasks or Calendar or Comments for example) instead of the generic Activity icon. Issue https://github.com/nextcloud/activity/issues/322

## Notifications @nickvergessen

- [x] "No notifications" could use an icon, like the empty Contacts dropdown. https://github.com/nextcloud/notifications/issues/208

## Personal settings

- [ ] Personal: White border on permissions popup (left of blue bar) → should be `border: none;` for light theme instead of `border: 1px solid transparent;`
- [ ] Personal: Locale setting showed "English (United States)" by default, but week starts on Monday? Should be based on browser, and probably just the display in the select is wrong.
- [ ] Personal: Privacy settings of personal details not tab-focusable! And missing feedback for "Help translation"
- [x] Personal: Remove Google+ button at some point? ;) Shuts down August 2019
- [ ] Personal: Social icons need highlight (border, like avatar in top right)
- [ ] Security: Default logo for Session created through app password
- [ ] Activity: "Your settings were updated" too verbose, just "Settings updated"
- [x] Mobile & desktop: Icons of Calendar, Contacts & Files buttons too big
- [ ] Accessibility: Focus highlighting could be better
- [x] Accessibility: Border line at the top of the first section should not be there (highly visible in contrast theme)
- [ ] Sharing: Icons are too big

## Admin settings

- [ ] Overview: Links have no tab-focus feedback → underline by default, change background on hover/focus
- [ ] Overview: Translate update channels?
- [x] Overview: make a button out of "What's new?" so it's more obvious it can be clicked on. **Pull request** #12757 https://github.com/nextcloud/server/pull/12687#issuecomment-442762747
- [ ] Basic settings: Status indicator text of background jobs is not aligned with header
- [ ] Basic settings: Background jobs radio buttons explanatory text should be shifted to right to be flush with radio button text.
- [ ] Basic settings: Remove data handling? Cause we now use chunking
- [x] Support: Github header linked, not necessary cause button is linked
- [ ] Support: Link needs to be highlighted hover/focus
- [ ] Support: Social icons need highlight (border, like avatar in top right)
- [x] Sharing: Information "i" icons are a bit too far down, especially for Federated Cloud Sharing → h2 needs to be inline-block

## Apps management @juliushaertl @skjnldsv?

- [x] Workflow apps don’t have logo: Automated PDF conversion & Workflow external scripts → just use default app icon (the gear icon)
- [ ] "No reviews" does not translate to 2.5 stars → do not show stars when there are no ratings

## User management @juliushaertl @skjnldsv?

- [ ] German "Standard Speicherkontingent" wraps in select box → ellipsize to one line
- [ ] "Add group" control needs to move further down, into the "Groups" section
- [ ] "Add group" has a strange button combination of checkmark and cancel "x"

## Help

- [ ] Could use icons in the navigation bar

cc @nextcloud/designers @nextcloud/javascript I’ll also create issues in the relevant repositories if it relates to other apps. If you are working on an issue, please add your name to the point. :) Also link existing issues or pull requests if I forgot any.

**Comment by blizzz** [comment]
> Workflow apps don’t have logo: Automated PDF conversion & Workflow external scripts → just use default app icon (the gear icon)

Um, actually, they have and ship icons and screenshots. Indeed it looks like there are some issues with displaying the screenshots on the apps page.

**Comment by MorrisJobke** [comment]
> * 
> * [ ]  Opening "Move or copy" and change the view from list to grid also changes the main view, but not the main view toggle.

I added this. cc @skjnldsv

**Comment by blizzz** [comment]
> EDIT: Issue seems to be with the app store. The images for the apps page are hosted there, but the files for both apps just return "File Not Found", opposite to the other apps. Perhaps a re-publishing helps…

Rereleasing did not help. Perhaps the additional attribute in the screenshots entry in the info.xml is causing the app store to misbehave. That's what looks different to other apps, despite still validating.

**Comment by juliushaertl** [comment]
> Rereleasing did not help. Perhaps the additional attribute in the screenshots entry in the info.xml is causing the app store to misbehave. That's what looks different to other apps, despite still validating.

Seems to be an issue with the usercontent proxy https://github.com/nextcloud/usercontent.apps.nextcloud.com/issues/4

**Comment by MorrisJobke** [comment]
> Seems to be an issue with the usercontent proxy [nextcloud/usercontent.apps.nextcloud.com#4](https://github.com/nextcloud/usercontent.apps.nextcloud.com/issues/4)

Fixed.

**Comment by MorrisJobke** [comment]
> Fixed.

Also added to to-do-for-release list: https://github.com/nextcloud/server/wiki/Todos-before-a-release

**Comment by MorrisJobke** [comment]
Let's move this to 15.0.1

**Comment by nickvergessen** [comment]
I moved 
>  Emptycontent view should show the proper icon (for Tasks or Calendar or Comments for example) instead of the generic Activity icon. Issue nextcloud/activity#322

to 16 in the activity app. it's already working in my vue-js branch, I will not implement this twice or backport the vue change :see_no_evil:

**Comment by MorrisJobke** [comment]
@nextcloud/designers What to do with this list.

**Comment by jancborchardt** [comment]
A bunch of the issues were already fixed (checked them off) and more have work in progress or already separate open issues. I would just close this as we do these reviews regularly and it’s fine if some parts don’t get fixed → they will come up next time again, or during regular fixing. :)
