### ISSUE TITLE
Keyboard shortcut support

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#1444]
A few apps have awesome keyboard shortcuts, which makes it super easy and fast to use nextcloud. I think we should define standards for nextcloud, so the shortcuts are consistent.

*Additionally It would be nice to have a current shortcut overview help like github does it.
(Try it by pushing the `?` key)
Could this work as an app?*

---
### Advised general shortcuts
| Shortcut | Action |
| --- | --- |
| <kbd>r</kbd> | Reload messages / feed |
| <kbd>▶︎</kbd> / <kbd>j</kbd> /  <kbd>n</kbd> | Next item / file |
| <kbd>◀︎</kbd> / <kbd>k</kbd> /  <kbd>p</kbd> | Previous message / item / file |
| <kbd>del</kbd> | Delete message |
| <kbd>o</kbd> / <kbd>enter</kbd> | open Item |
| <kbd>q</kbd> | Focus internal search |
| <kbd>u</kbd> | Toggle read/unread |
| <kbd>s</kbd> | Toggle Star (flag) message |
| <kbd>c</kbd> | create item |
| <kbd>esc</kbd> | close menu |

**Items** can be mails, files, folders, etc., if not stated otherwise

### Shortcuts/combinations that should be avoided
- Combinations with <kbd>ctrl</kbd> and <kbd>cmd</kbd> in general
- <kbd>▼</kbd> and <kbd>▲</kbd>, because of interference with scrolling

### Undecided shortcuts from News App
Maybe to special to generalize them

Shortcut | Action
--- | ---
<kbd>e</kbd> | expandItem
<kbd>i</kbd> /  <kbd>l</kbd> | toggleStar
<kbd>h</kbd> | toggleStar && scrollToNextItem
<kbd>f</kbd> | nextFeed
<kbd>d</kbd> | previousFeed
<kbd>c</kbd> | previousFolder
<kbd>a</kbd> | scrollToActiveNavigationEntry
<kbd>v</kbd> | nextFolder
<kbd>shift</kbd> + <kbd>a</kbd> | markAllRead

### Files App

| Shortcut | Action |
| --- | --- |
| <kbd>ctrl</kbd>/<kbd>cmd</kbd> + <kbd>n</kbd> | new folder |
| <kbd>ctrl</kbd>/<kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>n</kbd> | new file |
| <kbd>esc</kbd> | close menu (while new file context menu is open) |
| <kbd>up</kbd>/<kbd>down</kbd> | select file/folder |
| <kbd>enter</kbd> | open file/folder |
| <kbd>delete</kbd>/<kbd>backspace</kbd> | delete file/folder |
| <kbd>ctrl</kbd>/<kbd>cmd</kbd> + <kbd>f</kbd> | focus search field |
| <kbd>esc</kbd> | close menu |

### Mail App

| Shortcut | Action |
| --- | --- |
| <kbd>r</kbd> | Reload messages |
| <kbd>◀︎</kbd> | Previous message |
| <kbd>▶︎</kbd> | Next message |
| <kbd>s</kbd> | Star (flag) message |
| <kbd>u</kbd> | Toggle read/unread |
| <kbd>del</kbd> | Delete message |

### News App

Shortcut | Action
---|---
<kbd>j</kbd> /  <kbd>n</kbd> /  <kbd>▶︎</kbd> | scrollToNextItem
<kbd>k</kbd> /  <kbd>p</kbd> /  <kbd>◀︎</kbd> | scrollToPreviousItem
<kbd>u</kbd> | toggleUnread
<kbd>e</kbd> | expandItem
<kbd>s</kbd> /  <kbd>i</kbd> /  <kbd>l</kbd> | toggleStar
<kbd>h</kbd> | toggleStar && scrollToNextItem
<kbd>o</kbd> | openLink
<kbd>r</kbd> | reloadFeed
<kbd>f</kbd> | nextFeed
<kbd>d</kbd> | previousFeed
<kbd>c</kbd> | previousFolder
<kbd>a</kbd> | scrollToActiveNavigationEntry
<kbd>v</kbd> | nextFolder
<kbd>q</kbd> | Focus search
<kbd>shift</kbd> + <kbd>a</kbd> | markAllRead

## Todo:
- [x] collect the shortcuts that are already available
- [ ] general: improve tabindex
- [ ] general: shortcuts for navigation / menu 
  - [ ]  jump to apps menu
  - [ ]  jump to sidebar
  - [ ]  jump to settings menu
  - [ ]  select menu point (sidebar/apps/settings) with arrow keys
- [ ] add a dedicated page in the documentation
- [ ] files app: add file option (maybe distinct issue)
  - [ ]  rename
  - [ ]  open and focus details
  - [ ]  share (is an essential feature and should be able to be  directly executed on a selected file)
  - [ ] descend into newly created folder by clicking enter again [#1905]
- [ ] contacts app
- [ ] calendar app [nextcloud/calendar#157]
- [ ] gallery app
- [ ] ?app for a helper listing shortcuts in the current view

**Comment by MariusBluem** [comment]
...to **make something great again** also reminds me on this nice guy with the fancy haircut 😜

**Comment by eppfel** [comment]
@ChristophWurst Could you post/link the mail shortcuts?

**Comment by ChristophWurst** [comment]
Shortcut | Action
---|---
<kbd>r</kbd> | Reload messages
<kbd><</kbd> | Previous message
<kbd>></kbd> | Next message
<kbd>s</kbd> | Star (flag) message
<kbd>u</kbd> | Toggle read/unread
<kbd>del</kbd> | Delete message

**Comment by eppfel** [comment]
So, I just started implementing a proof-of-concept app for this "keyboard shortcut helper". Github uses [facebox](https://github.com/defunkt/facebox), which was not maintained for years. Are there modals in nextcloud? The only one I can think of, is in the first run wizard.

And what other apps besides mail use shortcuts, yet? I am not aware of any other. Maybe we postpone this, until our Design Guide is ready.

**Comment by MorrisJobke** [comment]
> Are there modals in nextcloud? The only one I can think of, is in the first run wizard.

There are, but they build on an old version of jQuery UI and we try to get rid of this. Beside that these are dialog based modals (with buttons to accept or decline the stuff).

**Comment by eppfel** [comment]
I found the shortcuts of the files app, but not any other ones. ⏫ 
I'll open respective issues in the contacts/calendar/gallery apps. Any other apps that are essential?

Before we jump into action (see todos ⏫ ), we should develop an ideal/desired state, so shortcuts are consistent over apps and we don't have conflicts/collisions between apps and general shortcuts (navigation/search).
I'd like @nextcloud/accessibility opinion on this, too.

**Comment by phsc** [comment]
In IE11 none of the above listed "Keyboard shortcuts: actual state" worked in the Files app on Nextcloud 10.0.1. Is this an IE11 problem or do I something wrong?

Nevertheless, I'm not sure, if ``backspace`` should trigger the "delete file/folder" action. This could lead to unintentionally deleted files (ok, we have a trashbin, but it still can be annoying).

**Comment by eppfel** [comment]
@phsc: mh, movin in the list and open works on my side, but not the rest. Maybe this is something for a dedicated issue.

**Comment by jancborchardt** [comment]
Also cc @BernhardPosselt as the News app was the first app with shortcuts like this. @BernhardPosselt can you post the list of the News app shortcuts?

Where do we have further shortcuts? cc @georgehrke @raghunayyar @tcitworld for Calendar, @Henni @irgendwie for Contacts & Notes, @oparoz for Gallery.

**Comment by skjnldsv** [comment]
@jancborchardt don't think we have shortcuts on contacts.

**Comment by ccoenen** [comment]
Regarding the suggestions in the original post: I'd not overwrite <kbd>Ctrl+N</kbd> it's a browser default for new window in all browsers I know. <kbd>Ctrl+Shift+N</kbd> is "get back the most recently closed window" at least in firefox. Some browsers also prevent you from overriding their shortcuts. This is the Case for <kbd>Ctrl+R</kbd> in either chrome or firefox, it could also apply to <kbd>Ctrl+N</kbd>

<kbd>up/down</kbd> keys should only be touched if we're 100% positive that we do not break scrolling along the way. I guess this is why most apps default to vi-style move keys.

I am also against overriding <kbd>Ctrl+F</kbd> - personally I use in browser text search _all the time_ also in Nextcloud. Wouldn't want to lose that.

**Comment by ccoenen** [comment]
<kbd>Backspace</kbd> is also a bad choice for shortcuts. It is "back" in all the browsers I know. At least on windows.

**Comment by eppfel** [comment]
@ccoenen  So far, we just collected the current state. I can only agree with your points (although Chrome has dropped <kbd>backspace</kbd> for <kbd>cmd</kbd>+<kbd>◀︎</kbd>, but <kbd>del</kbd> is sufficient for us)

I suggest working on the basis of the News/Mail App: Check if the user is not in an input/textarea/... and only then perform actions on key inputs (mainly) without modifier keys.
- News App: [news/js/gui/KeyboardShortcuts.js](https://github.com/nextcloud/news/blob/master/js/gui/KeyboardShortcuts.js) Awesome work by @BernhardPosselt 
- Mail App: @ChristophWurst Can you point us to the source code? 

I made a proposal in the OP, please review: @nextcloud/accessibility @nextcloud/designers

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/blob/52810c7b799304a7cf116abc8b13d0a4973110c0/js/views/foldercontent.js#L155-L199 is where we handle our keyboard shortcuts.

**Comment by eppfel** [comment]
@nextcloud/designers I know everyone is down, because of the guy with crazy hair being president and all, but I need some feedback on my proposal, so we can make dedicated PRs:
So, What do you think?
### Advised general shortcuts
| Shortcut | Action |
| --- | --- |
| <kbd>r</kbd> | Reload messages / feed |
| <kbd>▶︎</kbd> / <kbd>j</kbd> /  <kbd>n</kbd> | Next item / file |
| <kbd>◀︎</kbd> / <kbd>k</kbd> /  <kbd>p</kbd> | Previous message / item / file |
| <kbd>del</kbd> | Delete message |
| <kbd>o</kbd> / <kbd>enter</kbd> | open Item |
| <kbd>q</kbd> | Focus internal search |
| <kbd>u</kbd> | Toggle read/unread |
| <kbd>s</kbd> | Toggle Star (flag) message |
| <kbd>esc</kbd> | close menu |

**Items** can be mails, files, folders, etc., if not stated otherwise

### Shortcuts/combinations that should be avoided
- Combinations with <kbd>ctrl</kbd> and <kbd>cmd</kbd> in general
- <kbd>▼</kbd> and <kbd>▲</kbd>, because of interference with scrolling

I'm not 100% on <kbd>q</kbd> and <kbd>s</kbd> though. <kbd>s</kbd> could be `search`, too.

What do you think about shortcuts for jumping between navigation (sidebar/apps/...)?

Any use-cases we need to add?

**Comment by ccoenen** [comment]
<kbd>f</kbd> could be "find", as in Ctrl+f in most software.

**Comment by tyrylu** [comment]
I am only a little bit worried about interactions between del and focused edit controls. It will probably be okay, but do not forget to test this.

**Comment by eppfel** [comment]
> f could be "find" -> focus search

Another contender. 😄 The News app uses <kbd>f</kbd> for next Feed already, but makes sense, because <kbd>ctrl + f</kbd> is well known.

> I am only a little bit worried about interactions between del and focused edit controls. It will probably be okay, but do not forget to test this.

If you refer to text modifications: These commands should not work, if the user is inside an input field. I guess we could even introduce <kbd>esc</kbd> to exit a field.

**Comment by BernhardPosselt** [comment]
BTW, lets not override ctrl + f, discourse does it and I hate it with a burning passion

**Comment by eppfel** [comment]
@BernhardPosselt, I cite my proposal 😁 
> ### Shortcuts/combinations that should be avoided
> - Combinations with ctrl and cmd in general

**Comment by MorrisJobke** [comment]
> BTW, lets not override ctrl + f, discourse does it and I hate it with a burning passion

Press ctrl + f a second time and you get the one of the browser :wink

**Comment by ccoenen** [comment]
Actually, since we're already off topic, I can't get the discourse search to pop up via <kbd>Ctrl</kbd>+<kbd>f</kbd> at all. Neither in Firefox nor in Chrome. It's also not documented in the <kbd>?</kbd> help screen. Anyway this suggestion here does not seek to override <kbd>Ctrl</kbd>+<kbd>f</kbd>, so we're all in agreement so far.

**Comment by mammuth** [comment]
The "Advised general shortcuts" might also state a common combination for **creating items**. 

I would like to suggest `C (create/compose)`  (_create_ event, _compose_ mail, _create_ file/folder). 

This is also the shortcut which is used at eg. mail.google.com, inbox.google.com and calendar.google.com

**Comment by jancborchardt** [comment]
cc @ChristophWurst @georgehrke for that »Create/Compose« shortcut. We should add that to Mail and Calendar. :)

**Comment by BennyLi** [comment]
Just to mention it: I'm very familiar with Vim keybindings. Google uses these in there web apps too. I would prefer these type of keybindings.

In example for searching just press <kbd>/</kbd> and start typing. You already use the movement keys from Vim like keybindings.

**Comment by ccoenen** [comment]
<kbd>/</kbd> for search is very limited to the nerd demographic. I believe we're better off with <kbd>Ctrl</kbd>+<kbd>F</kbd>. On many (most?) keyboards <kbd>/</kbd> is not even preferable to <kbd>Ctrl</kbd>+<kbd>F</kbd>, as you have to press the same amount of keys.

**Comment by jancborchardt** [comment]
Yup, what @ccoenen said. Additionally we use a lot of "Vim" style shortcuts already, like j/k in the News app and others.

**Comment by eppfel** [comment]
Thinking about this again, we should really look for other web applications and find the most used versions...
Our chances of users adapting keyboard interaction, will increase if they can use the ones they already know.

**Comment by jsalatiel** [comment]
I dont know if this is the right place to ask, but why page up and page down does not scroll the files ?

**Comment by ccoenen** [comment]
one more suggestion: <kbd>Alt</kbd>+<kbd>Up</kbd> is used in Windows explorer and Gnome's nautilus to bring you up one level in your directory hierarchy (which is not always the same as browser back, so it proves very useful sometimes).

**Comment by ccoenen** [comment]
@jsalatiel This should work (For me, it does on Nextcloud 12, Firefox, Windows, German keyboard).

So this sounds more like a bug than missing support. I'd open this as a new ticket, this will be easier to debug and receive attention. In here nobody will ever find it.

**Comment by jsalatiel** [comment]
@ccoenen , thanks! i did that https://github.com/nextcloud/server/issues/6863
Well, i tested both firefox 56 and chrome 60 on linux, and neither can scroll using keyboard. (It only works with the mouse)
I don't have windows to test it.

**Comment by siccovansas** [comment]
@skjnldsv just merged the very useful functionality to tag multiple files at once in #28133 🎉🎉!

A great addition to this would be to have keyboard shortcuts so you can quickly navigate files using up and down arrows to (de)select files. I must say that Gmail's keyboard shortcuts work really well. On a daily basis I use the up and down arrows to quickly (de)select emails and use 'l' to add a label(/tag) or '#' to delete the selected emails. Such keyboard shortcuts would make Nextcloud Files much more powerful as you can quickly organize your files using only your keyboard.

**Comment by skjnldsv** [comment]
I think having this would be nice, but would require a proper API for every app to register a list of said shortcuts. So they are consistent across Nextcloud

If anyone wants to draft an RFC with a proposal, it would be cool :)

**Comment by Tanman897** [comment]
Hey, I am not of much help here to contribute anything useful but want to say That  useful progress but I do find it very frustrating that shift + click to select a batch of files on the server is not a functionality in the year 2021. It makes moving batches of files around in folders a task that would take seconds in literally any other application into hours (no exaggeration) when I am dealing with thousands of files.
