### ISSUE TITLE
Rework of collaborative tags 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1465]
- [x] Give them a UI that makes clear that it's about tags, not a normal input box
  - [x] "🔖 Tags" next to file size in the details, on click expand and focus input field (#1469)
  - [x] Fix font and input field size
- [x] By default show the last tags a user applied (#1934)
- [ ] ~~Search/type-ahead should only bring up tags the user applied already (or has access to)~~ moved to 13: #4699
- [ ] ~~Tags that are not assigned should not be visible (implied by pervious task) (#586)~~ moved to 13: #4699
- [x] Users (non-admins) should not be able to delete tags (#2512)
- [ ] ~~Some information on the filter search page (#2143)~~ moved to 13: #4699
- [ ] ~~More prominent displaying of tags when used (#2838)~~ moved to 13: #4699
  cc @jancborchardt as discussed?

**Comment by raimund-schluessler** [comment]
I would like to be able to give tags a custom color so it is easier to distinguish between different tags.
@jancborchardt Might this be useful?

**Comment by MorrisJobke** [comment]
@nickvergessen Could I ask you to split out the stuff that doesn't make it into 11 to a separate ticket for 12? Thanks ;)

**Comment by disaster123** [comment]
@raimund-schluesser great! Need that too. Any chance to implement it?

**Comment by WowMuchName** [comment]
Isn't #2512 very limited and only scratching the surface of a deeper problem?

For instance we have a group User and a group Manager. When Users upload stuff the workflow module assigns a "to be checked" tag. After the Managers check the files the tag is removed. With things as they are Managers either need to be Admins or the tag needs to be public. Both options aren't very good. Currently we rely on the fact that tag-removal is logged and just have the tag public.

Couldn't each collaborative Tag be treated with the same access mechanism used for files? Where users can give "see Tag" (read), "set Tag" (write), "remove Tag" (delete), "Can reshare" privileges to other users and groups as they do with files? Inheriting all the "reshare only in the same group" etc. settings that are used for files?

I would assume a lot of the logic and ui components already used for files could be reused here. Having one concept of a "secureable object" and Files, Tags, Adressbooks, Calendars etc. just extending upon that concept seems a good idea for both usability and maintainability. It is also how most operating systems and security frameworks organize things.

At any rate giving tags some-sort-of-access-rights-but-not-really seems like re-inventing an inferior wheel when a battle proven one is already used elsewhere in the code.

**Comment by Spartachetto** [comment]
@WowMuchName I have the impression that there is some misunderstanding...

If I am not wrong #2512  is about another aspect of tag management: you are talking about assigning and removing (i.e.: "un-assigning") tags to files; #2512 is about deleting tags from the list of tags, i.e.: removing tags from the system.
To say it with other words, if someone deletes the "to be checked" tag then the only way to assign it to a file is to recreate another tag with the same label.

**Comment by WowMuchName** [comment]
@Spartachetto You are correct, I jumped to conclusions there and should have actually read the issue before linking it. I was referring to the hidden-public-restricted access-types you can set for tags which I find to be very limited.

**Comment by MorrisJobke** [comment]
@nickvergessen I think the remaining items needs to be pushed to 13, right? Could you create a ticket for them? To know what was implemented in which version.

**Comment by MorrisJobke** [comment]
I moved the pending items to a dedicated 13 issue: #4699
