### ISSUE TITLE
✨ Nextcloud 17 polishing list!

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#16076]
As usual, we test the daily zip file to find details for polishing. 🎉

Everyone should go over the issues and see where they can help out! 😊 Add your handle if you work on it, or relevant issues or pull requests.

**Bold issues are especially important and should be fixed for the release!**

## 🏗 Pre-installation
* [x] Zip file is huge!
  * [x] ~Because of .map files?~ – they are not that big
  * [x] viewer ships cypress (36.4MB): Should be removed in tomorrows daily
  * [x] ~~3rdparty/aws/aws-sdk-php/src/data possibly not necessary (12.2MB)~~ too risky, might be in use
* [x] Change name of "Nextcloud.mp4" to "Nextcloud intro.mp4" to fix the strange Viewer issue which accomodates for iOS live images → pull request at https://github.com/nextcloud/example-files/pull/5

## 👩‍🏭 Installation
* [ ] Finish button not visible on some screens – possibly sticky, or make warning wider
* [x] ~**Missing loading feedback on installation, should have a spinner**~ – it’s there, Safari just stops rendering
* [ ] Security warning is not greyed out
* [x] ~~Whitescreen on installation, no feedback~~ was caused by fatal PHP error caused by the support app interface, fixed by @juliushaertl 

## 🧙 First run wizard
* [x] First run wizard should have different viewer background opacity (less dark) @juliushaertl 
* [x] Scrollbar shows @juliushaertl 
* [x] Content should fit into box @juliushaertl 
* [x] Container shouldn’t need to resize between slides, adjust content, fix height and width @juliushaertl 
* [ ] Button style difference too harsh, prev button should have slight white-ish background

## 📁 Files
* [x] **Non default views: First entry is overlapped by header** #16366
* [x] **When switching views and back to "All files" again, the upload bar x shows** https://github.com/nextcloud/server/issues/16137
* [x] If settings menu (bottom left) is open, show a border-top
* [x] In all views except "All files": Border around folder/files icons, should only be around images with preview #14849 
* [ ] Breadcrumbs ellipsis menu needs max-width and ellipsis of entries
* [ ] In the "Shared" view and in "Recent", favorites indicator is not shown
* [ ] Range selection with shift does not work
* [ ] When all are checked, don’t show "Select file ranges"
* [ ] Think about moving "Share current folder" icon out of breadcrumb but to the right
* [x] File list moving 1px vertically on select all (top border?) #16475
* [ ] Action menu shadow broken in Safari @nextcloud/mac

## 🍔 Sidebar
* [x] **Share link should not open menu automatically**
* [ ] Copy link directly when sharing with tooltip feedback "Share created & link copied"
* [ ] \~~~Share link flow revisit → 18~~\~
* [x] Fix outdated comment icon → pull request at https://github.com/nextcloud/server/pull/15881
* [x] Add to project second row has too much line height (test if it flows into 2 lines)

## 👥 Sharing
- [x] Fix placement of icon in public share page for audio files #16118

## 📄 PDF viewer
* [ ] Would be nice in white instead <https://github.com/nextcloud/files_pdfviewer/pull/7>

## 🔮 Recommendations
* [x] **Max-width for entries, ellipsize**
* [x] Recommendations are not quite flush left with the file list icons → pull request at https://github.com/nextcloud/server/pull/16084

## 🖼 Viewer
* [x] **"Play" should be called "Start slideshow"** https://github.com/nextcloud/nextcloud-vue/pull/449 (+ integrate the next release)
* [x] Background color issue with Slideshow button
* [ ] Possibly make the sidebar dark in picture viewer mode (not in Text app though)

## 🏷 Tags
* [ ] If there’s tags, show autocomplete dropdown directly on opening the "Tags" section. That is, autofocus the field so the dropdown shows.

## ⚡ Activity
* [x] **.mp4 filetype uses non-existing "video-mp4.svg" as mimetype icon, but we only have "video.svg" and should use that** https://github.com/nextcloud/server/pull/16095
* [ ] ~~Activity settings: Instead of "Stream" use setting for "Push notifications". Use icons for Mail and Phone. Just show everything in stream.~~ 2-4 weeks task
* [ ] If Calendar app is not installed, show "Install Calendar app" with link to apps mgmt in emptycontent view of "Calendar" in Activity stream
* [ ] Creation "+" icon looks interactive, bit confusing. Maybe different icon, maybe not use color

## 🖼 Gallery
* [x] Sort buttons to right and fix layout issues - https://github.com/nextcloud/gallery/pull/532
* [x] Remove "File list" icon in top right - https://github.com/nextcloud/gallery/pull/532
* [x] Fix the share menu confirm button white background (just use background-color: transparent;) nextcloud/gallery#526
* → Other Gallery stuff we should properly schedule

## 🔎 Search
* [x] ~~Show "Results from other folders" as a bigger header before the other results~~
* [x] Fix left-alignment of other results (move slightly to right to be same position as list view)

## 🔔 Notifications
* [ ] Put timestamp below message instead of on top right to not conflict with close x

## 👥 Contacts menu
* [x] We can add a button to "Install Contacts app" here https://github.com/nextcloud/server/pull/16104

## ⚙ Settings personal
* [x] Too much vertical whitespace between entries in "Personal settings"
* [x] Mobile & desktop settings: Check over wording of "Server address"
* [ ] Accessibility settings: prevent checking both High contrast and Dark theme
* [x] Remove "(beta)" label from Dark theme?
* [ ] Federated Cloud: Nice image or illustration and more info about what it does, compare <https://nextcloud.com/federation/>
* [x] Privacy: Add the icons of the user data manifesto
* [x] Privacy: Put country picker above world map, and directly highlight country when choosing
* [x] Privacy: Country highlight should be primary theming color instead of red nextcloud/privacy#179

## ⚙ Settings admin
* [x] **Logging: Take care that there’s no errors on default installation**
  - https://github.com/nextcloud/server/pull/16095 and https://github.com/nextcloud/server/issues/16039
* [ ] Overview: Make "Security scan" a button, and prefill current instance address
* [x] Overview: Version info i icon not vertically aligned correctly #16236 
* [x] Basic settings: Cron settings alignment issues: info i not correctly vertically aligned, detail text of radio buttons should be flush with first line #16236 
* [x] Groupware: Also text alignment issues, indent the subline to be flush with first line #16236 
* [x] Security: Sort blocks like this: Password policy, 2FA, Encryption, OAuth https://github.com/nextcloud/server/pull/16147
* [ ] Theming: Notification icon is not inverted immediately on bright color
* [ ] "Saving" indicators flashes between loading and "Saved", loading should only be shown if saving takes longer than X ms
* [ ] System: Look over the design ;))))
* [ ] System: Network: show boxes next to each other so it doesn’t use as much space vertically

## 🛠 Apps management
* [x] **Button to "Update all" is needed in "All apps" view**
* [x] **"No ratings" shows as 2.5 stars – should not show anything (also fixes issue of showing ratings for official apps)** https://github.com/nextcloud/server/pull/16141
* [x] Apps with update should have the counter inside a primary color bubble for attention - #452
* [x] Sidebar has two x buttons on the top right - https://github.com/nextcloud/server/pull/16122
* [ ] App bundles section shows "No apps found for your version" on the bottom
* [x] Spinner for "install" app should show inside button instead of above
* [ ] Sidebar info for untested apps should not show the text about "Dependency: server version 15 or lower required" but instead a sentence like "This app has not yet been marked as compatible with this server version, but you can install it at your own risk."
* [x] Right-click app needs an "Official" label @ChristophWurst https://github.com/nextcloud/server/pull/16145

## 👥 User management

* [ ] **"Language" dropdowns in the list overlap with next colum entries like "Storage location" if they are enabled** → PR at https://github.com/nextcloud/server/pull/17239

## ❓ Help
* [x] Add icons to the left sidebar

**Comment by jancborchardt** [comment]
cc @nextcloud/designers @nextcloud/vue and everyone really – if you want to pick up anything from this, you’re most welcome! :)

**Comment by enoch85** [comment]
Sorry, maybe a seperate issue but; 

**Viewer**
- [ ] Reinstate the delete trashcan button

**Comment by jancborchardt** [comment]
@enoch85 this is for small quick polishing mainly. Can't judge the workload on that one but seems like it might better be a separate issue. :)

**Comment by enoch85** [comment]
Here it is: https://github.com/nextcloud/server/issues/16078

**Comment by ChristophWurst** [comment]
>     * Because of .map files?

No. They are not that big. It's mainly Cypress in viewer that caused the jump.

**Comment by ChristophWurst** [comment]
> Missing loading feedback on installation, should have a spinner

It's there. But since we're submitting a form the new page is loaded and AFAIK Safari stops rendering in that case. That is the same issue as with the apps/settings menu. https://github.com/nextcloud/server/blob/c8e617b07c2df1e85f5504cca11e438921a3aafd/core/js/setup.js#L57

**Comment by ChristophWurst** [comment]
> **Button to "Update all" is needed in "All apps" view**

I'm afraid this isn't a simple fix but requries more afford. Hence it's not really polishing but a new feature.

**Comment by Thatoo** [comment]
Would it be possible to get an an API that fully, properly and easily manage mimetypes?
https://github.com/nextcloud/server/issues/9192
Usability of some apps are reduced by lack of it.
For example Keeweb is not click&play because .kdbx are not recognized by nextcloud and when we click on our keepass database, it invites us to download it instead of opening Keeweb.

**Comment by skjnldsv** [comment]
@Thatoo this is not the issue to ask questions :)
As you mentioned, #9192 is the issue to discuss it.

**Comment by kesselb** [comment]
![Screenshot from 2019-09-28 15-37-53](https://user-images.githubusercontent.com/3902676/65817403-bbcd8400-e206-11e9-8f8f-2778cdc56628.png)

![Screenshot from 2019-09-28 15-38-11](https://user-images.githubusercontent.com/3902676/65817406-c12ace80-e206-11e9-8d5a-f57db6080ffa.png)

Arrow right looks a bit off :arrow_right: 

![Screenshot from 2019-09-28 15-39-42](https://user-images.githubusercontent.com/3902676/65817417-e3245100-e206-11e9-888b-ecb8ee7c04e4.png)

I think we could improve the wording a bit. Like yeah you made it :tada: :beers: You can close this window now should be on a new line.

**Comment by sunjam** [comment]
> I think we could improve the wording a bit. Like yeah you made it 🎉 🍻 You can close this window now should be on a new line.

### Congratulations!
Account access granted!
You can close this window.

**Comment by jancborchardt** [comment]
@kesselb could you open a separate issue for that? We usually don’t really add stuff to the polishing list much later. :) There’s always a next polishing round too.

**Comment by jancborchardt** [comment]
It’s been a few months since the polishing review and most of the issues were fixed. :) So as per usual, we’re going to close the issue and open a new one at the next polishing review.

For any leftover issues which you think should be fixed, please open a separate issue or – even better – a pull request to fix them. :tada:
