### ISSUE TITLE
Better calendars (CalDAV) integration into NC

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#1642]
A few ideas here : 
- [x] Send emails for reminders (`VALARM : EMAIL` see https://github.com/owncloud/core/issues/22734)
  I've started work on this by using a hook when a calendarobject is created/updated/deleted and looking for VALARMs in the `$calendarData`. In that case, we can save the reminder in a dedicated table and run a background job that takes care of sending the emails when it's time
- [x] Show notifications for reminders through [the notification app](https://github.com/nextcloud/notifications) `VALARM : DISPLAY`
  Just like what's I've described before, but send a notification instead of an email.
- ~~Play a sound for notification. This may be harder. `VALARM: AUDIO`~~
- [x] Show upcoming events (and maybe more calendar actions) in [the activity app](https://github.com/nextcloud/activity). I guess there's a going to be a lot of discussion here, since I don't know you see the future of this app. https://github.com/nextcloud/server/pull/1733
- [ ] Make calendar shares acceptable (through notifications) #19568
- [ ] Make calendar shares federated-compatible. #1440

Please give some input :-)

**Comment by nickvergessen** [comment]
Well let me split this up:
1 and 2 are to be implemented in the dav app
3 however needs to be part of the calendar app
4 "upcoming events" is nothing the activity app can take care of. activity app is more of a "timeline" and therefor a backwards view. I'm currently working on activities for calendar creation/update/deletion/share and the same for events. However an "upcoming" view should be more of a separate thing, maybe the calendar app can finally have an "agenda" style 😉 - cc @georgehrke 

5 and 6 sound like nice features. Not sure who has any knowledge about dav + federated sharing thou

**Comment by nickvergessen** [comment]
One more note about 1+2:

Once we have the notification API implemented on the phone, this will be really annoying. Because most people have their calendars also on their phone, you will get multiple system notifications for the same event (one from nextcloud, one from your calendar app)?

**Comment by tcitworld** [comment]
>  3 however needs to be part of the calendar app

My idea was that the sound would be played even if you're currently not using the calendar app, therefore I was thinking expanding the possibilities of the notification app for this.

> maybe the calendar app can finally have an "agenda" style

It comes with FullCalendar 3, so this should come soon. Happy to know calendar actions will be handled by the activities app.

> Once we have the notification API implemented on the phone

I don't know what you're talking about. The notifications from nextcloud will be synced to the nextcloud mobile app ? I guess we can identify from which app the notifications are coming from and deactivate them on the mobile client.

**Comment by georgehrke** [comment]
There is an issue for federation already: https://github.com/nextcloud/server/issues/1440

**Comment by georgehrke** [comment]
> Play a sound for notification. This may be harder. `VALARM: AUDIO`

I completely agree with @nickvergessen here. This has to go in the calendar app.
There is an issue for that already: https://github.com/nextcloud/calendar/issues/51

> It comes with FullCalendar 3, so this should come soon. Happy to know calendar actions will be handled by the activities app.

Yes, we are already running fullcalendar 3. There has been some issues with the list view in fullcalendar 3.0.0, but there were list-view-related fixes in 3.0.1.

> Make calendar shares acceptable (through notifications)

Are there plans to make file shares acceptable too?
This should ideally be consistent among files, calendar and contacts.

> Not sure who has any knowledge about dav + federated sharing thou

Me and @schiessle :)

**Comment by tcitworld** [comment]
> Are there plans to make file shares acceptable too?

I was inclined to think so considering the screenshots on https://github.com/nextcloud/notifications

**Comment by nickvergessen** [comment]
> Are there plans to make file shares acceptable too?

yes, currently only federated shares, but normal shares will follow soon.

**Comment by tcitworld** [comment]
And now since every item is either taken care of or has its own issue, let's close this one.
