### ISSUE TITLE
Can not delete group shared calendars (and addressbooks I guess)

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1653]
### Steps to reproduce
1. As user1 share a calendar with group1
2. As user2 (member of group1) delete the calendar
3. Refresh the page
### Expected behaviour

At 2. Calendar vanishes form the list + Status OK
At 3. Calendar should not be there
### Actual behaviour

At 2. Calendar vanishes form the list + Status Forbidden
At 3. Calendar is back
### Server configuration

**Nextcloud version:** git-master

**List of activated apps:**

```
Enabled:
  - activity: 2.4.0
  - calendar: 1.4.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_sharing: 1.1.0
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - workflowengine: 1.1.1
```

## Work packages

- [x] Allow individual unshare in backend
- [x] Adjust Contacts front-end to say *Unsare* instead of *Delete*
- [ ] User manual documentation

As a work around we could ask the calendar to show an error instead of deleting the calendar from the list, when deletion failed (cc @georgehrke ). But I guess what we really want to do is allow to unshare group-shares just like normal shares.

**Comment by tcitworld** [comment]
Was the calendar shared with write access ?

**Comment by nickvergessen** [comment]
Happens in both cases

**Comment by georgehrke** [comment]
> But I guess what we really want to do is allow to unshare group-shares just like normal shares.

Well, but do you really want to allow one user to unshare the calendar for everyone else in the group? 
What's the behavior in the files app here?

**Comment by nickvergessen** [comment]
Files you get excluded from the share, not the whole group.

**Comment by nickvergessen** [comment]
However we patched the share behaviour for 12 here. I think you are not allowed to delete group shares as recipient anymore.

**Comment by georgehrke** [comment]
> However we patched the share behaviour for 12 here. I think you are not allowed to delete group shares as recipient anymore.

In that case the same behavior should apply to CalDAV sharing, right?

**Comment by nickvergessen** [comment]
yeah it's in the dav sharing backend

**Comment by MorrisJobke** [comment]
@georgehrke Is this still feasible for 16?

**Comment by georgehrke** [comment]
No, we can't simply extend the files solution to CalDAV and CardDAV but need to reimplement it.
Removing from any milestone, needs discussion at feature planning.

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by xeruf** [comment]
Still occuring in 25.0.4, sadly...

**Comment by Hk1020** [comment]
Now it is 2023, nearly 7 years later after the issue has been opened and I still have the problem. I am at 27.1.1

**Comment by miaulalala** [comment]
Fixed by https://github.com/nextcloud/server/pull/43117

**Comment by ChristophWurst** [comment]
> Adjust Contacts front-end to say _Unsare_ instead of _Delete_
> User manual documentation

pending

**Comment by ChristophWurst** [comment]
> User manual documentation

Still missing at https://docs.nextcloud.com/server/latest/user_manual/en/groupware/contacts.html#adding-and-managing-address-books

**Comment by miaulalala** [comment]
Documentation is done: https://github.com/nextcloud/documentation/pull/11609
