### ISSUE TITLE
Switching to scss

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#1786]
This is becoming more and more needed. The more we wait, the harder it will gets for us to make the switch later.

Sooooooo let's do this!
### Why
1. **Nesting and code readability**. This is an insane advantage to have. Right now the code have a basic structure, but it's still very hard to find whatever you're searching.
2. **Size**. Scss files are significantly lighter than css. if correctly implemented, the generated css file should still be lighter than what we currently have.
3. **Redundancy**. Actually we have a lot of similar stuff that would be great to merge (inputs.css for example)
4. **Variables**. Will definitely improve the overall design guidelines for this project and allows pretty much anyone to quickly edit a global var for customisation.
### Goals
- Only increase the entry barrier with the scss language. No sass lib needed, no core compilation...
- Use caching for freshly compiled css
- Do not compress output if debug enabled (for devs)
- Rewrite all css into scss with proper nesting
- Convert and regroup similar used colours into variables
### Numbers
- First commit with a basic css to scss conversion and compression enabled saves 10.965KB
### Roadmap
- [x] Use on-the-fly scss compiler so no one has to install anything
- [x] Cache system
- [x] Detect and change url on compiled files
- [x] Convert css to scss
  - [x] apps.css
  - [x] ~~fixes.css~~
  - [x] ~~fonts.css~~
  - [x] ~~global.css~~
  - [x] header.css
  - [x] icons.css
  - [x] inputs.css
  - [x] jquery-ui-fixes.css
  - [x] ~~jquery.ocdialog.css~~
  - [x] ~~mobile.css~~
  - [x] multiselect.css
  - [x] share.css
  - [x] styles.css
  - [x] systemtags.css
  - [x] tooltip.css
  - [x] ~~update.css~~
- [x] Switch to AppData 
- [x] Tests
- [x] Finish guest.css file
- [x] Cleanup scss files
  - [x] Fix copyrights
- [ ] List and regroup variables into variables.scss
- [ ] Regroup and merge keyframes into animations.scss
### Optionnal
- [x] Compress css on compiling (if no debug mode)
- [x] Added original SCSS line numbers for better frontend debugging (if debug mode)

@Henni @MorrisJobke @BernhardPosselt @jancborchardt

**Comment by LukasReschke** [comment]
>  Use on-the-fly scss compiler so no one has to install anything

If that is possible 👍

**Comment by jancborchardt** [comment]
Yup, as talked about if we have an on-the-fly SCSS compiler it’s good. :) If not it’s a very annoying barrier.

**Comment by skjnldsv** [comment]
Yep! This is mandatory!

**Comment by raghunayyar** [comment]
well, this can be integrated with the task runners we use for the applications at-least. So, no additional steps for the app standpoint.
I am super happy for us to move to sass, it has been long pending.

**Comment by skjnldsv** [comment]
@raghunayyar you mean cron? How will we handle the compiling if the user load nextcloud but the cron hasn't started?

**Comment by jancborchardt** [comment]
@raghunayyar having a task runner for core development is exactly what we want to avoid ;) it’s about on-the fly CSS generation.

**Comment by raghunayyar** [comment]
@skjnldsv I meant something like grunt / gulp / webpack. But @jancborchardt seems legit about avoiding that hastle in core. It can be taken in account for apps though.

**Comment by MorrisJobke** [comment]
> @skjnldsv I meant something like grunt / gulp / webpack.

No way. We will not introduce such stuff - it only confused people - new ones in the same way as existing contributors.

**Comment by Espina2** [comment]
Really nice that you guys switch. I agree 200% with @raghunayyar we should have a task runner to. 

@MorrisJobke I don't think you can confuse people if you only to run one command to run the taskrunner. Grunt serve, or Gulp serve its very easy and remove complexity.

**Comment by skjnldsv** [comment]
No we won't implement this. This has been discussed sooo many times before, and we want to avoid that. Having a direct compilation and a cache system is the easiest way.

**Comment by Espina2** [comment]
As you guys want, its a step forward anyway. Just thinking in what is more easy. I just think its more easy to new guys have the project if you have taskrunner that install all the depencies. But it can be only me.

**Comment by Henni** [comment]
@Espina2 @skjnldsv is working on a way to integrate scss without any development dependencies at all. Instead nextcloud will compile scss to css on the fly.

**Comment by Espina2** [comment]
@Henni 

I know what it is. This are introduced in nextcloud website, but removed after some time. I don't this are a good practice have a script that compiles the code. It will load all the page with only html and after some time it compile the code. If you are in a slow network this will hurt a lot. 

So if this script is only for develpment I think its okay, if are for production I don't think so...

**Comment by skjnldsv** [comment]
As far as I can tell, my server isn't having any trouble. And it's a one-time compilation. Lambda user won't have any issue.

**Comment by BernhardPosselt** [comment]
@Espina2 afaik its compiled using PHP, not the JavaScript compiler

**Comment by Espina2** [comment]
@BernhardPosselt @skjnldsv 
I'm not sure, but i guess that work's in the same way. It always have to check if the file have differences, so How its possible to not only to compile one time?

**Comment by skjnldsv** [comment]
Well on a non-dev user installation, the css won't change except maybe after an update. So only a single compilation will ensue.

**Comment by Espina2** [comment]
So what you are saying is when this are released you only have the css compiled in the folder, dnd further "tweaks" should be done in that css file?

**Comment by BernhardPosselt** [comment]
I suppose the first web request will compile it

**Comment by Spacefish** [comment]
"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'Leafo\\\\ScssPhp\\\\Compiler' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(90): OC\\\\Template\\\\SCSSCacher->cache('\\\/var\\\/data\\\/www\\\/c...', 'styles.css', 'styles.scss', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), 'core\\\/css')\\n#1 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(88): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/data\\\/www\\\/c...', 'core\\\/css\\\/styles...')\\n#2 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(55): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/data\\\/www\\\/c...', 'core\\\/css\\\/styles...')\\n#3 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/styles')\\n#4 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/TemplateLayout.php(210): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#5 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/TemplateLayout.php(166): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#6 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/legacy\\\/template.php(232): OC\\\\TemplateLayout->__construct('user', 'files')\\n#7 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#8 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#9 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#10 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#14 \\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/index.php(40): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/data\\\/www\\\/cloud.neosolve.de\\\/htdocs\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php\",\"Line\":125}","level":3,"time":"2017-01-08T02:02:16+00:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"Spacefish","version":"12.0.0.12"}

:( guess this is related to this?

**Comment by MorrisJobke** [comment]
@skjnldsv I think this one is done :) We could refine based on the current state step by step if needed. Thanks for this awesome contribution :)

**Comment by skjnldsv** [comment]
@MorrisJobke 💘
