### ISSUE TITLE
Show system address book as read-only address book in contacts

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#19575]
In organizations it is quite common that you want to have a shared address book with the contact data of all your colleagues.

Today you can achieve this with a address book created within the contacts app and shared with all others. But this has some issues:

1. If you share it read-only someone has to be in charge to keep it up to date
2. If you share it read-write so that everyone can add their own contact data people have to maintain their information twice, once in "contacts" and once in the personal settings.
3.  If you share it read-write you risk that people delete contacts by accident, add contacts which doesn't belong to the address book, etc

All information from the personal settings are already written to a carddav system address book. So technically we already have everything we need in the back-end. The idea is to expose it to the contacts app for all users and via carddav in a read-only mode. This way:

1. Every time someone updates their personal settings or if they are updated in a central user management like LDAP the address book will be updated as well.
2. People don't have to maintain their information in multiple places
3. You don't risk that people delete contacts by accident or add personal contacts which doesn't belong to the address book.

~~Of course there should be a Admin switch to enable/disable this behavior. In most organizations this will be quite useful but of course a shared hoster for example doesn't want to present all users in a address book to all the other users (Although keep in mind that they do it already though the "people menu" which can not be disabled so the feature suggested here has no additional impact on the users privacy).~~ The feature should respect the existing sharing and user enumeration settings.

## Acceptance criteria

* Data sources
   1) User backend
   2) Profile
     * Respect profile privacy settings
* Exposed as read-only CalDAV collection
  * Has to be listable in Contacts app 
  * Has to be readable by CalDAV clients
  * Name: "Accounts" (should have localized display name, if possible)
* Respects sharing settings for user enumeration
* Do not show in share dialogue (would duplicate users)
* Org chart continues to work
* Mapping
  * Manager -> X-MANAGERSNAME (set by admin via user management, not the user)
    * Optional: map from LDAP
  * Display name -> FN
  * Primary email addresses -> EMAIL (without TYPE)
  * Secondary email addresses -> EMAIL (without TYPE)
  * Phone number -> TEL (without TYPE)
  * Organisation (to be renamed to Company) -> ORG
  * Role (to be renamed to Title) -> TITLE
  * Location -> ADR
  * Language -> LANG
  * Profile page ``https://cloud.domain.tld/u/<uid>`` (if enabled) -> URL
  * Optional: ``https://cloud.domain.tld/apps/spreed/?callUser=<uid>`` -> URL
  * Optional: Nextcloud groups -> CATEGORIES (if possible and OK with data privacy)

## Work packages

- [x] https://github.com/nextcloud/server/issues/38141
- [x] https://github.com/nextcloud/server/issues/38021
- [x] https://github.com/nextcloud/server/issues/37800
- [x] https://github.com/nextcloud/server/issues/37963
- [x] https://github.com/nextcloud/server/issues/37797
- [x] https://github.com/nextcloud/contacts/issues/3317
- [x] https://github.com/nextcloud/contacts/issues/2187
- [x] https://github.com/nextcloud/documentation/issues/10020
- [x] https://github.com/nextcloud/documentation/issues/10021
- [x] https://github.com/nextcloud/server/issues/37799
- [x] https://github.com/nextcloud/server/issues/37798
- [ ] Add repair step to remove all guest users from system address book

**Comment by schiessle** [comment]
People think it makes more sense to have it in the server repo, although from my understanding it is mainly a "contacts" app question if and how the app exposes the address book which already exists in the server. Nevertheless I will let others figure it out.

I I think it is a well defined use case which makes sense to discuss independent from https://github.com/nextcloud/server/issues/693 which went in many different directions. That's why I prefer to keep it as a separate issue.

I don't see a privacy issue here because the exact same information are already exposed over the "people menu" which is always enabled (no way to disable it) while the suggested feature here would be opt-in.

**Comment by jospoortvliet** [comment]
I agree that 'just' solving this basic case is legit. It doesn't have the privacy issue (as it can and should respect the privacy settings in the user settings) and provides a useful feature on internal/private instances while it can be disabled (or should be off by default?) on public/hosting provider instances. We might be able to get away without a setting as we have other settings for hosting provider like instances already, in sharing (don't auto-complete or something like that).

**Comment by SomeFixItDude** [comment]
Please implement this feature. 

We also use nc to sync contacts to mobile devices. Since we need phone numbers and email addresses the same exact users in the system contacts are also in the users contacts. As a result, when in the files app and you want to share a file you begin typing in the name of the user. Two entries pop-up and we are counting on the user clicking the system user.

Thank you!

**Comment by adamshand** [comment]
Has there been any progress on this?  It would be very helpful if system users could show up in contacts!

**Comment by whiskeytangofoxy** [comment]
+1 for another interested user in this feature.

**Comment by jancborchardt** [comment]
Very related issue, possibly duplicate @ChristophWurst https://github.com/nextcloud/contacts/issues/2361

**Comment by scratch-a** [comment]
Đã gửi từ iPad của tôi

Ngày 17 thg 3, 2022, vào lúc 20:18, Jan C. Borchardt ***@***.***> viết:

**Comment by svtcpxdev** [comment]
A Users and Groups directory would be very useful indeed.

**Comment by R7JANV1** [comment]
Is there any progress on this? Is there any progress on this? Synology and co all have this feature.

**Comment by svtcpxdev** [comment]
> Is there any progress on this? Is there any progress on this? Synology and co all have this feature.

Not really, no. They seem to think that people in the same organisation are not allowed to see other people working in the organisation. I find that to be a bit extreme, given you usually do know the people you work with anyway and that in most orgs people use their business contact info and not their private ones but you know, "privacy concern" is a great argument to weasle yourself out of doing work too these days. Collaboration by it's very definition eliminates user privacy to some degree. At this point, I'm considering hiring a developer myself to build an app that list the users and groups (read only). Will update if and when that happens.

**Comment by R7JANV1** [comment]
I think the developers are doing their best. And I hope we will eventually find a solution. All the organizations I know use such a feature whether at Teams, Synology, ... and with Nextcloud we still have to add it manually. I don't think it's a permanent solution and believe sooner or later the feature will come.

Personally, I do not see any concerns of such a function. But we can talk about it here.

@nickvergessen @jancborchardt @ChristophWurst What speaks for the moment against such a function?

**Comment by svtcpxdev** [comment]
> I think the developers are doing their best. And I hope we will eventually find a solution. All the organizations I know use such a feature whether at Teams, Synology, ... and with Nextcloud we still have to add it manually. I don't think it's a permanent solution and believe sooner or later the feature will come.
> 
> Personally, I do not see any concerns of such a function. But we can talk about it here.
> 
> @nickvergessen @jancborchardt @ChristophWurst What speaks for the moment against such a function?

I know, I was being sarcastic. Their argumentation on this matter are mostely mentioned in this thread:
https://github.com/nextcloud/server/issues/693

**Comment by R7JANV1** [comment]
> > I think the developers are doing their best. And I hope we will eventually find a solution. All the organizations I know use such a feature whether at Teams, Synology, ... and with Nextcloud we still have to add it manually. I don't think it's a permanent solution and believe sooner or later the feature will come.
> > Personally, I do not see any concerns of such a function. But we can talk about it here.
> > @nickvergessen @jancborchardt @ChristophWurst What speaks for the moment against such a function?
> 
> I know, I was being sarcastic. Their argumentation on this matter is mentioned in this thread: #693

Thank you, I have already read it. But that was a few years ago now and maybe something has changed since then.

**Comment by nickvergessen** [comment]
If it works for your personal usecase that's great, but doesn't work for:
* providers: think of a provider giving you free accounts or allowing you to buy storage space
* university/schools: giving you access to the names and details of thousands others

**Comment by R7JANV1** [comment]
> If it works for your personal usecase that's great, but doesn't work for:
> 
>     * providers: think of a provider giving you free accounts or allowing you to buy storage space
> 
>     * university/schools: giving you access to the names and details of thousands others

Therefore, the function could be disabled by default and the system address book is created and displayed only when enabled.

**Comment by SomeFixItDude** [comment]
Be nice if this was implemented and configurable. Issue been open for 2 years, so not looking like it will be.

**Comment by givors-anabasis** [comment]
A major downside of how things work for now is that when I want to invite a user to an event in the calendar, things work differently if I select the contact or the user… :-(

**Comment by clayrisser** [comment]
I'm still watching this. Looking forward to it as well.

**Comment by mrtn223** [comment]
This would be a very cool feature - I‘d be very happy to see it implemented.

**Comment by miaulalala** [comment]
@schiessle what about federated sharing? I saw some code instances where federated sharing was accessing the system address book. Should this behaiour be influenced by the backend option I have added?

**Comment by miaulalala** [comment]
Split in work packages:

- [ ] Expose address book (respect share enumeration)
- [ ] Research: federated sharing and the system address book 
      - how does federated sharing work 
      - will exposing the address book break the instance encapsulation (i. e. are other system address books accessible through federated sharing, is that wanted, what happens with share enumeration etc)
- [ ] Fix search provider enumeration (with backports to 25) if it's not already filtered somewhere else
- [ ] Write profile information to system address book (with above mentioned mappings) and map backend properites to above mentioned mappings

**Comment by tcitworld** [comment]
> I saw some code instances where federated sharing was accessing the system address book. Should this behavior be influenced by the backend option I have added?

Trusted servers exchange each other's system addressbooks, in order to ease file sharing with users from external servers. As federation is limited to file sharing at the moment, I don't think we should expose those addressbooks as well.

**Comment by tcitworld** [comment]
Nope, everything seems to be exposed. The only way to filter them may be to use [the `CLOUD` property](https://github.com/nextcloud/server/blob/1a255379e85f02f3fb301f709720f3210f56b011/apps/dav/lib/CardDAV/Converter.php#L97-L101).

**Comment by miaulalala** [comment]
> Nope, everything seems to be exposed. The only way to filter them may be to use [the `CLOUD` property](https://github.com/nextcloud/server/blob/1a255379e85f02f3fb301f709720f3210f56b011/apps/dav/lib/CardDAV/Converter.php#L97-L101).

But also `$shareWithTrustedServers` needs to be set to true/yes, no? That could possibly be enough.

**Comment by schiessle** [comment]
tested with @miaulalala: Each server has their own address book:

![image](https://user-images.githubusercontent.com/1589737/234312294-e6f170f5-99cb-463d-9864-e02fbae60710.png)

**Comment by ChristophWurst** [comment]
## Observation: Ghost Users

Only users with at least one published property get added to the system address book. Impact: someone restricting their profile properties to *Local* or *Private* vanishes from the system address book.

![Bildschirmfoto vom 2023-04-28 12-43-02](https://user-images.githubusercontent.com/1374172/235127510-c4d11134-78b5-469b-a67b-6b7577cc7a65.png)

It appears that only publishable data is materialized in the system address book. Data for local use only is not there.

The logic sits at ``\OCA\DAV\CardDAV\Converter::createCardFromUser``. The required scope for the system address book enrollment is *federated* or *published*.

**Comment by ChristophWurst** [comment]
Idea: materialize all properties that are at least *local*. Those props should be readable to other users. Store the scope next to the prop value inside the vcard and when we send data to another server we filter out all properties with the local scope, so only published and federated data remains.

Alternative: build two materialized address books. One for local use (system address book in the new sense) and a federation addres book (system address book in the old sense).

**Comment by ChristophWurst** [comment]
> All information from the personal settings are already written to a carddav system address book. So technically we already have everything we need in the back-end.

We do not. The address book only contains federated and published data. Local data (which would be ok to expose to others) is missing as per above.

**Comment by schiessle** [comment]
> Idea: materialize all properties that are at least _local_. Those props should be readable to other users. Store the scope next to the prop value inside the vcard and when we send data to another server we filter out all properties with the local scope, so only published and federated data remains.
> 
> Alternative: build two materialized address books. One for local use (system address book in the new sense) and a federation addres book (system address book in the old sense).

I discussed the second option with @miaulalala but I like the first idea with the prop value if it is technically feasible to filter during the sync process. This would avoid having yet another address book.

**Comment by tcitworld** [comment]
> Local data (which would be ok to expose to others) is missing as per above.

There *should* be a way to opt out of system addressbook, for instance on a server where not everybody has to know each other. Otherwise you can just create lists of users, which can be troublesome.

**Comment by ChristophWurst** [comment]
> > Local data (which would be ok to expose to others) is missing as per above.
> 
> There _should_ be a way to opt out of system addressbook, for instance on a server where not everybody has to know each other. Otherwise you can just create lists of users, which can be troublesome.

It is planned for the system address book to respects share enumeration settings. If an admin configures Nextcloud to now show other users, the system address book will also not show anyone else.

**Comment by miaulalala** [comment]
> > Add repair step to remove all guest users from system address book
> 
> @miaulalala is this still to do or done with the filter for guest users when exposing the SAB?

I thought that was done with the Migration but that doesn't seem to be the case. I will look into it.

**Comment by jakobroehrl** [comment]
Are there any plans to extend the profile?
It would be nice if the user could add a second telephone number, address and birthday date and these fields should shown up in the auto generated contact

**Comment by tcitworld** [comment]
@jakobroehrl Please create a new issue for this request (search for existing ones first).

**Comment by ChristophWurst** [comment]
> > > Add repair step to remove all guest users from system address book
> > 
> > 
> > @miaulalala is this still to do or done with the filter for guest users when exposing the SAB?
> 
> I thought that was done with the Migration but that doesn't seem to be the case. I will look into it.

Can't see what's missing in the current state. Seems fine.

**Comment by ChristophWurst** [comment]
From my notes

> Options
> 1. Expose system address book as is, with guest users
> 2. Exclude guest users
> 3. Somehow try to separate guest users
> 
> Seems 1 is simplest, 3 is the best case, but 2 might be the best balance

So currently real users see guest users but guest users don't see anyone else. It's the simplest yet acceptable solution.

**Comment by chrisherzberg** [comment]
Hi all,
is their any update on this topic? We are using nextcloud 27.0.2 and would like to access the system address book via cardDav but we can´t. The personel addrssbook works fine.
Thanks
Christian
