### ISSUE TITLE
Overview: Calendar Sharing

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#20096]
This is an overview ticket for feature requests / bugs related to Calendar Sharing:

## Sharing
- [ ] [#1600 Allow (internal) sharing of subscribed webcal calendars](https://github.com/nextcloud/server/issues/1600)
- [ ] [#1440 Federated calendar and contacts sharing](https://github.com/nextcloud/server/issues/1440)
- [ ] [#1653 Can not delete group shared calendars](https://github.com/nextcloud/server/issues/1653)
- [ ] [#19568 Accept or decline calendar shares through notifications](https://github.com/nextcloud/server/issues/19568)
- [ ] [#5551 group member can overwrite private appointment](https://github.com/nextcloud/server/issues/5551)
- [ ] [#11214 Share calendar to users or groups with "show only as busy"](https://github.com/nextcloud/server/issues/11214)
- [ ] [#19827 Per-user settings for shared events](https://github.com/nextcloud/server/issues/19827)

## Publishing
- [ ] [#3509 Allow editing on publicly shared calendars](https://github.com/nextcloud/server/issues/3509)
- [ ] [#11214 Share calendar to users or groups with "show only as busy"](https://github.com/nextcloud/server/issues/11214)

**Comment by georgehrke** [comment]
cc @tcitworld 
cc @rullzer for feature planning :)

**Comment by georgehrke** [comment]
One of the biggest issue when it comes to publishing is that each calendar is limited to one publishing link.

This is causing many issues that you can't simply revoke a calendar without breaking embedded calendars / having to send out a new public link to people who should still have access.

In order to solve any of the publishing related tickets mentioned above, we first need support for multiple publishing links. Once we have support for that, adding support for more sharing types including "internal busy", "public busy", "public editable", "public busy editable" should be straight forward.

**Comment by georgehrke** [comment]
Once we have support for these public types, adding password-protected public shares would also be straight forward.

**Comment by georgehrke** [comment]
Overall tasks:
- [ ] discuss new columns that have to be added to `dav_shares`.
- [ ] discuss changes to CalDAV sharing and publishing API.

**Comment by georgehrke** [comment]
also cc @raimund-schluessler @skjnldsv 

This will require changes to `cdav-library`, but i aim at implement them in a backward-compatible way.

**Comment by tcitworld** [comment]
Can `cs:publish-url` handle multiple URLs ? We'll have to go with our own thing otherwise.

**Comment by georgehrke** [comment]
> Can cs:publish-url handle multiple URLs ? We'll have to go with our own thing otherwise.

Not as far as i can tell. We would have to move to our own implementation.

**Comment by favincen** [comment]
Hi. I suggest to add also a link to issue "Send invitations for shared calendars" #26668 , as it is about shared calendars expected features.

**Comment by favincen** [comment]
Another issue that could be referenced in this overview about calendar sharing: #5050

**Comment by ESIETP** [comment]
Hi, maybe the "No invites, but invite cancellations sent from shared calendars" #20278 is also a part of this?

**Comment by tcitworld** [comment]
That's a bug, not a feature.

**Comment by ZID-TU-Graz** [comment]
I suggest to add #19994 (as mentioned in the this issue, the problem still occurs in our installation, NC Version 26.0.4)

**Comment by gnrfzui** [comment]
> I suggest to add #19994 (as mentioned in the this issue, the problem still occurs in our installation, NC Version 26.0.4)

Seconded: #19994 is still open with NC 27.1.5 and Calendar 4.6.6

**Comment by PeonyThePeon** [comment]
I suggest adding https://github.com/nextcloud/server/issues/61388 to this overview list.
