### ISSUE TITLE
Nextcloud 11 release review

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#2134]
- [x] change from 9.2 to 11.0 **PR:** https://github.com/nextcloud/server/pull/2139
- [x] spreed call **PRs:** nextcloud/spreed#89, nextcloud/spreed#90, nextcloud/spreed#91
- [x] firstrunwizard doesn't show up ( https://github.com/nextcloud/firstrunwizard/pull/24 )
- [x] firstrunwizard:
  - [x] ~~capital A in first sentence~~
  - [x] documentation button is not needed https://github.com/nextcloud/firstrunwizard/pull/22
  - [x] alignment of button text wrong
  - [x] change URL to docs.nextcloud.com (https://github.com/nextcloud/server/pull/2145)
  - [x] fix theming translation with tab sign PR https://github.com/nextcloud/server/pull/2131
- [x] sharing settings:
  - [x] by default disable automatic federation trust (@schiessle https://github.com/nextcloud/server/pull/2178)
- [x] rename "Usage report" to "Usage survey" PR https://github.com/nextcloud/survey_client/pull/43
- [x] files (@jancborchardt)
  - [x] sharing: delete delete button PR https://github.com/nextcloud/server/pull/2136
  - [x] sharing - ellipsise user name & align options PR https://github.com/nextcloud/server/pull/2136
  - [x] tooltip of sharing "i" PR https://github.com/nextcloud/server/pull/2132
- [x] files sidebar
  - [x] think about "Hide file listing" - **PR:** #2243
- [x] language name (@morrisjobke) **PR:** #2423
- [x] collaborative tags settings:
  - [x] fix layout of the "Select tags" input field #2133
- [x] replace log with: https://github.com/icewind1991/logreader
- [x] Fix error log (@lukasreschke)
- [x] Apps management settings are empty? https://github.com/nextcloud/server/issues/2183
- [x] setup page - loading spinner should collapse the details to not mess with the layout https://github.com/nextcloud/server/issues/2129 PR https://github.com/nextcloud/server/pull/2242
- [x] app passwords
  - [x] "copy icon" needs tooltip (@rullzer) – also for share link and Federated Cloud ID copy icon ( https://github.com/nextcloud/server/pull/2146 )
  - [x] add default name is none is added https://github.com/nextcloud/server/pull/2220
- [ ] theming:
  - [x] move reset field into field & only show it when in the field (@jancborchardt) PR 
  - [x] layout bug if checkboxes #2157
  - [x] add a file selector for both images https://github.com/nextcloud/server/pull/2151
  - [ ] click on image: open file chooser 
- [ ] admin settings:
  - [x] social icons needs to below updater (https://github.com/nextcloud/server/pull/2150)
  - [x] german translation of "Developed by the Nextcloud community" (@morrisjobke)
  - [x] left sidebar has white space blocked on bottom even if there is no settings button **PR:** #2283
  - [ ] condense updater texts
  - [ ] make input field of update groups smaller
  - [ ] ~~security section (move password policy there)~~ 
- [ ] Spreed
  - [x] stun server: default stun server maybe set to something else https://github.com/nextcloud/spreed/pull/88
  - [x] personal turn server setting **PR:** https://github.com/nextcloud/spreed/pull/84
  - [x] admin turn server setting **PR:** https://github.com/nextcloud/spreed/pull/120
  - [ ] **1.0 milestone issues** https://github.com/nextcloud/spreed/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0
- [ ] inform community about version change from 9.2 to 11.0 see https://github.com/nextcloud/server/pull/2139
- [ ] files:
  - [ ] favorite - remove spinner on default (maybe show it when the request takes longer than 1 second – but then definitely do not show it in place of the filetype icon)
  - [ ] improve contrast of sidebar (selected element) - make bold? make text color the themed one?
- [ ] gallery:
  - [ ] move delete & download to name (jancborchardt @icewind1991)
- [ ] avatar cropper (@icewind1991):
  - [ ] make it bigger
  - [ ] remove radio box
- [ ] server info:
  - [ ] CPU info - check for 0 - sys_getloadavg
  - [ ] number of files might be wrong
  - [ ] change "files" to "files in data directory"
  - [ ] input field for external URL with copy link
- [ ] app management:
  - [ ] markup for discription
  - [ ] user_external needs an update of the supported version

----

Stuff from #735

- [ ] apps:
  - [ ] proper descriptions (3 sentences)
  - [ ] external sites doesn't work (without page reload)
- [ ] admin settings
  - [ ] external sites: remove PNG, show default icon next to button, Rename drop down to "Change different icon"

**Comment by rullzer** [comment]
> firstrunwizzard: capital A in first sentence

That is actually just taking the theme slogan.

**Comment by jancborchardt** [comment]
> That is actually just taking the theme slogan.

Yup, I just talked with @MariusBluem and we decided to leave it. Our options are:
- change the theme slogan. Then it looks crappy in the footer »Nextcloud – A safe home for all your data« (the sentence begins with »Nextcloud« already)
- have two separate strings – :'D no way
- capitalize it via CSS: people who theme will be confused
- leave it like it is

**Comment by LukasReschke** [comment]
11 is done => Let's do the same for 12 again but closing here now.

**Comment by jancborchardt** [comment]
Added the leftovers to https://github.com/nextcloud/server/issues/2672 so they don’t get lost and we actually fix these important papercuts :)
