### ISSUE TITLE
Different settings on password and timeout protection requirements for link shares

### ISSUE THREAD

**Issue by JochenHWezel** [nextcloud/server#24150]
### Use case scenarios identified

These are our main use cases:

1. For website downloads, we sometimes could need a permanent download link for some files in our NextCloud, but it should be available with read-access-only and without a password requirement.

2. When collaborating with external persons, our staff needs most often up- and download and edit rights for those external persons, but as the responsible IT department, we would like to force a password protection on such link shares.

### Feature demand
As IT department, we would like to enforce a general setting for all link shares to
1. be forced to be time limited (so that a user can't share sensitive files with 3rd parties who don't belong any more to our partnership for years)
2. be password protected (so that a link to sensitive files can't be forwarded simply or published openly)
3. but allow exceptions for some special users/groups (e.g. group "Marketing - Website Team"), so that they can share without time limit and without password (in our use case: the website guys who want to create permanent links to shares for embedding them in the website)

### First shot by OwnCloud
The owncloud guys already solved this feature request partially: it's already possible to define password protection requirements by link share type
![image](https://user-images.githubusercontent.com/14078625/99239408-4dc59100-27fb-11eb-96ed-bef2b0647d95.png)

### ToDos

Following ToDos and activities are expected:
- [ ] Implement similar logic like OwnCloud to setup a general policy for password protection requirements for link shares
- [ ] Implement an logic to setup a policy for group objects to 
  - [ ] override the general policy for password protection requirements for link shares
  - [ ] override the general policy for enforcing timeout requirements for link shares, which is defined here:  
![image](https://user-images.githubusercontent.com/14078625/99240034-320eba80-27fc-11eb-841d-f41cbcb75ce0.png)

**Comment by szaimen** [comment]
cc @nextcloud/designers does this make sense and is it feasible?

**Comment by nimisha-vijay** [comment]
Currently Files allows you to create multiple share links for the same file with the optional ability to add a unique password and set different expiration dates for each. This way one file can be access by different people with different password/time privileges. This can be found in the menu next to the share link entry in the right sidebar. 
Is this what you are looking for?

**Comment by jochenwezel** [comment]
> Currently Files allows you to create multiple share links for the same file with the optional ability to add a unique password and set different expiration dates for each. This way one file can be access by different people with different password/time privileges. This can be found in the menu next to the share link entry in the right sidebar.
> Is this what you are looking for?

No, this issue is not targetting the question of creating different link shares.
This issue is targetting policy issues for link shares.

**Comment by jancborchardt** [comment]
What do you think about this @skjnldsv?

The first screenshot says:
- Enforce password for "View only" links
- Enforce password for "View & edit" links
- Enforce password for "View, edit & delete" links
- Enforce password for file drop links

And the second one focuses on "Enforce as latest expiration date".

**Comment by skjnldsv** [comment]
That is too much. We aim for simplicity, the whole settings and sharing is already too complex already. 
Sorry, but we will not go this way in our roadmap.
