### ISSUE TITLE
php8 compatibility

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#26710]
- [x] ``doctrine/dbal``: 3.0.0 https://github.com/doctrine/dbal/releases/tag/3.0.0 https://github.com/nextcloud/3rdparty/pull/581
- [x] ``doctrine/event-manager``: 1.1.1 required https://github.com/nextcloud/3rdparty/pull/576
- [x] ``guzzlehttp/guzzle``: 6.x is not compatible, we need 7.x https://github.com/guzzle/guzzle/pull/2712 https://github.com/guzzle/guzzle/pull/2715 https://github.com/guzzle/guzzle/pull/2789
- [x] ``nikic/php-parser``: https://github.com/nextcloud/3rdparty/pull/559
- [x] ``patchwork/utf8``: ~~needs a fix https://github.com/tchwork/utf8/issues/74~~ replaced with symfony polyfill
- [x] ``php-http/guzzle6-adapter``: "*guzzle 6 does not work with php 8*" https://github.com/php-http/guzzle6-adapter/issues/80#issuecomment-735653801
- [ ] ``php-opencloud/openstack``: https://github.com/php-opencloud/openstack/issues/322 https://github.com/php-opencloud/openstack/pull/323, https://github.com/php-opencloud/openstack/commit/155511170bd1c81e2bcbb8b49ded2a8a7cebdc53 is requires for guzzle7 https://github.com/php-opencloud/openstack/pull/325
- [x] ``pimple/pimple``: 3.3.1 https://github.com/nextcloud/3rdparty/pull/584
- [x] ``psr/http-client``: 1.0.1 https://github.com/nextcloud/3rdparty/pull/526 https://github.com/nextcloud/server/pull/24916
- [x] ``sabre/event``: 5.1.1 https://github.com/nextcloud/3rdparty/pull/577
- [x] ``sabre/dav``: 4.1.2 https://github.com/nextcloud/3rdparty/pull/577
- [x] ``sabre/http``: 5.1.1 https://github.com/nextcloud/3rdparty/pull/577
- [x] ``sabre/uri``: 2.2.1 https://github.com/nextcloud/3rdparty/pull/577
- [x] ``sabre/vobject``: 4.3.2 https://github.com/nextcloud/3rdparty/pull/577
- [x] ``sabre/xml``: 2.2.2 https://github.com/nextcloud/3rdparty/pull/577
- [x] ``scssphp/scssphp``: anything after 1.0.4 should satisfy php8 https://github.com/nextcloud/3rdparty/pull/574 https://github.com/nextcloud/server/pull/24910
- [x] ``symfony/event-dispatcher-contracts``: fixed with [1.1.9](https://github.com/symfony/contracts/blob/master/CHANGELOG.md#119)/[2.1.3](https://github.com/symfony/contracts/blob/master/CHANGELOG.md#213) https://github.com/nextcloud/3rdparty/pull/569
- [x] ``symfony/event-dispatcher`` needs an update of ``symfony/event-dispatcher-contracts`` https://github.com/nextcloud/3rdparty/pull/569
- [x] ``swiftmailer/swiftmailer``: https://github.com/nextcloud/3rdparty/pull/567
- [x] ``web-auth/webauthn-lib``: v3.3 ~~(unreleased)~~ https://github.com/nextcloud/3rdparty/pull/594

**Comment by J0WI** [comment]
Related to https://github.com/nextcloud/server/issues/25806

**Comment by ChristophWurst** [comment]
Once https://github.com/nextcloud/3rdparty/pull/684 is in we can close this ticket

**Comment by janilowski** [comment]
https://github.com/nextcloud/3rdparty/pull/710

> Once [nextcloud/3rdparty#684](https://github.com/nextcloud/3rdparty/pull/684) is in we can close this ticket

https://github.com/nextcloud/3rdparty/pull/710
