### ISSUE TITLE
Nextcloud 12 overview

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2672]
## Current short list 2017-01-24
- [x] Lookup Server++ @schiessle (WIP: https://github.com/nextcloud/server/pull/3869)
- [x] Contacts Dropdown - @ChristophWurst https://github.com/nextcloud/server/pull/3233, @georgehrke https://github.com/nextcloud/server/issues/207#issuecomment-289410262
- [x] Push Notifications - @nickvergessen #3417 & https://github.com/nextcloud/notifications/pull/59
- [x] Federated Activities - @nickvergessen 
- [x] User Migration - @icewind1991 https://github.com/icewind1991/migration
- [x] Sharepoint 2013 - @blizzz #4106
- [x] Spreed++ - @Ivansss 
- [x] Make public links writable - @schiessle  (pr: https://github.com/nextcloud/server/pull/3231)
- [x] Unbundle apps - @LukasReschke 
- [x] App bundles - @LukasReschke  / @jancborchardt https://github.com/nextcloud/server/pull/4454
- [x] Signed upgrades - @LukasReschke 
- [x] Additional security hardenings - @LukasReschke 
- [x] Improved selection highlighting - @icewind1991 
- [x] Add new authentication flow - @LukasReschke @rullzer  (pr: https://github.com/nextcloud/server/pull/4479) 
- [x] (Social) Media Sharing - @rullzer
- [ ] ~~Comments user autocompletion - @blizzz https://github.com/nextcloud/server/issues/2443~~ (moved to 13)

### Optional

- [ ] ~~Federated Spreed calls https://github.com/nextcloud/spreed/issues/21 - @nickvergessen~~ (moved)
- [ ] ~~Pending Shares #2192 - @schiessle / @rullzer~~ (moved to 13) 
- [ ] ~~Introduce timeline https://github.com/nextcloud/server/issues/658 @icewind1991~~ (moved to 13)
- [ ] ~~Personal page sections / merge admin and personal - @blizzz~~
- [ ] ~~Inline image endpoint - @LukasReschke https://github.com/nextcloud/server/issues/2523~~ (moved to 13)

### Open Tasks/Ideas (take one if you want or add your own feature)

- [ ] ~~Undo delete (files, users, contacts etc) **PR:** #1610 closed, issue at https://github.com/nextcloud/server/issues/3216~~ (moved)
- [ ] ~~Signature panel ("I have seen it") #1213~~ (moved to 13)
- [ ] Send notification after upgrade - ?
- [ ] Sharing function & sidebar in detail view of other apps (image viewer, text editor etc) - ?

# Open Tasks from the Nextcloud 11 release

Picking this tasks up is highly appreciated.

## Not finished - delayed to 12

- [x] Opt-In LDAP password expiry handling (@GitHubUser4234) **PR:** #1023 review by @blizzz 
- [x] »All apps« category in apps management #126 
- [x] ~Investigate making it possible to directly link to files which have been re-encoded (such as images) @LukasReschke https://github.com/nextcloud/server/issues/2523#issuecomment-265166327 – _lots_ of people request this => dupe of "Inline image endpoint")~
- [x] app store - ratings (official, supported, ...) how to differentiate (@lukasreschke @jospoortvliet)
- [ ] ~~Skip version upgrades (@lukasreschke @morrisjobke) #2270~~ (moved to 13)
- [ ] ~~Introduce »Updates« navigation section for Apps mgmt instead of confusing notification #838~~ (moved to 13)
- [ ] ~~in the federation section show suggestions for trusted servers based on received/send shares sorted by usage stats~~ (moved to separate ticket #4844)
- [x] documentation:
   - [x] CLI updater & general updater overhaul (@morrisjobke) https://github.com/nextcloud/documentation/pull/460

## Small release review polishing (leftovers from #2134 & #735)

- [x] external sites admin settings: remove PNG, show default icon next to button, Rename drop down to "Change different icon"
- [x] admin settings:
  - [x] condense updater texts
  - [ ] ~~make input field of update groups smaller PR: #4828~~ (keep it as it is)
- [x] avatar cropper (@icewind1991):
  - [x] make it bigger
  - [x] remove radio box PR: #4826
- [x] Theming: click on background image should open file chooser too PR: #4829
- [x] files:
  - [ ] ~~favorite - remove spinner on file icon by default (maybe show it when the request takes longer than 1 second – but then definitely do not show it in place of the filetype icon)~~ (moved to separate ticket #4845) 
  - [x] consider improving contrast of sidebar (selected element) - make bold? make text color the themed one?
- [ ] ~~Gallery: move delete & download to name (@jancborchardt @icewind1991) https://github.com/nextcloud/gallery/issues/80~~ (moved)
- [ ] ~~server info:~~ (moved to https://github.com/nextcloud/serverinfo/issues/90)
  - [ ] ~~CPU info - check for 0 - sys_getloadavg~~
  - [ ] ~~number of files might be wrong~~
  - [ ] ~~change "files" to "files in data directory"~~
  - [ ] ~~input field for external URL with copy link~~
- [x] app management:
  - [x] markup for discription
  - [x] user_external needs an update of the supported version (https://github.com/nextcloud/apps/pull/29)
  - [x] no two new lines in app description
  - [ ] show reason why group restriction not possible for that app (moved to https://github.com/nextcloud/server/issues/4864)
- [x] apps:
  - [x] proper descriptions (3 sentences)
  - [x] ~~external sites doesn't work (without page reload)~~ (moved to separate issue https://github.com/nextcloud/external/issues/28)

This is a rough list of topics we want to work on for Nextcloud 12. It lists the topic and a person who want to work on it and manage the tasks that are to be done. This is up to change and the exact specs are not set in stone now. Some of these are tiny, others are huge - we'll create issues to explain and expand on them the coming week.

If anybody is interested to help out for a specific topic just contact the listed person 😃 And of course if you want to work on something different: feel free to do so and add yourself to the list 😄 

Pls be sure to add a issue number of PR link to what you do/did.

**Comment by schiessle** [comment]
I removed "next generation federated sharing" because this was added for 11 like "yeah, webdav mounts need to be faster, that could be better,..." but no real specific task. Features/Improvements planed for a version should be more specific.

**Comment by jancborchardt** [comment]
I also added the small release review polishing items (leftovers from #2134 & #735). We shouldn’t just forget them in the closed issue but already make sure we polish early. :)

**Comment by Spartachetto** [comment]
I wonder if the exclusion from the above list of the leftovers from #1465 is voluntary.

Consider that one of the issues (#2512) should be ready to merge!

**Comment by jancborchardt** [comment]
@Spartachetto https://github.com/nextcloud/server/issues/1465 is scheduled for Nextcloud 12 as you can see from the milestone. :)

**Comment by masteranalyze** [comment]
Any plans to integer amazon cloud drive and one drive microsoft as external storages in the coming next cloud 12?

Alot of things are added witch is very good,but it`s seems to missing very importantly external services providers implementation and implementation with joomla ,wordpress for easily share for example 1000 photos all togheter.

**Comment by AMDG2** [comment]
Is there any plan to improve federated cloud id management ? I suggested an algorithm to avoid id like `john.doe@mydomain.ltd@nextcloud.mydomain.ltd` in issue #782.

**Comment by MorrisJobke** [comment]
@jospoortvliet Something for the release notes: #3151 Maybe add a note that developers should check their app and maybe add a nice looking icon (like in https://github.com/nextcloud/twofactor_u2f/pull/31)

<img width="371" alt="bildschirmfoto 2017-01-24 um 12 51 27" src="https://cloud.githubusercontent.com/assets/245432/22261778/dd7a1e54-e233-11e6-94bb-f47bcca2d854.png">

**Comment by Ramalama2** [comment]
Webdav (file locking) should be fixed...
To get native osx webdav client working.

**Comment by MorrisJobke** [comment]
> Webdav (file locking) should be fixed...
> To get native osx webdav client working.

Fixed by https://github.com/nextcloud/server/pull/1328

**Comment by Ramalama2** [comment]
@MorrisJobke 
No it's not fixed, i have all that fixes already merged.
Native Windows WebDav = Working
Cyberduck = Working
Native OSX Webdav = Cant upload files (Brocken)

Cheers :-)

**Comment by MorrisJobke** [comment]
> @MorrisJobke
> No it's not fixed, i have all that fixes already merged.
> Native Windows WebDav = Working
> Cyberduck = Working
> Native OSX Webdav = Cant upload files (Brocken)
> 
> Cheers :-)

Please open a new ticket.

**Comment by cowai** [comment]
I really hope chunked uploading in the web ui will come in NC12.

**Comment by jones4410** [comment]
it would be nice to have some kind of backup service for nextcloud to automatically push a backup to a remote server (maybe through rsync?)...
maybe for NC13?

**Comment by MorrisJobke** [comment]
@karlitschek I went through all the items in the list above and either moved them in a separate ticket, fixed them or checked if they are fixed.

This list is now completely done. 🙌

**Comment by karlitschek** [comment]
super awesome :-)
