### ISSUE TITLE
Write ocs end-points for occ commands and other admin settings

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2694]
**Edit:** Not completed items are moved to Nextcloud 13: #4904

I would be good to have a OCS API for all our occ and admin settings so that a Nextcloud installation can be administrated from outside.

Here is a list of what we need:

- [x] app:
	- [x] ~check-code~ - makes no sense
	- [x] disable: provisioning_api
	- [x] enable: provisioning_api
	- [x] list: provisioning_api
- [x] background:
	- [x] ~ajax~: config=>system:set
	- [x] ~cron~: config=>system:set
	- [x] ~webcron~: config=>system:set
- [ ] config
	- [x] app:delete: provisioning_api
	- [x] app:get: provisioning_api
	- [x] app:set: provisioning_api
	- [ ] import
	- [ ] list: provisioning_api for apps
	- [ ] system:delete
	- [ ] system:get
	- [ ] system:set
- [x] db:
	- [x] ~convert-type~ - makes no sense
	- [x] ~generate-change-script~ - makes no sense
- [ ] encryption:
	- [ ] change-key-storage-root
	- [x] ~decrypt-all~ - Timeout critical
	- [ ] disable
	- [ ] enable
	- [x] enable-master-key
	- [x] ~encrypt-all~ - Timeout critical
	- [ ] list-modules
	- [ ] migrate
	- [ ] set-default-module
	- [ ] show-key-storage-root
	- [ ] status
- [ ] files
	- [ ] files:cleanup
	- [x] ~files:scan~ - Timeout critical
	- [x] ~files:transfer-ownership~ - Timeout critical
- [ ] integrity:
	- [ ] integrity:check-app
	- [ ] integrity:check-core
	- [x] ~integrity:sign-app~ - makes no sense
	- [x] ~integrity:sign-core~ - makes no sense
- [ ] ldap:
	- [ ] ldap:check-user
	- [x] ldap:create-empty-config → #3162 
	- [x] ldap:delete-config → #3162 
	- [ ] ldap:search
	- [x] ldap:set-config → #3162 
	- [ ] ldap:show-config → #3162 
	- [ ] ldap:show-remnants
	- [ ] ldap:test-config
- [ ] maintenance:
	- [ ] maintenance:mimetype:update-db
	- [ ] maintenance:mimetype:update-js
	- [x] ~maintenance:mode~: config=>system:set
	- [ ] maintenance:repair
	- [x] ~maintenance:singleuser~: config=>system:set
	- [ ] maintenance:update:htaccess
- [ ] user
	- [ ] user:lastseen
	- [ ] user:report
	- [ ] user:resetpassword
- [ ] versions
	- [ ]  versions:cleanup
- [x] sharing
	- [x]  set default expire date and other sharing settings: provisioning_api

Beginning with Nextcloud 11 we can probably set most of them already with `ocs/v2.php/apps/provisioning_api/api/v1/config/apps/{app}/{key}` by sending GET, POST and DELETE requests

Please double check for your apps @nickvergessen @blizzz @rullzer @icewind1991 @LukasReschke

**Comment by nickvergessen** [comment]
I added some information and killed some that just make no sense.

**Comment by jancborchardt** [comment]
To relay what we talked about via private mail: It would be cool to rename the command from the very technical (and outdated) `occ` to `nextcloud` or if that causes name conflicts, `nextcloud-cli` or so. (Ideally a less technical word than `cli` too …

**Comment by blizzz** [comment]
With regard to the LDAP part, do I understand correctly that the OCS spec needs to be extended? Since the only fitting service is CONFIG, but only a GET method is specified.

**Comment by nickvergessen** [comment]
> Beginning with Nextcloud 11 we can probably set most of them already with `ocs/v2.php/apps/provisioning_api/api/v1/config/apps/{app}/{key}` by sending GET, POST and DELETE requests

Post is also fine, so should be okay I think?

**Comment by blizzz** [comment]
Only GET is specified (1.7 draft, but same in 1.6)

![spectacle w17738](https://cloud.githubusercontent.com/assets/2184312/21984443/3864637c-dbf6-11e6-8e0f-ae78f0089fe1.png)

**Comment by nickvergessen** [comment]
That's a different endpoint...

**Comment by blizzz** [comment]
Ok, meanhwhile I figured out the doc at opendesktop.org is abandoned, in favor https://lukasreschke.github.io/OpenCloudMeshSpecification, while this is not complete either. Which isn't acutally good, but eases things…

**Comment by MorrisJobke** [comment]
I created a new ticket for 13 for the not yet implemented end points: #4904
