### ISSUE TITLE
Personal Info Settings Vuetified [Meta]

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#27869]
Personal Info Settings rewritten in Vue

- [x] https://github.com/nextcloud/server/pull/28028
- [x] https://github.com/nextcloud/server/pull/27379
- [x] https://github.com/nextcloud/server/pull/28423
- [x] https://github.com/nextcloud/server/pull/33206
- [x] https://github.com/nextcloud/server/pull/33217
- [x] https://github.com/nextcloud/server/pull/33285
- [x] https://github.com/nextcloud/server/pull/33310
- [x] https://github.com/nextcloud/server/pull/33311
- [x] https://github.com/nextcloud/server/pull/33409
- [x] https://github.com/nextcloud/server/pull/33502
- [x] https://github.com/nextcloud/server/pull/33512
- ~Deprecate and cleanup legacy templating, styles, et cetera~

<details>
<summary>Other</summary>

- (No textarea) ~Use component introduced in https://github.com/nextcloud/nextcloud-vue/pull/2868~

</details>

**Comment by tcitworld** [comment]
Part of https://github.com/nextcloud/server/issues/12906

**Comment by Pytal** [comment]
> moving to 26, for it seems to me not all is done, yet?

All done actually, other non-Vuetifying changes to be handled separately
