### ISSUE TITLE
User Profile [Meta]

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#28139]
<details>
<summary>Completed</summary>

### Base
- [x] https://github.com/nextcloud/server/pull/28751

#### References
- Profile page ideation [https://github.com/nextcloud-gmbh/server/issues/33](https://github.com/nextcloud-gmbh/server/issues/33)
- Penpot Mockups [https://design.penpot.app/#/dashboard/team/aba21030-65ab-11eb-bbda-03f8ac143bbf/projects/7d7bb720-a2cc-11eb-bb49-81aaa3a367f9](https://design.penpot.app/#/dashboard/team/aba21030-65ab-11eb-bbda-03f8ac143bbf/projects/7d7bb720-a2cc-11eb-bb49-81aaa3a367f9)

### Privacy
  - [x] https://github.com/nextcloud/server/pull/29559
  - [x] https://github.com/nextcloud/server/pull/29869
 
### Design / Frontend
  - [x] https://github.com/nextcloud/server/pull/29482
    - [x] https://github.com/nextcloud/spreed/pull/6437
  - [x] https://github.com/nextcloud/server/pull/29833
  - [x] https://github.com/nextcloud/server/pull/29872
  - [x] https://github.com/nextcloud/server/pull/29893

---

</details>

## Issues
- [x] https://github.com/nextcloud/server/issues/30864
- [ ] https://github.com/nextcloud/server/issues/30865
- [x] https://github.com/nextcloud/server/issues/30866
- [x] https://github.com/nextcloud/server/issues/30867
- [ ] https://github.com/nextcloud/server/issues/30868
- [x] https://github.com/nextcloud/server/issues/30869
- [ ] https://github.com/nextcloud/server/issues/30870
- [ ] https://github.com/nextcloud/server/issues/30871

## Miscellaneous
  - [x] https://github.com/nextcloud/documentation/issues/7797
  - [ ] Tests
  - [ ] Set order of profile actions
  - Provide additional emails as actions
    - Prerequisites:
      - [ ] Preserve order and scope of additional emails, the logic for handling this is a prerequisite as visibility must also be preserved https://github.com/nextcloud/server/issues/26866#issue-874793291

**Comment by jancborchardt** [comment]
So here’s the mockups @nimisha-vijay and I worked on. :)
You can also find them on [our Penpot org](https://design.penpot.app/#/workspace/7d7bb720-a2cc-11eb-bb49-81aaa3a367f9/3e819810-661c-11eb-bbda-03f8ac143bbf?page-id=3e819811-661c-11eb-bbda-03f8ac143bbf) if you have access.

## Personal settings
Has a nice redirect / marketing about the new profile feature, directly showing the hovercard:

![Personal settings](https://user-images.githubusercontent.com/925062/130597500-b23089f0-1e73-4a5f-9f85-13aa6af829b1.png)

## Profile
Possible sections:
- Description / Bio
- You & this person: Events, calls, mails, Talk messages, etc.
- Photos in a nice grid view
- Shared resources: Files, folders, file drop, forms, public deck board, etc.
- (Posts from Social are smth for the dreamworld future ;)

![Profile](https://user-images.githubusercontent.com/925062/130597501-2d835145-03f4-43e3-a214-052991cfcfe4.png)

## Empty content
Viewing another person’s profile which is rather empty, we could move the "You & this person" section to the content since otherwise the content will be a bit unbalanced:

![Profile-empty-1](https://user-images.githubusercontent.com/925062/130597496-255db5bc-512d-4b0a-9954-3e7e9f40f866.png)

**Comment by tobiasKaminsky** [comment]
Whoever is working on this, please let us talk about proper API for clients.

**Comment by Salvador1313** [comment]
Я всегда за конструктивный диалог.

пн, 30 авг. 2021 г., 09:43 Tobias Kaminsky ***@***.***>:

**Comment by Spartachetto** [comment]
When reading this issue and looking at the images I remembered the proposal of #2143.

The aim of that old issue is different (synthetic informations about tags and not about users), yet maybe rereading it while working at this issue could provide some useful suggestions for an extension of this functionality.

Hope that helps!

**Comment by Pytal** [comment]
> Whoever is working on this, please let us talk about proper API for clients.

Definitely, what do you have in mind? Do we have a similar API used by clients that may be used as reference?

**Comment by Pytal** [comment]
> Whoever is working on this, please let us talk about proper API for clients.

For sure! what do you have in mind? Do we have a similar API used by clients that may be used as reference?

**Comment by ChristophWurst** [comment]
> Makes you approachable and shows Nextcloud ecosystem: Book an appointment, Talk to person

How will we do this? Groupware will take care of the appointments integration. Can we register to render arbitrary content on the profile page like we do on the dashboard? As in, Nextcloud server doesn't have any ties on how Calendar or the appointments feature works, but rather Calendar renders a small component on the profile page that renders the appointments button/widget?

**Comment by ChristophWurst** [comment]
Thanks. From that code I get that one can only provide *links*, right? Will we also support running and rendering arbitrary content on the page? Like will the Calendar app be able to load a little widget that, depending on the appointments configurations of the user, renders a button, more than one or none?
