### ISSUE TITLE
Settings Apps Redesign Overview

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#3194]
So, I want to use this issue as an overview for the various todos and steps in making the apps settings more user friendly, appealing and integrated with the appstore.
Discussion and todos are from #2533 and the 12 overview #2672 .

#### Todo
- [x] Make the installed (enable/disabled) apps a table PR: #3195 
    - [ ] Introduce proper sorting in table view
- [x] Introduce an "All installed" category PR: #3195 
- [x] Introduce an "All apps" category #126 
- [x] Introduce »Updates« category #838
- [x] Redesign the appstore categories overview with bigger screenshots, etc.
- [x] Rewrite settings.css --> settings.scss #6372 
- [x] Add icons to the menu entries #3987 + #6627 

#### To discuss
- [x] Link to the appstore details page
- [ ] OR Introduce a details page (pop-up) for each app #3193 
- [ ] OR Show app details in a right sidebar #2138
- [ ] Make it possible to uninstall enabled apps (trigger disable and then uninstall)
- [ ] Make categories enabled/disabled/update filters, to reduce request

The Server and Client Controller might have to be rewritten ( 🍝 ), but I wanted to introduce changes step by step...

**Comment by skjnldsv** [comment]
> Introduce »Updates« category
😍

**Comment by ChristophWurst** [comment]
How about a visual separation between the meta categories (installed, enabled, disabled) and the categories from the app store (like authentication and the like) with either some whitespace or a horizontal line?

**Comment by schiessle** [comment]
> Introduce a details page (pop-up) for each app #3193

To show app details we also had the idea of using a side bar, similiar to what we have for files, see https://github.com/nextcloud/server/issues/2138

**Comment by eppfel** [comment]
> How about a visual separation between the meta categories (installed, enabled, disabled) and the categories from the app store (like authentication and the like) with either some whitespace or a horizontal line?

Already planned. :wink: From: https://github.com/nextcloud/server/pull/2533#issuecomment-267641134
>Make a more clear separation between enabled/disabled apps and the actual store categories.

I could add it in #3195 , if we are positive on this.

**Comment by schiessle** [comment]
Something also to consider. It is really hard to search for a app because of all the categories. Two ideas:

- Either the search on the top should search all apps,not just the current category
- Or introduce a new "category" called "all apps"

**Comment by eppfel** [comment]
@schiessle "All apps" already planned, see OP.

Searching all apps per default could also work, because you know what you are searching for, so typing a few more characters until you filter the list down enough could be ok, even with a large amount of apps in store.

**Comment by eppfel** [comment]
From discussion #3195 and here #126:

We have to decide how to structure the apps management.

This is what I thought it is going to be:
<img width="502" alt="bildschirmfoto 2017-01-23 um 18 14 09" src="https://cloud.githubusercontent.com/assets/1899308/22214756/3347bd1e-e199-11e6-8eca-3faea5164200.png">

---

But we could also, drop `enabled` and `disabled` IMO and combine all apps:

* All Apps (all the app store has + custom ones you installed)
* Installed
* Updates
* Store Category 1
* Store Category N

But then it would be weird to have two different layouts for that. I really feel there are two separate scenarios. Managing apps vs. getting new ones (see my explanation in https://github.com/nextcloud/server/pull/3195#issuecomment-274444219).

---

I could even think about redirecting to the store in the fashion of "Get more apps".
* All installed
* Updates
* Get more apps (external)

The link could send the Nextcloud installations endpoint via GET and when you click install in the store you are redirected to your Nextcloud and the app is installed. That way we do not have to build a nice looking appstore and a nice looking apps management.

---

My final call would be:

#### Installed
- All installed
- Updates

#### App store
- All available
- category 1
- category …
- category n

Any other ideas?

**Comment by skjnldsv** [comment]
I really like it! :D 
Maybe adding a counter in the app-navigation?

**Comment by jancborchardt** [comment]
We got a lot done! Moving the rest to Nextcloud 13 :)

**Comment by skjnldsv** [comment]
Apps settings icons > #6627

**Comment by Hanzei** [comment]
Updates category --> #6739

**Comment by jancborchardt** [comment]
Most of this is actually fixed and implemented, right @eppfel? The only major thing seems to be the addition of the #app-sidebar to the right with some additional app info.

I would close this overview issue as fixed, as it doesn't need that big of an overview anymore. ;) We always have the label "feature: apps".

**Comment by MorrisJobke** [comment]
Many things were fixed with #9565
