### ISSUE TITLE
[Meta]: Port away from ILogger

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/server#32127]
## Current pull requests
 - [x] https://github.com/nextcloud/server/pull/31609
 - [x] https://github.com/nextcloud/server/pull/31943
 - [x] https://github.com/nextcloud/server/pull/31948
 - [x] https://github.com/nextcloud/server/pull/40508
 - [ ] ...

## Current remaining modules to port in server
 - [x] lib/{private,public}/Files 

## Current remaining shipped app to port
 - [x] federation https://github.com/nextcloud/server/pull/39018
 - [x] encryption https://github.com/nextcloud/server/pull/39065
 - [x] federatedfilesharing #39160 
 - [x] files_sharing https://github.com/nextcloud/server/pull/39169
 - [ ] files_trashbin
 - [x] files_external https://github.com/nextcloud/server/pull/39480
 - [ ] dav
 - [x] weather_status
 - [ ] settings
 - [x] files
 - [ ] workflowengine
 - [x] user_status
 - [x] user_ldap https://github.com/nextcloud/server/pull/40504
 - [x] updatenotification
 - [x] twofactor_backupcodes
 - [x] theming
 - [x] sharebymail

## Current issues

- The background job interface exposes `ILogger` in its public API. We need to deprecate this
- In some places, like the updater. It's helpful to be able to write `ILogger:DEBUG` instead of `2`. We need to look if upstream psr would be interested to add enums for the log levels.

**Comment by come-nc** [comment]
- [ ] https://github.com/nextcloud/server/pull/31775

**Comment by come-nc** [comment]
- [ ] https://github.com/nextcloud/server/pull/31752

**Comment by Altahrim** [comment]
- [ ] #39160

**Comment by Altahrim** [comment]
- [ ] #39169

**Comment by joshtrichards** [comment]
All that's left I think is to remove these deprecated references in the `\OCP\BackgroundJob` interfaces I think:

https://github.com/nextcloud/server/blob/1518ded8b193ca789b28f8f64114798ab8df1747/lib/public/BackgroundJob/Job.php#L42-L46](https://github.com/search?q=repo%3Anextcloud%2Fserver%20path%3A%2F%5Elib%5C%2Fpublic%5C%2FBackgroundJob%5C%2F%2F%20Ilogger&type=code)

**Comment by come-nc** [comment]
See https://github.com/nextcloud/server/pull/48197 , it will be for Nextcloud 33 because of API stability rules.
