### ISSUE TITLE
[Meta]: Remove appinfo/app.php

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/server#32132]
Current task:

- [x] files_sharing - #23046
- [x] encryption - #46136
- [x] user_saml - nextcloud/user_saml#538
- [x] suspicious_login - nextcloud/suspicious_login#499
- [x] officeonline - nextcloud/officeonline#353
- [ ] stop checking for the file existence once the critical apps have been migrated

Misc apps:

- [ ] cms_pico - nextcloud/cms_pico#230
- [x] jsloader - nextcloud/jsloader#34

**Comment by szaimen** [comment]
is files_sharing still not solved? I thought it was?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/tree/master/apps/files_sharing/appinfo
It is, lemme close that ticket

**Comment by ChristophWurst** [comment]
https://github.com/search?q=org%3Anextcloud+%22app.php%22+in%3Apath+path%3A%22appinfo%22&type=code :crying_cat_face:

**Comment by nickvergessen** [comment]
Checking the info.xmls on those, only 3 apps of those are still developed:
* user_saml
* jsloader
* suspicious_login

So ready to 🔥

**Comment by andyxheli** [comment]
Might want to also include this https://github.com/nextcloud/officeonline/issues/353

**Comment by masterwishx** [comment]
encryption/appinfo/app.php having same issue for this

![image](https://github.com/nextcloud/server/assets/28630321/dd6e846c-9926-416a-8b71-711574b18534)

**Comment by SjoerdV** [comment]
@CarlSchwan, I understand this is an issue that is taking some time to sort out.
In the meantime could the 'flooding of the log' be prevented for this issue? 

When on `'loglevel' => 0` in `config/config.php` the 'user_saml' component is sending the same message 15 times a second:
`/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.`

I hope it's possible, thanks.

**Comment by joshtrichards** [comment]
@SjoerdV You can accomplish that yourself by turning off debug level logging. Set your loglevel to something more reasonable like 2. :)

**Comment by SjoerdV** [comment]
> @SjoerdV You can accomplish that yourself by turning off debug level logging. Set your loglevel to something more reasonable like 2. :)

Yes, well thanks, but I was actually debugging other issues, so a constant flow of this particular message is not really helpful in that case.
I was hoping it would be possible to throttle or limit logging for this specific app. ;-)

**Comment by nickvergessen** [comment]
> I was hoping it would be possible to throttle or limit logging for this specific app. ;-)

You can do it the other way around, leave the log level on warning and add the log condition for your app (then it logs debug for your app)

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level-interaction

**Comment by SjoerdV** [comment]
> > I was hoping it would be possible to throttle or limit logging for this specific app. ;-)
> 
> You can do it the other way around, leave the log level on warning and add the log condition for your app (then it logs debug for your app)
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level-interaction

Thanks very much, That's great and will work just fine. Excellent!

**Comment by joshtrichards** [comment]
Encryption handled in  #46136

**Comment by joshtrichards** [comment]
Closing since only remaining ones here are:

- cms_pico (not really maintained any longer and in any case not a shipped app; has its own tracker for the matter)
- jsloader (not really maintained any longer and in any case not a shipped app; has its own tracker for the matter)
- user_saml (not a shipped app; has its own tracker for the matter)

**Comment by ChristophWurst** [comment]
I believe we had this tracking issue so that server can stop checking for the file existence once the critical apps have been migrated.

From the list above I'd say the last critical migration is user_saml.
