### ISSUE TITLE
[Meta]: Get rid of at() matcher in phpunit tests

### ISSUE THREAD

**Issue by come-nc** [nextcloud/server#32316]
See https://github.com/sebastianbergmann/phpunit/issues/4297

- [x] apps/dav - 116 
  - Most of it - https://github.com/nextcloud/server/pull/36026
  - Last one - https://github.com/nextcloud/server/pull/40424
- [x] apps/encryption - 15 - https://github.com/nextcloud/server/pull/32567
- [x] apps/federatedfilesharing - 1 - https://github.com/nextcloud/server/pull/32570
- [x] apps/files - 6 - https://github.com/nextcloud/server/pull/32571
- [x] apps/files_sharing - 17 - https://github.com/nextcloud/server/pull/32577
- [x] apps/notifications - 2 - https://github.com/nextcloud/notifications/pull/1240
- [x] apps/oauth2 - 1 - https://github.com/nextcloud/server/pull/33435
- [x] apps/provisioning_api - 6 - https://github.com/nextcloud/server/pull/32799
- [x] apps/settings - 18 - https://github.com/nextcloud/server/pull/32737
- [x] apps/theming - 49 - https://github.com/nextcloud/server/pull/32900
- [x] apps/updatenotification - 1
- [x] apps/user_ldap - 36 - https://github.com/nextcloud/server/pull/32861
- [x] tests/Core - 39
   - First part -  https://github.com/nextcloud/server/pull/32572
   - Last one - https://github.com/nextcloud/server/pull/40420
- [x] tests/Test - 7 - https://github.com/nextcloud/server/pull/33435
- [x] tests/lib - 196 
  - First part - https://github.com/nextcloud/server/pull/32901
  - Second part - https://github.com/nextcloud/server/pull/33732
  - Last one - https://github.com/nextcloud/server/pull/40419

**Comment by joshtrichards** [comment]
Still open due to this TODO item: https://github.com/nextcloud/server/pull/32577#issue-1246551065

https://github.com/nextcloud/server/blob/7362ede426becc20e0f2285b72b8e5fec3edfb70/apps/files_sharing/tests/External/ManagerTest.php#L257

**Comment by nickvergessen** [comment]
Solved by now as we use PHPUnit 10
