### ISSUE TITLE
[Bug]: Upload from android client

### ISSUE THREAD

**Issue by pledou** [nextcloud/server#33002]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A lot of file I want to push dont work. The problem started 3 days ago with upgrade to 24.0.1

### Steps to reproduce

1. start upload pictures from android client
2. Failed with unknown error

### Expected behavior

No error 

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "config_is_read_only": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "leducd.duckdns.org",
            "nginx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "24.0.2.1",
        "dbtype": "pgsql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "fr",
        "default_locale": "fr",
        "default_phone_region": "FR",
        "defaultapp": "dashboard,files",
        "knowledgebaseenabled": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auto_logout": false,
        "token_auth_enforced": false,
        "auth.bruteforce.protection.enabled": true,
        "auth.webauthn.enabled": true,
        "hide_login_form": false,
        "skeletondirectory": "core\/skeleton",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": "true",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "overwrite.cli.url": "https:\/\/leducd.duckdns.org",
        "trashbin_retention_obligation": "auto,7",
        "updater.release.channel": "stable",
        "loglevel": 1,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "theme": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "app_install_overwrite": [
            "files_fulltextsearch_tesseract",
            "ocsms",
            "keeweb",
            "social",
            "backup"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - backup: 1.0.6
  - bruteforcesettings: 2.4.0
  - calendar: 3.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.1
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_fulltextsearch: 24.0.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.5
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - ocsms: 2.2.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - registration: 1.5.0
  - richdocuments: 6.1.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.2
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - encryption: 2.12.0
  - firstrunwizard: 2.9.0
  - nextcloud_announcements: 1.13.0
  - privacy: 1.8.0
  - support: 1.4.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"IiosGJeQu5TuFaRgYD2S","level":4,"time":"2022-06-23T21:08:20+00:00","remoteAddr":"192.168.1.109","user":"v.leduc","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/v.leduc/f2adecdf166c18a2c169cd0bea21ede9/0000000000000000-0000000001175253","message":"OC\\DB\\QueryBuilder\\QueryBuilder::__construct(): Argument #3 ($logger) must be of type Psr\\Log\\LoggerInterface, OC\\Log given, called in /var/www/html/apps/fulltextsearch/vendor/artificial-owl/my-small-php-tools/lib/Db/Nextcloud/nc23/NC23ExtendedQueryBuilder.php on line 74","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.20.3","version":"24.0.2.1","exception":{"Exception":"TypeError","Message":"OC\\DB\\QueryBuilder\\QueryBuilder::__construct(): Argument #3 ($logger) must be of type Psr\\Log\\LoggerInterface, OC\\Log given, called in /var/www/html/apps/fulltextsearch/vendor/artificial-owl/my-small-php-tools/lib/Db/Nextcloud/nc23/NC23ExtendedQueryBuilder.php on line 74","Code":0,"Trace":[{"file":"/var/www/html/apps/fulltextsearch/vendor/artificial-owl/my-small-php-tools/lib/Db/Nextcloud/nc23/NC23ExtendedQueryBuilder.php","line":74,"function":"__construct","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[{"__class__":"OC\\DB\\ConnectionAdapter"},{"__class__":"OC\\SystemConfig"},{"__class__":"OC\\Log"}]},{"file":"/var/www/html/apps/backup/lib/Db/CoreQueryBuilder.php","line":48,"function":"__construct","class":"ArtificialOwl\\MySmallPhpTools\\Db\\Nextcloud\\nc23\\NC23ExtendedQueryBuilder","type":"->","args":[]},{"file":"/var/www/html/apps/backup/lib/Db/CoreRequestBuilder.php","line":124,"function":"__construct","class":"OCA\\Backup\\Db\\CoreQueryBuilder","type":"->","args":[]},{"file":"/var/www/html/apps/backup/lib/Db/ChangesRequestBuilder.php","line":75,"function":"getQueryBuilder","class":"OCA\\Backup\\Db\\CoreRequestBuilder","type":"->","args":[]},{"file":"/var/www/html/apps/backup/lib/Db/ChangesRequest.php","line":69,"function":"getChangesSelectSql","class":"OCA\\Backup\\Db\\ChangesRequestBuilder","type":"->","args":[]},{"file":"/var/www/html/apps/backup/lib/Db/ChangesRequest.php","line":81,"function":"getByHash","class":"OCA\\Backup\\Db\\ChangesRequest","type":"->","args":["e48bc898af117241e4caf06e574cdfe1"]},{"file":"/var/www/html/apps/backup/lib/Service/FilesService.php","line":215,"function":"insertIfNotFound","class":"OCA\\Backup\\Db\\ChangesRequest","type":"->","args":[{"__class__":"OCA\\Backup\\Model\\ChangedFile"}]},{"file":"/var/www/html/apps/backup/lib/Listeners/NodeEvent.php","line":107,"function":"changedFile","class":"OCA\\Backup\\Service\\FilesService","type":"->","args":[{"__class__":"OCA\\Backup\\Model\\ChangedFile"}]},{"file":"/var/www/html/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OCA\\Backup\\Listeners\\NodeEvent","type":"->","args":[{"__class__":"OCP\\Files\\Events\\Node\\NodeCreatedEvent"}]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCP\\Files\\Events\\Node\\NodeCreatedEvent"},"OCP\\Files\\Events\\Node\\NodeCreatedEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"OCP\\Files\\Events\\Node\\NodeCreatedEvent",{"__class__":"OCP\\Files\\Events\\Node\\NodeCreatedEvent"}]},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\Files\\Events\\Node\\NodeCreatedEvent"},"OCP\\Files\\Events\\Node\\NodeCreatedEvent"]},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Files\\Events\\Node\\NodeCreatedEvent",{"__class__":"OCP\\Files\\Events\\Node\\NodeCreatedEvent"}]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":136,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\Files\\Events\\Node\\NodeCreatedEvent"}]},{"file":"/var/www/html/lib/private/legacy/OC_Hook.php","line":106,"function":"postCreate","class":"OC\\Files\\Node\\HookConnector","type":"->","args":[[null]]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":464,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","post_create",[null]]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":399,"function":"emitPostHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[false]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":164,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/html/apps/dav/lib/Upload/UploadFolder.php","line":45,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["0000000000000000-0000000001175253",null]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["0000000000000000-0000000001175253",null]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/v.leduc/f2adecdf166c18a2c169cd0bea21ede9/0000000000000000-0000000001175253",null,null]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":352,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":166,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","Line":86,"CustomMessage":"--"},"id":"62b4d6d388931"}
```

### Additional info

Some customisation on fpm image:

FROM nextcloud:fpm
#TODO nextcloud:stable-fpm  

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        libmagickcore-6.q16-6-extra \
        procps \
#        smbclient \
        supervisor \
#       libreoffice \
        nginx \
        imagemagick\
        ghostscript\
    ; \
    rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    \
    savedAptMark="$(apt-mark showmanual)"; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libbz2-dev \
#        libc-client-dev \
#        libkrb5-dev \
#        libsmbclient-dev \
    ; \
    \
#    docker-php-ext-configure imap --with-kerberos --with-imap-ssl; \
    docker-php-ext-install \
        bz2 \
#        imap \
    ; \
#    pecl install smbclient; \
#    docker-php-ext-enable smbclient; \
    \
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
    apt-mark auto '.*' > /dev/null; \
    apt-mark manual $savedAptMark; \
    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
        | awk '/=>/ { print $3 }' \
        | sort -u \
        | xargs -r dpkg-query -S \
        | cut -d: -f1 \
        | sort -u \
        | xargs -rt apt-mark manual; \
    \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p \
    /var/log/supervisord \
    /var/run/supervisord \
;

COPY supervisord.conf /

ENV NEXTCLOUD_UPDATE=1

# Autoriser les aperçus de PDF par ImageMagick
RUN sed -i 's/\(^ *<policy.*rights="\)\([^"]*\)\(".*PDF.*\/>\)/\1read|write\3/1' /etc/ImageMagick-6/policy.xml

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
