### ISSUE TITLE
Own background image conflicts with admin theming primary color

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#33925]
### Problem
With the design update, you can have the strange state that the primary color picked by the admin is still present when you pick a different background image, resulting in e.g. red primary buttons when there is a green-ish background image.

@skjnldsv since we also talked about that in https://github.com/nextcloud/server/issues/33810#issuecomment-1238039878

### Possible solution

**For users**
People should be able to set their own design, background image including primary color. For that we can do several enhancements, any or all of these:
- [ ] Ideally the primary color is sourced automatically from the image, e.g. via https://www.the-art-of-web.com/php/extract-image-color/ or https://stackoverflow.com/questions/10290259/detect-main-colors-in-an-image-with-php => https://github.com/nextcloud/server/issues/34560
- [ ] Optionally people could set this in the settings via a color picker, but this needs manual work. Ref settings PR by @GretaD @Pytal at https://github.com/nextcloud/server/pull/33733 (If we have the automatic color sourcing from the image, ideally we do not need this) => (Custom plain background color) https://github.com/nextcloud/server/pull/34437 => https://github.com/nextcloud/server/issues/34560#issuecomment-1277552105
- [x] The default backgrounds can also have default primary colors associated with them (see list below): https://github.com/nextcloud/server/pull/34298

**For admins**
- [x] Ideally, the admin should be able to disable this account-specific customization completely, if they would like to keep their cloud on-brand. This would be a setting in "Theming" called "Allow people to personalize their background and color". By default, the customization is enabled of course. => https://github.com/nextcloud/server/issues/34561

**Default**
The default image and color if nothing is customized by either admin or individual people remains:
- background (for logged in as well as logged out pages): kamil-porembinski-clouds.jpg
- color: Nextcloud blue `#0082c9`

cc @PVince81 @skjnldsv @karlitschek @AndyScherzinger

---

List of colors for default dashboard images (taken by putting the images through the [Material Theme Builder](https://m3.material.io/theme-builder#/dynamic)):
- `#a53c17` anatoly-mikhaltsov-butterfly-wing-scale.jpg
- `#316b26` bernard-spragg-new-zealand-fern.jpg
- `#56633d` bernie-cetonia-aurata-take-off-composition.jpg
- `#9c4236` dejan-krsmanovic-ribbed-red-metal.jpg
- `#4f6071` eduardo-neves-pedra-azul.jpg
- `#396475` european-space-agency-barents-bloom.jpg
- `#98415a` hannes-fritz-flippity-floppity.jpg
- `#845334` hannes-fritz-roulette.jpg
- `#4f6071` hannes-fritz-sea-spray.jpg
- `#0082c9` kamil-porembinski-clouds.jpg (the actual accessible color here would be `#00639a`)
- `#7f5700` lali-masriera-yellow-bricks.jpg
- `#005ac1` nasa-waxing-crescent-moon.jpg
- `#7b4e7e` rawpixel-pink-tapioca-bubbles.jpg
- `#6a2af4` tommy-chau-already.jpg
- `#7f4f70` tommy-chau-lion-rock-hill.jpg

**Comment by Pytal** [comment]
As a user this would be much simpler and less of a footgun by not having a custom color picker and instead just picking the background which automatically chooses the primary color resulting in a background and color combination that never conflict, what do you think @jancborchardt?

Color presets added in https://github.com/nextcloud/server/pull/34272

**Comment by szaimen** [comment]
> As a user this would be much simpler and less of a footgun by not having a custom color picker and instead just picking the background which automatically chooses the primary color resulting in a background and color combination that never conflict, what do you think @jancborchardt?
> 
> Color presets added in #34272

Makes sense! But what abour custom backgrounds?

**Comment by szaimen** [comment]
ping @jancborchardt

**Comment by jancborchardt** [comment]
Yes, the default presets for the default backgrounds are good, thanks @Pytal! :)

As mentioned in the post, it would still be great if a color picker shows up when you load a custom image (does not need to show for the default pictures as the colors are good).

And in the future, we can get the color automatically from custom images too – or if it's easier we do that directly. Then no footgun there too. ;)

**Comment by Pytal** [comment]
New color presets used in https://github.com/nextcloud/server/pull/34298

**Comment by nickvergessen** [comment]
Please note/adjust `tertiary-on-primary` in the vue library accordingly as well.
The name might not be matching anymore but it is only used for buttons that are added in the top bar, e.g. in Talk to open the sidebar.

**Comment by Tealk** [comment]
Does the following problem also apply here?

A separate background, the upper edge is bright
Theme Colore #078D4E

Unfortunately I don't know how to get the navigation dark like it is with some of the preinstalled background images.
![image](https://user-images.githubusercontent.com/12276250/194907656-2d085ef8-4c61-4f2b-8433-e87acd5d4293.png)

**Comment by Pytal** [comment]
Rewrite of admin theming in https://github.com/nextcloud/server/pull/34359

**Comment by Pytal** [comment]
Using dark navigation icons for custom backgrounds would be a separate issue @Tealk, feel free to open a new issue

**Comment by PVince81** [comment]
- [x] BUG: https://github.com/nextcloud/server/issues/34457

**Comment by PVince81** [comment]
- [ ] issue: cache buster needs to be user specific: https://github.com/nextcloud/server/issues/34472

**Comment by PVince81** [comment]
- [ ] bug: https://github.com/nextcloud/server/issues/34338

**Comment by skjnldsv** [comment]
Fixed now I guess with the various PR and the last https://github.com/nextcloud/server/pull/34576
Closing as there is individual tickets for the extra points
