### ISSUE TITLE
FilePicker: "Add new directory" does not work and looks distorted

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#34694]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using the FilePicker in "choose file" mode (enabled picking directories), then there is a "+" button allowing you to create new directories.

1. Clicking this button opens a submenu for entering the directory name, that input field is broken, as I am not able to change the content of the textinput, so only creating directories called "New folder" is possible.
2. The submit button (arrow) is distorted by 3 pixels, as the input field has set a margin of 3px but the submit button does not, see screenshot below

### Steps to reproduce

1. Create a new filepicker
3. Open it
4. try to create new directory

```js
const filePicker = new FilePicker(
	'Select file or folder',
	false, // multiselect
	[], // mime filter
	true, // modal
	FilePickerType.Choose, // type
	true, // directories
	`/` // path
)

filePicker.pick()
```
(you can also use `OC.dialogs` directly, this issue is not bound to `@nextcloud/dialogs`)

### Expected behavior

You can enter a different directory name and the submit button does not look distorted

### Web server
Apache (supported)

### Is this bug present after an update or on a fresh install?
Fresh install

### Are you using the Nextcloud Server Encryption module?
No

### List of activated Apps
Fresh and clean install form master

### Additional info
Tested this on the current nextcloud server git master. Using Firefox 104.

The distorted button is caused by the margin of the input field, set in `inputs.scss` line 203

### Screenshot of distorted submit button
![submit button moved 3px up relative to the input field](https://user-images.githubusercontent.com/1855448/196929400-09098876-6025-49cc-8f5f-ff3d654923c4.png)
