### ISSUE TITLE
Bring back 32 bit support on Nextcloud 26

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#36072]
### Tasks

- [x] implement CI for 32bit
- [x] changes that will need reverting:
    - implement setup check to block installing on 32bit (master)   
        - [x] https://github.com/nextcloud/server/pull/34907 
    - make admin overview check more clear that 32bit compatibility is removed with nc26 (master and stable25) 
        - [x] https://github.com/nextcloud/server/pull/34906 
          - [x] https://github.com/nextcloud/server/pull/36587
        - [x] https://github.com/nextcloud/server/pull/34921
          - [x] https://github.com/nextcloud/server/pull/36631
    - make docs more clear that 32bit compatibility is removed with nc26 (master and stable25) 
        - [x] https://github.com/nextcloud/documentation/pull/9274 
          - [x] https://github.com/nextcloud/documentation/pull/9615
        - [x] https://github.com/nextcloud/documentation/pull/9279
          - [x] https://github.com/nextcloud/documentation/pull/9620
    - implement check into updater to block upgrades to nc26 on 32bit (master and stable25) 
        - [x] https://github.com/nextcloud/updater/pull/446 
          - [x] https://github.com/nextcloud/updater/pull/464
        - [x] https://github.com/nextcloud/updater/pull/452
          - [x] https://github.com/nextcloud/updater/pull/465
        - [x] https://github.com/nextcloud/server/pull/34908 
          - [x] https://github.com/nextcloud/server/pull/36588
        - [x] https://github.com/nextcloud/server/pull/34922
          - [x] https://github.com/nextcloud/server/pull/36593
- [ ] implement 32bit tests for things formerly breaking on 32Bit (where not mitigate-able due to technical restrictions)
    - test with each CI run would be fine plus running the whole suite (that would work on 32bit" regularly (i.e. daily or weekly against master/stable*) would be enough to not burn too much CI resources

Regarding the typing, instead of removing typing like for stable25 we should use the union types available thanks to PHP 8 and use `int|float`.

Running the CI on 32 bits is not that straightforward because Github does not propose it so one has to run a docker in a docker or something along these lines. Need someone with knowledge on CI/docker.

On Drone, 64bit hardware is likely able to run 32bit code.
See "arch" field in https://docs.drone.io/pipeline/configuration/

It should not be too hard to fix once we have proper CI, given we have the PR for stable25 to use as an example of how to fix stuff. That said it seems stable25 is still not passing test suite on 32bits.

Estimate: possibly 2 weeks effort if not more depending on hurdles and whether we need to port Github workflow tests to Drone

@AndyScherzinger @DaphneMuller @come-nc @blizzz

**Comment by ZendaiOwl** [comment]
> Running the CI on 32 bits is not that straightforward because Github does not propose it so one has to run a docker in a docker or something along these lines. Need someone with knowledge on CI/docker.

I don't know, maybe you guys already know about it and have more knowledge than me but I thought I could at least mention my thoughts. :pray: 

I'm guessing you would need something similar to the `Release` workflow that's been setup for NCP? 

Release Workflow: https://github.com/nextcloud/nextcloudpi/actions/runs/3914606592/jobs/6691860077

It has it's own runner for armhf using Docker that builds an image using Buildx for the 32bit platform support and uses the binaries from tonistiigi for multiple architecture support. (Mentioned in the Docker documentation here: https://docs.docker.com/build/building/multi-platform/) 

The binaries are installed with: `docker run --privileged --rm tonistiigi/binfmt --install all`

`build-docker.yml`: https://github.com/nextcloud/nextcloudpi/blob/master/.github/workflows/build-docker.yml

**Comment by PVince81** [comment]
@come-nc can you update the status, in case there was progress on the revertings ?

**Comment by come-nc** [comment]
Only reverted the first one in my PR, I checked the boxes with current PR state.

Current CI status in the PR:
Tests: 14429, Assertions: 37379, Errors: 8, Failures: 6, Warnings: 29, Skipped: 42.

On the 8 errors:
- 7 are `PHPUnit\Framework\MockObject\UnknownTypeException: Class or interface "OCA\Files_External\Lib\StorageConfig" does not exist` from `tests/lib/Encryption/UtilTest.php:208`. They also fail in my 8.2 testing PR and should be fixed or skipped, but are not related to 32bits
- 1 is `ValueError: Epoch doesn't fit in a PHP integer` from sabre-dav, needs investigation and fix or skip

On the 6 failures:
- All 6 of them seem related to the routes loading failing for files application. From what I was able to debug the include_once in lib/private/Route/Router.php does not include the routes because the file was already included but the routes were lost for some reason. It only happens in github and not in drone or local run, and only happens when running apps/files tests after core tests. So some kind of env specific loading problem. Not related to 32bits. Not clear how to fix it and not sure if safe to skip routing tests on 32bits?

**Comment by come-nc** [comment]
- [ ] https://github.com/sabre-io/dav/pull/1444

**Comment by szaimen** [comment]
Looks like everything done now or is something missing?

**Comment by blizzz** [comment]
> Looks like everything done now or is something missing?

I am not aware of anything missing.  @come-nc  can you confirm?

**Comment by come-nc** [comment]
Backport of CI and fixes to 25 is missing but that will have to wait 25.0.5.

**Comment by blizzz** [comment]
> Backport of CI and fixes to 25 is missing but that will have to wait 25.0.5.

which ones did i miss? (but this issue is about 26?)

**Comment by come-nc** [comment]
> > Backport of CI and fixes to 25 is missing but that will have to wait 25.0.5.
> 
> which ones did i miss? (but this issue is about 26?)

The fixes which were done in the PR adding CI: https://github.com/nextcloud/server/pull/36120
The CI needs to be backported to 25 and some things will break, and some of the fixes will have to be backported.
But it’s not an easy backport because typing is different on 25 and 26.

**Comment by ZachHandley** [comment]
hey so, I don't know if this is the right issue, but I have this error 
<img width="447" alt="image" src="https://github.com/user-attachments/assets/49adbf56-7169-4979-82d2-e4b62a8fde9b">
only on files over 2 GB, these aren't four, they're 3.7 GB, so it's extra weird. From the research I've done, it's related to #16431 -- if I'm wrong please don't re-open, but I can't upload anything and I have a hetzner cloud 32 bit so.

**Comment by AndyScherzinger** [comment]
Can't say for sure @ZachHandley - best to raise a new issue so folks can reply to it. I know there is a limitation in terms of file size 32Bit can handle due to the limitations that come with it within PHP.
