### ISSUE TITLE
[Feature] CardDAV - expose system address book

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#37797]
Part of https://github.com/nextcloud/server/issues/19575

Currently, the system principal address book is not available from the AddressBookHome.

## Todo

- [x] Add the system address book while still respecting the share enumeration settings as defined in the Share API.
- [x] Exclude any users coming from https://github.com/nextcloud/guests (uri: Guests:email.vcf)
- [x] Exclude any disabled users (in my tests, they disappeared from the system address books).

## Follow-ups

* Feature request: expose a guest users addressbook (use case still to be found)
