### ISSUE TITLE
📣 Set reminder: file/folder

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#39181]
### Tasks

- [x] https://github.com/nextcloud/server/pull/39651
- [x] https://github.com/nextcloud/server/pull/39685
- [x] https://github.com/nextcloud/server/pull/39798

---

Add ability to set reminders for a file/folder resulting in a notification pointing to the item at the chosen time, see example GMail:

https://github.com/nextcloud/server/issues/39181#issuecomment-1641880618
![image](https://github.com/nextcloud/server/assets/925062/261004db-d029-42da-89f7-09837ab586f9)

For a first iteration of the feature we only implement the fixed options, no option to pick an individual time.

For scheduling a notification please check Deck / @juliushaertl since Deck can already send notification for Deck cards when you hit their due date.

The notification should simply be "Reminder for {file-name or folder-name}" with the placeholder being bold + a action button "View file" or "View folder" that brings you directly to the file/folder in the files view (like the "View chat" does for notifications when being mentioned in a Talk room giving you an easy way to navigate there.

**Comment by jancborchardt** [comment]
@nimishavijay this is very related to "snooze mails", do you want to specify both together? :)
https://github.com/nextcloud/mail/issues/2048

**Comment by jancborchardt** [comment]
> Like where would the reminder option be located

We should simply put it in the 3-dot menu in files. Between "Move or copy" and "Edit locally" would be a good position.

> which options would be offer?

The options you mention are good:

Set a reminder
- In 1 hour
- Tomorrow
- Next week
- Custom (possibly as a follow-up feature)

Then at the specified time you would get a Nextcloud notification. If it is a shared file, still only the person who set a reminder should get a notification.

cc @nimishavijay to coordinate for the options we would have in Mail and other apps for this. She also mentioned a possible "Reminder note" feature, but let’s keep it simple first only with the reminder time.

**Comment by AndyScherzinger** [comment]
@Pytal if you have any design questions please get in touch with @jancborchardt or @nimishavijay. @jancborchardt and @nimishavijay I took the liberty to summarize things in the issue description and also spec how the notification should look like and behave.

**Comment by jancborchardt** [comment]
@Pytal @nickvergessen for consistency let’s call it "Set reminder" in both cases. We don’t use "me" anywhere in the interface, and "Set reminder" is a simple common expression and call to action. :)

**Comment by Pytal** [comment]
Any icon changes needed @jancborchardt @nimishavijay ?

![image](https://github.com/nextcloud/server/assets/24800714/20148454-5d3a-429e-b322-dcd57805237d)
![image](https://github.com/nextcloud/server/assets/24800714/d52d5df3-cf0d-4294-b544-ca33c033ac7e)

**Comment by Antreesy** [comment]
As we started to discuss it here:
- Should the time appearance be adjusted to user's locale (24h, 12h)?

**Comment by nickvergessen** [comment]
> Should the time appearance be adjusted to user's locale (24h, 12h)?

yes of course, just use the existing methods we have ([nextcloud-moment](https://github.com/nextcloud/spreed/blob/master/package.json#L31))

**Comment by AndyScherzinger** [comment]
> Which time points are we picking: 

see https://github.com/nextcloud/server/issues/39181#issuecomment-1641880618

* At morning - 8 AM
* At evening - 6 PM

> If time has passed (for example, I'm picking "Later today 6 PM" at 6:15 PM) - what should be shown oft this option? Maybe, "plus two hours rounded" from current time (8:00 PM)?

Nice idea, yet it get complicated, what if I open the menu 2,5h after the time slot? I would vote to keep it simple and just hide options that lie in the past, which can only happen for "Later today". What do you think @jancborchardt @nimishavijay

**Comment by Antreesy** [comment]
> especially if it’s a region where starting of the week is on Sunday.

It should be possible to get and use first day of week from NC Locale for `Next week`.
Will be `moment().weekday(0)` for JS code, but not aware of analog for mobiles

**Comment by SystemKeeper** [comment]
There are probably ways, yes. But most likely the user does not want to be reminded on a Sunday. I would still prefer to be explicit about it and use „Next Monday“ and „Next Saturday“

**Comment by AndyScherzinger** [comment]
"Next week" isn't confusing (see screenshots) since it also shows the exact time (Mon, 8:00 AM) for example. So "Monday" is already in.

"This weekend" would then also be hidden applying the rule also @SystemKeeper mentioned, if Saturday past 8:00 AM, hide the option.

**Comment by nimishavijay** [comment]
> Any icon changes needed?

Nice! I would suggest to use the [alarm icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aalarm%3A) for "Set reminder".

For the time options, since they are simply communicating different times, we could keep it simple and use radio buttons like in [Mail](https://github.com/nextcloud/mail/issues/2048#issuecomment-1644211312)? That would also make it easy for the "Clear reminder" option -- no need to mention the time. Would that be possible? :)

> Nice idea, yet it get complicated, what if I open the menu 2,5h after the time slot? I would vote to keep it simple and just hide options that lie in the past, which can only happen for "Later today"

I can see a use case where someone is at work and wants to remind themselves of a personal file after they get back. How about a solution between always showing +2h and always hiding after 18:00? Logic:
- Current time < 17:30 -->Later today = 18:00
- Current time between 17:30 and 20:30 --> Later today = 21:00
- Current time > 20:30 --> Hide later today, show directly tomorrow morning 

@AndyScherzinger would that be a more simple solution? :) also cc @jancborchardt

**Comment by Pytal** [comment]
> Nice! I would suggest to use the [alarm icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aalarm%3A) for "Set reminder".

👍

> For the time options, since they are simply communicating different times, we could keep it simple and use radio buttons like in [Mail](https://github.com/nextcloud/mail/issues/2048#issuecomment-1644211312)? That would also make it easy for the "Clear reminder" option -- no need to mention the time. Would that be possible? :)

Thought of that but unlike mail, where the user flow is Send later (action menu button) → Select radio → Send later (primary button) i.e.
![image](https://github.com/nextcloud/server/assets/24800714/b72b02ef-bcff-49af-8e86-3eee4462a13a)
the user flow here is Set reminder → Later today with less clicks

If we do radios here then we need another button at the end to commit the selected time, what do you think @nimishavijay? Also would have to do the same on iOS/Android 🤔

> I can see a use case where someone is at work and wants to remind themselves of a personal file after they get back. How about a solution between always showing +2h and always hiding after 18:00? Logic:
> 
> * Current time < 17:30 -->Later today = 18:00
> * Current time between 17:30 and 20:30 --> Later today = 21:00
> * Current time > 20:30 --> Hide later today, show directly tomorrow morning

As this is still being discussed could we have a spec for the reminder times and all edge cases to ensure consistency across implementations @jancborchardt @nimishavijay?

**Comment by skjnldsv** [comment]
> We should simply put it in the 3-dot menu in files. Between "Move or copy" and "Edit locally" would be a good position. The label is "Set a reminder" and it would open a submenu like we do for "More actions" in Mail.

Currently, we have no existing support or API for this @jancborchardt 
Adding some kind of submenu for actions is kinda out of scope I would say.
An action is unique and have nothing to do with how it is rendered in the Files UI. The current API is ver clean and simple and I think for the sake of maintenance, we should keep it like that: One action = one entry.

Can you provide a viable alternative that doesn't involve creating a multi-layer Actions menu please? 
Would a Modal be good enough? Any other idea?

**Comment by jancborchardt** [comment]
@Pytal regarding times, we should pick the exact ones that Google is using since it’s sort of a standard – see screenshot in the first post https://github.com/nextcloud/server/issues/39181#issue-1791008111

**Comment by jancborchardt** [comment]
Notes from the call with @skjnldsv @Antreesy @JohannesGGE @nickvergessen @ChristophWurst @nimishavijay 
If I missed anything please add it. :) cc @Pytal @AndyScherzinger also please check.

## Spec clarifications
- Should be done using the submenu of NcActions like in Mail "Send later" or "More actions", conditional actions list
  - Improvement for components would be a slight left/right animation, vue-transition
- Menu should be directly closed on picking an option
- For the custom date picker
  - NcActionsInput with the prop isNativePicker
  - there should be a "Save" button next to the input field
- Icons for the dates in the menu are too much, can be removed
- Detail – the dash needs to be an "en" dash instead of "em": "–"

## Known issues to fix in the future
- Currently reminders are not easily cancelable for other apps (oc_jobs table is too large). For now we only save on menu close and "Back" click.
- Ideally the time is displayed in color-text-maxcontrast and right-aligned, like Google Mail does it (see screenshot in first post)

**Comment by nickvergessen** [comment]
And we hide "Next week" on Sunday because it's the same as "Tomorrow", right?

**Comment by nickvergessen** [comment]
> And maybe on Saturday as well?

No, but "This weekend" on friday

**Comment by jancborchardt** [comment]
@nickvergessen yes, hiding "Next week" on Sunday sounds good.

@ChristophWurst the issue is that doing it based on locale also means "Next week has to be adjusted based on locale. If it's reasonably easy to do then yes let's do it, otherwise out of scope.

**Comment by Antreesy** [comment]
>  "Next week has to be adjusted based on locale

It may be not that hard, but "First day of week" is not the same as "First working day of week". I suppose, we're meaning the second option for the next week reminder?

**Comment by wokawoka** [comment]
Is there a way to receive an email notification for the reminder  (and not just a push notification) ?

Sorry, I went to the notifications section (for activities) in the settings but i couldn't find a setting for file/folder reminders, and I already tried to search the answers to this issue and nextcloud documentation without any luck.
Thank you!
