### ISSUE TITLE
[Bug]: special characters at "target directory" window

### ISSUE THREAD

**Issue by koebi80** [nextcloud/server#39683]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

At the "target directory" window special characters like **'** in the directory name aren't not corect showed at the buttons "copy to" and "move to".

![Bildschirmfoto 2023-08-02 um 23 31 16](https://github.com/nextcloud/server/assets/106907779/3cdfc1a3-f4b7-4795-9b26-ef6daa6a8659)

 

### Steps to reproduce

1. create a directory with an **'** in the directory name
2. start copy a file to this directory

### Expected behavior

Correct the output of the directory name at the buttons "copy to" and "move to".
At the path line the directory name is correct showed.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
I plan to fix this with #38926

**Comment by joshtrichards** [comment]
Duplicate of #33137 
Consolidating tracking reports/progress there.
