### ISSUE TITLE
[f2v] Final overview

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#39914]
## Main modules
- [x] Files: #39808 
- [x] Systemtags: https://github.com/nextcloud/server/pull/40475

### Submodules
- [x] File upload + New files/folder menu: https://github.com/nextcloud/server/pull/39945
- [x] Breadcrumbs sharing icon https://github.com/nextcloud/server/pull/40192
- [x] Drag and drop + Move/Copy action #39998 
- [x] Sort favorites first option #37946
- [x] Grid view  https://github.com/nextcloud/server/pull/40917
- [ ] Search
  - closes https://github.com/nextcloud/server/issues/1274
  - closes https://github.com/nextcloud/server/issues/38312
- [x] Folder icon overlay https://github.com/nextcloud/server/pull/40209
- [x] Dropzone https://github.com/nextcloud/server/pull/40674

### Actions
- [ ] Support nested actions
  - closes https://github.com/nextcloud/server/issues/39718
- [x] Inline tag display https://github.com/nextcloud/server/pull/40284
- [x] Inline comments action https://github.com/nextcloud/server/pull/40409
- [ ] Inline locked state https://github.com/nextcloud/files_lock/issues/154
- [x] Inline share action https://github.com/nextcloud/server/pull/40517
- [x] Template picker https://github.com/nextcloud/server/pull/40854
- [ ] Disconnect/leave share delete node: https://github.com/nextcloud/server/issues/40940 https://github.com/nextcloud/server/blob/dd3cd29224cd93c6168cd42e93e68cdd6ac5e921/apps/files/js/fileactions.js#L787-L791

#### Undecided / later
- [ ] Files public (the public files app is behaving very differently and needs dedicated separate work) 
- [ ] My files view
  - closes #9528

## Regressions

- #40514 

## Testing
- [ ] Acceptance cypress

## Follow-ups
- [x] Dive into a potential perf boost on the virtual scrolling with some pseudo-code key mapping https://github.com/nextcloud/server/pull/40917
- [ ] Implement keyboard navigation and shortcut page: https://github.com/nextcloud/server/issues/30484
- [x] Deprecate files_rightclick
- [ ] Remove `/apps/files/js`
- [ ] Photos previews get outdated after an edit from the viewer https://github.com/nextcloud/server/issues/40230

## Apps customizations
- [x] Disabled style for end-to-end encrypted folders

**Comment by artonge** [comment]
Linked https://github.com/nextcloud/server/issues/38156 for "Inline share action"

**Comment by artonge** [comment]
Added: disabled style for end-to-end encrypted folders

**Comment by artonge** [comment]
While you are at it: photos previews get outdated after an edit from the viewer: https://github.com/nextcloud/server/issues/40230

**Comment by artonge** [comment]
Weird bug:
- Select all
- Scroll to the bottom
- Unselect last item
- Scroll up
- See that all files that were not visible when unselecting the last item are not selected anymore.

**Comment by skjnldsv** [comment]
> Added: Weird bug when unselecting files while the list is scrolled:
> 
> * Select all
> * Scroll to the bottom
> * Unselect last item
> * Scroll up
> * See that all files that were not visible when unselecting the last item are not selected anymore.

Already fixed with https://github.com/nextcloud/server/pull/39998
But please open dedicated issue instead of using that issue :)
