### ISSUE TITLE
📅⛔ Allow users to select another user as their out-of-office replacement

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#40398]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Is your feature request related to a problem? Please describe.
As a Nextcloud users I want to make sure others know about my vacation replacement when they try to contact me for urgent topics.

### Describe the solution you'd like
Let me pick another Nextcloud user as my replacement in the new UI of https://github.com/nextcloud/server/issues/40397. The replacement has to be optional because some people don*t have replacements. Expose the info through the API so that apps consuming out-of-office can do a meaningful redirect to my replacement.

## Implementation

Use the sharee API or similar to find users. Make sure sharing enumerations are valued, so that the user only sees others they may see. Store the user ID in the database. Expose the ID through the OOO API.

## Work packages
- [x] Adjust UI, persistence and API for the new property https://github.com/nextcloud/server/pull/45766
- [x] Adjust Talk so it shows a hyperlink to the replacement user and make it easy to jump into their 1:1 room https://github.com/nextcloud/spreed/pull/12510
- [x] Developer manual documentation https://github.com/nextcloud/documentation/pull/11940
- [x] User manual documentation https://github.com/nextcloud/documentation/pull/11941

## Aditional context
- [x] Requires https://github.com/nextcloud/server/issues/40397
