### ISSUE TITLE
Allow users to enter out-of-office info, propagate to Calendar, user status, Mail and Talk

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#40397]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Is your feature request related to a problem? Please describe.
As a Nextcloud user I want to have a central place where I can enter my unavailability for vacation, sick leave or other. The info should be used to let my family, friends or colleagues know that I'm not here to respond to their messages.

### Describe the solution you'd like
Add a new section to the existing availability settings in the personal settings. Let me enter the following details:
* Absence message (multi line free text)
* Status text (single line)
* Start of absence (inclusive)
* End of absence (inclusive)

Based on the input above, do
1) Write an event to my calendar so I show as busy when someone tries to book a meeting
2) Set my user status to the status text and do-no-disturb at the start of the absence, reset when it ends
3) Set my Mail app account(s) auto responder to the date range and the absence message at the start of the absence, reset when it ends
4) Show the absence message inside 1:1 chats when others try to reach me

## Work packages
- [ ] Settings in server with persistence in database
- [ ] Write vacation into user's personal calendar with status **busy**. Replace event when absence info changes. Delete event when absence ends or is disabled.
- [ ] Expose out-of-office user info for Mail, Talk and other apps to read
- [ ] Change user status at the beginning of the absence, reset at the end
- [ ] Apply out-of-office user info to Mail's auto responder settings (if enabled)
- [ ] Show out-of-office user info in 1:1 conversations

## Additional info

This is an MVP. The big picture is tracked in https://github.com/nextcloud/server/issues/31607.

**Comment by nickvergessen** [comment]
- [ ] Would be helpful to also show it on the profile (maybe optional, so users can select "only people that are logged in" in case they post direct phone numbers

**Comment by nickvergessen** [comment]
- [ ] As lead/manager/sysadmin I would also think it's helpful to be able to set it for other people (via API or OCC), in case they can not return to set it themselves.
