### ISSUE TITLE
[Bug]: task list disappears

### ISSUE THREAD

**Issue by Franz36** [nextcloud/server#40812]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

One of many todo list shows briefly on left side menu, then disappears. 
From clients the list ist not readable but writeable.
From Iphone a an old task can be marked "complete" or new task can be created, activity is shown in activity-log. 
But new/change tasks are not transferred to other clients.

After some days list reappeared in menu on left side, but ist empty. *.ics-Export and import to new list is incomplete and shows random items.

### Steps to reproduce

1. Open Nextcloud Tasks in Webbrowser. All Task lists appear, then after 1-3 seconds 1 of them disappears.
2. This task list is accepting new data from clients (Iphone/Mac/Thunderbird). Activity is seen in activity-log.
3. New data is not transferred to other clients.
4. Other task-list work as expected.

### Expected behavior

All task-list stay visible in left side menu.
New tasks of all lists is transferred to clients.

### Installation method

Other

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "11": "x.x.x.x",
            "1": "172.18.0.2",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "6": "https:\/\/x.duckdns.org",
            "12": "x.duckdns.org",
            "3": "decce1b1740c",
            "22": "https:\/\/x.duckdns.org",
            "14": "decce1b1740c",
            "": "0718c5969ed0"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "https:\/\/decce1b1740c\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie",
            "OC\\Preview\\TXT"
        ],
        "maintenance": false,
        "data-fingerprint": "27d551cabf2d295c37fc7b40f322273a",
        "loglevel": 0,
        "theme": "",
        "updater.release.channel": "stable",
        "twofactor_enforced": "false",
        "app_install_overwrite": [
            "occweb",
            "files_external_ipfs"
        ],
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}
```

### List of activated Apps

```shell
Enabled:
 - accessibility: 1.9.0
 - activity: 2.15.0
 - appointments: 1.12.6
 - apporder: 0.15.0
 - calendar: 3.3.2
 - circles: 23.1.0
 - cloud_federation_api: 1.6.0
 - comments: 1.13.0
 - contacts: 4.1.1
 - contactsinteraction: 1.4.0
 - dav: 1.21.0
 - deck: 1.6.3
 - drawio: 1.0.3
 - extract: 1.3.5
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_external: 1.15.0
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - firstrunwizard: 2.12.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - mail: 1.13.4
 - maps: 0.1.10
 - metadata: 0.16.0
 - nextcloud_announcements: 1.12.0
 - nextcloudpi: 0.0.1
 - notifications: 2.11.1
 - notify_push: 0.4.0
 - oauth2: 1.11.0
 - password_policy: 1.13.0
 - passwords: 2022.6.10
 - photos: 1.5.0
 - previewgenerator: 99.99.99
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - rainloop: 7.2.5
 - ransomware_protection: 1.13.0
 - recommendations: 1.2.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - support: 1.6.0
 - survey_client: 1.11.0
 - systemtags: 1.13.0
 - tasks: 0.14.4
 - text: 3.4.1
 - theming: 1.14.0
 - twofactor_admin: 3.2.0
 - twofactor_backupcodes: 1.12.0
 - twofactor_gateway: 0.19.0
 - twofactor_nextcloud_notification: 3.4.0
 - twofactor_totp: 6.4.0
 - user_status: 1.3.1
 - video_converter: 1.0.5
 - viewer: 1.7.0
 - workflow_media_converter: 1.3.6
 - workflowengine: 2.5.0
Disabled:
 - admin_audit
 - dashboard: 7.0.0
 - encryption
 - updatenotification: 1.11.0
 - user_ldap
 - weather_status: 1.0.0
```

**Comment by nextcloud-command** [comment]
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by joshtrichards** [comment]
Please provide your Nextcloud log contents from the time period where this happens:

> One of many todo list shows briefly on left side menu, then disappears.

Also check your browser console log for anything interesting under the Network and Console tabs

**Comment by nextcloud-command** [comment]
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.
