### ISSUE TITLE
Beta design feedback

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#41450]
Discussed with @karlitschek and @marcoambrosini. cc @AndyScherzinger for awareness. Sorted by priority of visual impact.

Since we are in the beta stage and already beyond feature freeze, we need to focus on easy fixes.

1. [x] **Sidebar tabs too present and conflict with primary buttons, especially in Talk:** Style will be changed from full primary background highlight to underline. → FIX at https://github.com/nextcloud-libraries/nextcloud-vue/pull/4815
2. [x] **Share button too present:** Style change to tertiary non-bold button (background will be removed and color adjusted to color-primary-element). → FIX at https://github.com/nextcloud/server/pull/41453
3. [x] **Groupfolder and other folder icons are off:** There is a dark icon with white stroke on color-primary icon. Instead icon should simply be color-primary-element-text on the color-primary-element icon – same logic as the primary button. → FIX at https://github.com/nextcloud/server/pull/41455
4. [x] **Favorites button in sidebar overlaps icon/preview too much:** "Favorite" can move to actions menu, and indicator to start of subline with size and modified date. https://github.com/nextcloud/server/pull/41481
5. [x] **Comments layout improvements:** Vertically align name with avatar, remove "" quotes so subline does not wrap. https://github.com/nextcloud/server/pull/41481

![Files](https://github.com/nextcloud/server/assets/925062/5456ff6a-1f45-42d4-9fd4-a2aa5afacd2c)

Additional second set of feedback:
1. [ ] **Black border in "New" menu in Safari:** There is a black border on the first entry of the "New" menu. It should only appear on tab navigation, not on initial opening or interacting with the mouse. → Bug with Safari, does not appear with Chrome. @ShGKme can reproduce
   Issue: https://github.com/nextcloud-libraries/nextcloud-vue/issues/4874
2. [ ] **Some action menus have scrollbars:** Issue exists at https://github.com/nextcloud-libraries/nextcloud-vue/issues/3920 → According to @marcoambrosini @szaimen very complicated as the component would need logic to know where it is opened. Currently always 50vh to work in all circumstances.
3. [x] **Time of calendar notification is based on first of a recurring meeting:** The time in the notification should be based on the next meeting and not the first of a recurring event. → Christoph opened issue at https://github.com/nextcloud/server/issues/41615
4. [x] **External storage settings layout looks off:** Should be on top of the page, or properly integrated into emptycontent view → @marcoambrosini @szaimen https://github.com/nextcloud/server/issues/41614
5. [x] **"Shared" label takes a lot of space in Files list for internal shares:** → Proposals at https://github.com/nextcloud/server/issues/41620 https://github.com/nextcloud/server/pull/41656

Some more feedback from Jan:
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/issues/4872
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/issues/4870 → pull request at https://github.com/nextcloud-libraries/nextcloud-vue/pull/4875
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/issues/4871

**Comment by jospoortvliet** [comment]
Jan, the improvements already made are nice, especially that first one.

I do have an additional issue - not sure if it's design or a bug:
![Screenshot_20231115_033010](https://github.com/nextcloud/server/assets/551757/72519134-ed0e-4a64-a553-8458b79bc2ca)

The copy/move can't be found there anymore. Those are far more typical operations on multi-select than the ones currently there. Should this be a separate issue?

**Comment by jancborchardt** [comment]
@jospoortvliet good find – that is a separate issue as it's a functionality regression rather than a design issue. Also cc @AndyScherzinger for info.

**Comment by AndyScherzinger** [comment]
Yes, I agree

> separate issue as it's a functionality regression rather than a design issue, can you raise a ticket for it please? Thanks in advance

**Comment by AndyScherzinger** [comment]
> The copy/move can't be found there anymore. Those are far more typical operations on multi-select than the ones currently there. Should this be a separate issue?

@jospoortvliet where exactly is it missing? So @susnux can take care of fixing. https://github.com/nextcloud/server/issues/41450#issuecomment-1811707144

**Comment by jospoortvliet** [comment]
Well, next to the Delete button? The Delete used to not be there - on my 27.1 Nextcloud these options are there:
![Screenshot_20231121_190140](https://github.com/nextcloud/server/assets/551757/6cc185c1-7dad-4333-834c-4bb4412ddf2f)

So we removed tagging - I don't care personally but I can imagine people who use tags do - and we removed copy/move. And we added delete.

Now when I select a bunch of files, I more often move them than that I delete them, so I would either replace delete with Copy/Move, or at least add copy/move.

**Comment by jancborchardt** [comment]
Issue for "Move or copy" opened at https://github.com/nextcloud/server/issues/41661, let’s keep the discussion over there since as said it’s not a design issue.

**Comment by jospoortvliet** [comment]
Maybe this is also something: https://github.com/nextcloud/server/issues/42098 -> the right click menu opening far from the cursor.

**Comment by jancborchardt** [comment]
@AndyScherzinger @sorbaugh since there are only 2 issues remaining here, I would suggest scheduling those for the next Files cycle specifically and closing this issue so they don’t get lost.

**Comment by AndyScherzinger** [comment]
Sounds good to me, can you take care of it @sorbaugh

**Comment by jancborchardt** [comment]
Closing this then as we have follow-up issues. cc @sorbaugh for the scheduling – the menu scroll one I have noted for the next planning meeting from my side.
