### ISSUE TITLE
Migrate public files to the same Files UI

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#42968]
After https://github.com/nextcloud/server/issues/28063 and all the various other items in https://github.com/nextcloud/server/projects/6

## TODO
- [ ] Folder view
- [ ] File drop
- [ ] Single file view

### Will allow
- [ ] https://github.com/nextcloud/server/issues/4109
- [ ] https://github.com/nextcloud/server/issues/16515
- [ ] https://github.com/nextcloud/server/issues/3234
- [ ] https://github.com/nextcloud/server/issues/26536

## Needs
- [x] #32400

**Comment by nooblag** [comment]
Great to see this in progress! :+1:
