### ISSUE TITLE
Better arrangement of items in "New" menu in Files

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/server#43728]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Uploading and adding new files and folders is one of the most common actions in Files. The most obvious way to do this is through the "New" menu. Currently, the items in this menu are simply in one big list, making it possibly difficult to find the action you are looking for. There is also a lot of repeated words (new file, new document, new spreadsheet, etc) and outdated icons are used (as we prefer material design icons)

Current state:

**Describe the solution you'd like**
Some small tweaks to the menu can make it look more organised and easy to find your desired action. 

| Before | After |
|---|---|
| ![image](https://github.com/nextcloud/server/assets/52440189/9051a0af-28f9-42b0-91f1-554eb379f7c1) | ![image](https://github.com/nextcloud/server/assets/52440189/1eb9d878-e385-4b34-9a98-501c217ff723) |

- [x] Group the different items using NcActionSeparator and NcActionCaption components: Upload group, new items group, and add description
- [x] Add an option to upload folder as well (there are multiple [forum posts](https://help.nextcloud.com/t/is-it-possible-to-upload-folders/21583/5), [community issues](https://github.com/nextcloud/server/issues/14707) and [customer issues](https://github.com/nextcloud-gmbh/customer-feature-requests/issues/233) about it)
- [ ] Rename 
  - [ ] "New folder", "New document", etc to just "Folder", "Document"
  - [ ] "Add description" to "Add folder description"
- [ ] Reorder
  - [x] Upload: Upload files, upload folders
  - [x] New: Folder, text file, document, spreadsheet, presentation, diagram
  - [ ] Add folder description
- [x] Icons: Use material design icons #44340
  - [x] Upload files: current icon
  - [x] Upload folders: [drive-folder-upload](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Adrive_folder_upload%3A) in `--color-primary-element`
  - [x] Folder: [folder](https://fonts.google.com/icons?selected=Material%20Icons%3Afolder%3A) in `--color-primary-element`
  - [x] Text file: [article](https://fonts.google.com/icons?selected=Material%20Icons%3Aarticle%3A)
  - [x] Document: [description](https://fonts.google.com/icons?selected=Material%20Icons%3Adescription%3A) in `#49abea`
  - [x] Spreadsheet: [file-table-box](https://pictogrammers.com/library/mdi/icon/file-table-box/) in `#9abd4e`
  - [x] Presentation: [file-presentation-box](https://pictogrammers.com/library/mdi/icon/file-presentation-box/) in `#f0965f`
  - [x] Diagram: [drawing-box](https://pictogrammers.com/library/mdi/icon/drawing-box/) in `#ebc94a`
  - [x] Description: [notes](https://fonts.google.com/icons?selected=Material%20Icons%3Anotes%3A)

**Describe alternatives you've considered**
n/a

**Additional context**
Also a point to note in the [Files gap analysis](https://github.com/nextcloud/server/issues/43238) is the grouping of new/upload actions in other products (see "Creating and uploading").

**Comment by susnux** [comment]
@skjnldsv this would require us to have some groups for those actions in `@nextcloud/upload`.
What do you think of having three defined groups `UPLOAD`, `NEW` and `OTHER` to sort them in?

**Comment by skjnldsv** [comment]
hmmm, the two firsts are internal, so it might not be needed for those :thinking: 
But the last two, good idea yeah.

**Comment by AndyScherzinger** [comment]
@jancborchardt jsut looking at you as kind of a replacement here: Is the text icon meant to be black, hence adapting accordingly for dark/light themes or should it be grey - like before? Thanks in advance for the feedback 🙏

**Comment by AndyScherzinger** [comment]
-> we target v29 - just for the icon update. Anything else could come later to keep it simple and can be split into a separate ticket

**Comment by jancborchardt** [comment]
> @jancborchardt jsut looking at you as kind of a replacement here: Is the text icon meant to be black, hence adapting accordingly for dark/light themes or should it be grey - like before? Thanks in advance for the feedback 🙏

Considering this is also used in the file list and grid view (and in the widgets) and black this would be very dark then, we should indeed keep it grey.
FYI @nimishavijay @marcoambrosini

**Comment by jancborchardt** [comment]
> Diagram: [drawing-box](https://pictogrammers.com/library/mdi/icon/drawing-box/) in `#ebc94a`

And on this to have proper 3:1 contrast, we need to change the color to: `#b39114` @nimishavijay

**Comment by jancborchardt** [comment]
Also updated in the issue at https://github.com/nextcloud/server/issues/44340#issuecomment-2009470536

**Comment by susnux** [comment]
Except for the folder description, this is done with https://github.com/nextcloud-libraries/nextcloud-upload/pull/1175
