### ISSUE TITLE
Better integration of contacts, users and groups

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#4493]
With there being more sharing, federation etc the proper integration of how we handle users and groups becomes very important.

Now before we develop more into three different directions with the user management, Contacts app and now even Circles, we should see where we can consolidate.

I had a call with @daita of the Circles app and we talked about a few things. The best course of action seems to make Circles a backend-only app and have everything which you could do via the interface be integrated into existing parts of Nextcloud. And also some additional thoughts.

## Example

In my Contacts app I have a few people, among them:
- Maxence and Nina, who are on the same Nextcloud installation
- Lukas and Björn, and I have their Federated Cloud IDs
- Giorgia and Ivan, whom I only have email addresses of

Now if I create a Group with all of these people and share something with that Group, it should be shared in the most ideal way with everyone:
- Maxence and Nina get it as a normal share
- Lukas and Björn get it as a Federated Cloud share
- Giorgia and Ivan get an individual link each via the new email share flow

## Tasks

- [ ] Connect own Contacts entry and Personal settings info: You should be able to set a Contacts entry as »Yourself« like in Android and iOS too. That contacts entry should be connected to your personal profile.

- [ ] Connect Contacts entries with other people’s personal settings info, basically like a federated phonebook / Facebook.
	- [x] We have the »x-cloud« parameter as »Federated Cloud ID«
	- [ ] If you put in a Federated Cloud ID of someone else, any missing or outdated info should be checked from the global & public address book. In any case, this contact should be connected with that person.

- [ ] Suggest Contacts from sharing
	- [ ] If you shared with someone via federated cloud sharing already, they should show up in a new group »Sharing« in the Contacts app where you can then choose to add them as contact, or delete them. If it’s not desired to have these people sync to Contacts before they are actually added, this group can be »virtual« and not part of the Contacts address book.
	- [ ] Same for sharing by email – if that person is not in your Contacts yet, it should be added as a suggestion in the »Sharing« group.

- [ ] Different visibility / levels of Contact groups: Just like Circles has different levels of visibility, we could have that in Contacts. It could be implemented by using the 3-dot-menu for each group, and having a selector »Local«, »Contacts«, »Public« (or other options) much like the Personal settings.

- [ ] Users should only see one term for »Groups« – not »Circles« or »Teams« or something like that. That’s confusing.

- [ ] In the Mail app, enable people to send mails to entire Contact groups. Ref https://github.com/nextcloud/mail/issues/41

- [ ] more ideas?

cc @nextcloud/sharing @nextcloud/contacts @daita @schiessle @ChristophWurst @irgendwie @henni @LukasReschke @oparoz

**Comment by daita** [comment]
Structural question: Should Circles be completely integrated to Contacts or as a separated app and enabling Circles would add those features to Contacts ?

**Comment by dieter-wilhelm** [comment]
Another essential feature lacking is the possibility to invite Contact groups in the Calendar app not only individual email addresses.

**Comment by jancborchardt** [comment]
Has this been fully superseded by https://github.com/nextcloud/server/issues/13478, or is anything missing there? cc @MorrisJobke @skjnldsv @daita

**Comment by MorrisJobke** [comment]
> Has this been fully superseded by #13478, or is anything missing there? cc @MorrisJobke @skjnldsv @daita

Yes - this is the new ticket with more details and covers all of the stuff here IMO. Let's close this one here for now.
