### ISSUE TITLE
NextCloud 29.0 doesn't have the right link on some buttons in the upper Taskbar

### ISSUE THREAD

**Issue by architectonio** [nextcloud/server#45223]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Some icons/buttons in the upper Taskbar have a wrong link. Example, The icon "Mail" is supposed to have "https://nextcloud.server/apps/mail/" but instead has "https://nextcloud.server/settings/admin".
The affected icons are (at least fr my configuration) the following:
- Notes
- Mail
- Tasks
- Phionetrack
- Keeweb
- The Search
- Polls
- Tables

### Steps to reproduce

1. Open the NextCloud Web Page
2. Point your mouse on any of the previously listed Icons, e.G. "Mail" 
3. Instead the Mail Page, the Settings page is opened

### Expected behavior

Click and go to the right App page

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "29.0.0.19",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "loglevel": 0,
        "default_phone_region": "DE",
        "app.mail.verify-tls-peer": false,
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "filelocking.enabled": "true",
        "chunkSize": "5120MB",
        "theme": "",
        "versions_retention_obligation": "auto, 186",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "updater.release.channel": "stable",
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "fulltextsearch",
            "files_reader",
            "keeweb",
            "richdocuments",
            "whiteboard",
            "epubreader",
            "radio",
            "fulltextsearch_elasticsearch",
            "twofactor_admin",
            "impersonate",
            "drawio",
            "mailnotifier",
            "files_mindmap",
            "llm",
            "tasks",
            "integration_libretranslate",
            "files_fulltextsearch",
            "twofactor_email",
            "files_rightclick",
            "extract",
            "files_archive",
            "transfer"
        ],
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "90, 180",
        "mysql.utf8mb4": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "has_rebuilt_cache": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - analytics: 4.13.0
  - app_api: 2.5.1
  - assistant: 1.0.9
  - audioplayer: 3.4.1
  - bookmarks: 14.0.2
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.2
  - calendar_resource_management: 0.7.0
  - cfg_share_links: 5.1.0
  - checksum: 1.2.4
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - context_chat: 2.1.2
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.0
  - drawio: 3.0.2
  - epubviewer: 1.6.2
  - external: 5.4.0
  - extract: 1.3.6
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_archive: 1.2.3
  - files_automatedtagging: 1.19.0
  - files_confidential: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_fulltextsearch: 28.0.0
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - files_zip: 1.5.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.3
  - fulltextsearch: 28.0.1
  - fulltextsearch_elasticsearch: 28.0.1
  - impersonate: 1.16.0
  - integration_libretranslate: 1.1.1
  - integration_openai: 2.0.1
  - integration_openstreetmap: 1.0.12
  - keeweb: 0.6.18
  - llm: 1.2.1
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.6.0
  - maps: 1.4.0
  - music: 1.11.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - phonetrack: 0.8.1
  - photos: 2.5.0
  - polls: 7.0.3
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - qownnotesapi: 24.4.0
  - quota_warning: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.1
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - socialsharing_email: 3.1.0
  - spreed: 19.0.0
  - stt_helper: 1.1.1
  - stt_whisper: 1.0.8
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tables: 0.7.1
  - tasks: 0.15.0
  - text: 3.10.0
  - text2image_helper: 1.0.2
  - text_templates: 1.0.5
  - theming: 2.4.0
  - theming_customcss: 1.16.0
  - thesearchpage: 1.2.7
  - transfer: 0.6.3
  - twofactor_admin: 4.5.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_email: 2.7.4
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 11.0.0-dev
  - unroundedcorners: 1.1.3
  - updatenotification: 1.19.1
  - user_ldap: 1.20.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
	- EXTRA_FILE
		- core/img/filetypes/drawio.svg
		- core/img/filetypes/dwb.svg
- drawio
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 5b121122c0bec0580402c04605700056ee06eb553a4692bfc085ad3fc17aa49af43ca7795e98cbd22383020bfa9809bf3cc824b1673595f461479afb602bcec4
                            [current] => 3780abf2631567308dea2792113a813b71ed713c53769f4197a5e6205a4c2f1f6f6d84c8d58037e0a49b5148caf3be55276bf23f5e215e0e4d27cc8102c45b09
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [core/img/filetypes/drawio.svg] => Array
                        (
                            [expected] => 
                            [current] => 92e0974cf869bf8ab969c3442dc2b80d55fde36441d22924db74916a06b407520aa2a9dc39336f9157195ebede697ffac0e639360879255ab91932d406e1897d
                        )

                    [core/img/filetypes/dwb.svg] => Array
                        (
                            [expected] => 
                            [current] => 43731dd5f17a048112ea5109b40b02ec019b3ee2324385a0f448e3bd2264cb13dc160ab018d893f92f8e2f168fd09009b51578c8c6b97a02a1617c67ac087701
                        )

                )

        )

    [drawio] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**Comment by joshtrichards** [comment]
This doesn't seem to happen in a conventional installation. Maybe an interaction with one of the apps you have installed? Not sure.

Can you provide a screenshot?

**Comment by architectonio** [comment]
Very difficult to provide a screenshot, since it doesn't show what happens.  I'm try to explain why:
A screenshot will just show the NextCloud interface with all buttons/icons at the top.
Pointing and clicking one of these button/icons, the screen changes to the next one.
That means the screenshot will show 
1) NextCloud Files or Dashboard or whatever else
2a) The App (all apps except the listed above)
2b) The "App Discover" (clicking on any app listed above)

Since a screenshot is a static image of my screen or a part of it and not a dynamic video, please tell me how and what exactly I should take the screenshot of.

**Comment by architectonio** [comment]
I have disabled all apps and then enabled them one by one, but the problem persists. 
However, when I enter the link in the browser, all apps work as expected.

**Comment by bovender** [comment]
Same issue here after upgrading to NC 29. Some links point to the current page, e.g. the Dashboard or the Settings page.

Here are my icons, in order from left to right:

Dashboard -- works
Files -- works
Calendar -- works
Mail -- works
Passwords -- works
Photos -- works
Deck -- works
Activity -- works
Contacts -- works
Search -- works
Mastodon -- works
**Phonetrack -- does not work**
Notes -- works
**Tasks -- does not work**
**Memories -- does not work**
Maps -- works
**Health -- does not work**

So most of the icons are linked correctly, but Phonetrack, Tasks, Memories, and Health cannot be invoked from the app menu.

**Comment by melle2** [comment]
Maybe a feedback from me, as I'm using Phonetrack, too. Just upgraded to NC29 and the icon links are woking as expected, specifically Phonetrack.
![grafik](https://github.com/nextcloud/server/assets/71716485/eb16435f-0d83-4029-8d2f-633305ff86b9)

**Comment by architectonio** [comment]
I just checked again. 
Phonetrack (0.8.1) App Icon on my NextCloud 29.0.0.19 doesn`t show the correct link.

**Comment by melle2** [comment]
Could be a specific probblem of you plugin installation. Did you try to remove and re-add Phonetrack?

**Comment by architectonio** [comment]
I did, and I did again right now. Unfortunately the issue remains.

**Comment by melle2** [comment]
I'm running out of ideas right now... 
Tried the repair function? --> `./occ maintenance:repair` (should run as `www-data` user). Please create a backup before

**Comment by architectonio** [comment]
Yes I did it and I also tried all troubleshooting best practice procedures (at least what I know and what I found across forums and documentation).
Thanks for your hints.

**Comment by bovender** [comment]
On my system, I can alleviate and reproduce the problem be disabling and re-enabling the phonetrack app. Curiously, it affects other app's icons as well.

Meanwhile, the phonetrack repo now has an open issue also concerning the menu/icon link: julien-nc/phonetrack#45

**Comment by joshtrichards** [comment]
Weird. Seems someone associated with the phonetrack app based on what you're all experiencing. But I'm still unable to reproduce it with that app installed in my test environments.

Any custom css/etc in use? Either in the theming settings or via one of the custom css add-on apps?

**Comment by jewink** [comment]
Same issue here after updating the mail app to 3.6.1 yesterday. I have NC 29 running in docker.
The problem concerns the following apps: 
- mail
- notes 
- tables
Phonetrack, Tasks, Memories and Health are not installed.
The 3 affected buttons always point to the to the currently open page. So if files are open. they link to /apps/files/files, if photos is open they link to /apps/photos/ and so on....

**Comment by bovender** [comment]
> On my system, I can alleviate and reproduce the problem by disabling and re-enabling the phonetrack app.

Well I must admit that it's not just the phonetrack app, even though I was able to reproduce the issue by disabling and re-enabling said app. But the problem reappeared, and I currently have a working menu bar after having disabled the fulltext search apps. God knows what's going on here.

**Comment by lumintulogic-admin** [comment]
> Same issue here after upgrading to NC 29. Some links point to the current page, e.g. the Dashboard or the Settings page.
> 
> Here are my icons, in order from left to right:
> 
> Dashboard -- works Files -- works Calendar -- works Mail -- works Passwords -- works Photos -- works Deck -- works Activity -- works Contacts -- works Search -- works Mastodon -- works **Phonetrack -- does not work** Notes -- works **Tasks -- does not work** **Memories -- does not work** Maps -- works **Health -- does not work**
> 
> So most of the icons are linked correctly, but Phonetrack, Tasks, Memories, and Health cannot be invoked from the app menu.
> 
> edit: deleting all site data in my browser and then logging back in did not restore the links

I have the same issue. The links are broken only for some apps, but in my case "Passwords" is also one of them. So, I suppose it's not the problem from the individual app, but rathe from NC 29.

**Comment by prolibre** [comment]
I've just solved the problem by deactivating and reactivating the fulltextsearch application.
I wonder if the problem isn't with this application.

**Comment by architectonio** [comment]
To disable and then enable again all apps was one of the first steps of
mine... unfortunately the issue remain.

Il gio 23 mag 2024, 16:32 Anthony ***@***.***> ha scritto:

**Comment by wagnbeu0** [comment]
I´m having the same problem:

Files - is working
Photos - is working
Activity - is working
Spreed - is working
Fulltextsearch - is working
Deck - is working
Polls - is not working
Forms - is working
Tasks - is not working
Tables - is not working

I also tried the following suggestions:
sudo -u www-data php /var/www/occ  maintenance:mode --on
sudo -u www-data php /var/www/occ maintenance:repair
sudo -u www-data php /var/www/occ maintenance:update:htaccess
sudo -u www-data php /var/www/occ maintenance:theme:update
sudo -u www-data php /var/www/occ maintenance:mode --off

I also uninstalled and installed the apps again, but no lock. With NC28 everything worked.

**Comment by architectonio** [comment]
I just upgraded NC to 29.0.1 however the issue is still there.

**Comment by HenkVirtual** [comment]
I also upgraded to NC 29.0.1 but we are also facing the issue with custom menu. as mentioned by [bovender] fulltextsearchfiles is interfearing with the custom-menu app. 
here is my list of disabled apps while the custom menu is working correcly;
<details>
  <summary>output of occ app:list</summary>
```
Disabled:

-   - encryption: 2.17.0 (installed 2.12.0)
-   - files_external: 1.21.0
-   - files_fulltextsearch: 29.0.0 (installed 29.0.0)
-   - files_markdown: 2.4.1 (installed 2.4.1)
-   - metadata: 0.20.0 (installed 0.20.0)
-   - user_ldap: 1.20.0

```

**Comment by I-am-stefan** [comment]
Also here. After upgrade to 29.0.1 some of the menue Items shows to the actual used site.

so when i click  on dashboard and open it, i can move the mouse over the link items. Then some of them are shown the right link, but some shown the link to dashboard. So i think, that the the correct link cannot be determinated and the default (the actual URL) is shown. Never the less if you add the app into the url manually, the app can be used:https://nc.slsnet.de/index.php/apps/phonetrack

**Comment by HenkVirtual** [comment]
@I-am-stefan , do you have 'files_fulltextsearch' installed ? if yes, what happens when you disable this app ??

**Comment by theosche** [comment]
I had the same issue. Disabling fulltextsearch has fixed it for me. And I could directly reenable fulltextsearch without the issue reappearing.

**Comment by architectonio** [comment]
I disabled all Fultextsearch apps and the issue has disappeared. 
I re-enabled all Fultextsearch apps and the issue hasn't reappeared.
Then I enabled the "The Search Page" app and the issue was back.
I disabled again all Search apps, then re-enabled all Fulltextsearch apps again but not the "The Search Page" and everything seems to be fine.
I suppose that the "The Search Page" app is what causes the inconsistency with the icons on the top bar.

**Comment by theosche** [comment]
> I disabled all Fultextsearch apps and the issue has disappeared. I re-enabled all Fultextsearch apps and the issue hasn't reappeared. Then I enabled the "The Search Page" app and the issue was back. I disabled again all Search apps, then re-enabled all Fulltextsearch apps again but not the "The Search Page" and everything seems to be fine. I suppose that the "The Search Page" app is what causes the inconsistency with the icons on the top bar.

I don't think so, I don't have that app installed, I think there is just some delay before the issues reappears after re-enabling Fulltextsearch

**Comment by architectonio** [comment]
> I don't think so, I don't have that app installed, I think there is just some delay before the issue reappears after re-enabling Fulltextsearch

Could be.... 
Let's see what happens after a while when the applications are activated. Currently the problem is not back yet.

**Comment by architectonio** [comment]
@theosche : You was right with your thoughts. Today the issue reappeared.

**Comment by cmigliorini** [comment]
> Update: ok, when I am disable the app: apps/disabled/fulltextsearch the behavior changes. Every link is working again.

Ha! That worked for me too, solving https://github.com/nextcloud/server/issues/43910 !!

**Comment by cmigliorini** [comment]
Even better: disabling "fulltextsearch" _then reenabling it_ solves the issue. _Have you tried turning it off then on again_ ? ^^

**Comment by fbuescher** [comment]
for me the following helped:

- login in web as admin
- go to "Administration Setting"
- go to "Full text search"
- disable "Navigation Icon"
- login in web as user
- hit refresh

**Comment by cmigliorini** [comment]
> Even better: disabling "fulltextsearch" _then reenabling it_ solves the issue. _Have you tried turning it off then on again_ ? ^^

In fact it was only temporary. Had to disable it after a few minutes

**Comment by cmigliorini** [comment]
> for me the following helped:
> 
>     * login in web as admin
> 
>     * go to "Administration Setting"
> 
>     * go to "Full text search"
> 
>     * disable "Navigation Icon"
> 
>     * login in web as user
> 
>     * hit refresh

Worked for me, too.

**Comment by joshtrichards** [comment]
Duplicate of nextcloud/fulltextsearch#842

**Comment by cmigliorini** [comment]
See -> https://github.com/nextcloud/fulltextsearch/issues/842
