### ISSUE TITLE
Predict database migration impact of upgrades

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#45943]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Is your feature request related to a problem? Please describe.
As a Nextcloud admin I want to be able to plan *when* to do the next upgrade based on *how long* it will take. Quick updates that pass in 10 minutes can be done without any significant downtime. If the upgrade runs for 12h it needs a scheduled maintenance window, e.g. on a weekend, where Nextcloud is not available and users have to be warned in advance.

## Describe the solution you'd like
Collect information about the changes done in migration files for server and the apps. Distribute the information through the updater server and the app store. Use the information locally diff applied and new migrations, then show a digest of all the changes that will be done, or tell me that there will be no database changes when I upgrade.

## Work packages
- [x] Add PHP attributes to annotate migration classes, e.g. "adds a new column to oc_filecache", "creates a new table" or "drops a column from oc_accounts".
- [ ] Adapt the server release script so it dumps a list of migrations and their changes for server and shipped apps. It's important that the list contains *all* migrations, not just the ones that are "new" because we don't know which version is upgraded from.
- [ ] Adapt the updater server to ship a list of all migrations inside a specific release
- [ ] Adapt the app store to ship a list of all migrations inside a specific release
- [ ] Add an occ command to query for updates
  * Query the updater server for the next release and its migration data
  * Check for app upgrades necessary (e.g. doing a major update of the server)
  * Show a list of the changes that will happen on server and apps upgrade

## Follow-ups
* Adapt the admin updater UI
  * Fetch migrations of the upcoming release
  * Check for app upgrades necessary (e.g. doing a major update of the server)
  * Show a list of the changes that will happen on server and apps upgrade
* Adapt the app management (changelog tab?)
  * Diff currently applied migrations with the list of migrations provided through the app store
  * Show a list of the changes that will happen on app upgrade

Describe alternatives you've considered

Download server and apps, look at the migration files and parse the code to find out the information.

Additional context

N/a

**Comment by ChristophWurst** [comment]
@AndyScherzinger @juliushaertl as discussed

**Comment by AndyScherzinger** [comment]
@sorbaugh @artonge something for next week to discuss.

**Comment by ArtificialOwl** [comment]
After some discussions:

- details about migrations will be defined by \Attributes for each Migrations files,
- core migrations will be extracted during the release process and stored in the update server,
- apps migrations will be parsed and stored by the appstore,
- data from update server and appstore will be compared with already done migration and data will be generated.
- data will be available from an occ command and a resume should be made available on the webpage that displays available new versions.

**Comment by juliushaertl** [comment]
We should also think about a ci check so that we make those attributes mandatory on shipped apps, otherwise we risk missing those in the future

**Comment by ChristophWurst** [comment]
A visitor like ``\OcpSinceChecker`` could do this in Psalm

**Comment by susnux** [comment]
Are the open work packages still planned?
