### ISSUE TITLE
Calendar invites: Administrator shall choose if server's or user's email address is used

### ISSUE THREAD

**Issue by tuergeist** [nextcloud/server#5080]
## Feature Request

I refer to #2345 and #2778. 

If a Nextcloud instance serves for users from different domains (which is the case at least for me), it's annoying that calendar invites are sent with the server's email address instead of the user's once. For me it would be fine if the server's address is taken if there is no user email configured.

To avoid problems with mailservers that might not accept sending emails for more than one domain, this behavior this could be made optional.
(In my case all domains are hosted and handled by one email server and one nextcloud server - I would not like to set up a nextcloud instance per domain).

(If someone is so nice and point me to the place where I can change it in the code myself, would be fine too)

## Implementation

Delegate sending emails to apps. The main target is the Mail app but others may offer this integration too.

## Work packages

- [x] Add a mail sending provider mechanism
- [x] Implement the mail sending provider for Mail
- [x] Add an admin setting to choose which email system should be used (system or mail providers)
- [x] Adjust CalDAV backend to use the providers and system email as fallback
- [x] Developer documentation for the new API
- [x] Admin documentation for the setup and any configuration options

**Comment by georgehrke** [comment]
@tuergeist This is the place to go:
https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L109

Feel free to send a PR that implements this optionally. :)

**Comment by georgehrke** [comment]
(Message provides a `setFrom` method, see https://github.com/nextcloud/server/blob/master/lib/private/Mail/Message.php#L81)

**Comment by tuergeist** [comment]
Hi @georgehrke, IMHO the problem is the sender's address which I cannot change easily in neither code locations you pointed to. [Or I'm just too stupid]

**Comment by tuergeist** [comment]
Aaahh. Got it.

**Comment by ntnsndr** [comment]
I'd add that this is an important issue for us at MayFirst.org, who use the same NextCloud across a great many domains and organizational identities. We really need these invitation emails to be coming from the users who send them. Thanks to all who have the capacity and willingness to work on this.

**Comment by skjnldsv** [comment]
@georgehrke :trumpet: could you update this? :)

**Comment by georgehrke** [comment]
cc @jancborchardt This is what we talked about on Talk.

**Comment by georgehrke** [comment]
to summarise the problem:
- depending on the environment, users will have email-addresses managed by a different organisation than the Nextcloud-instance. If your Nextcloud is configured with the email address noreply@abc.tld, but your users use different providers like gmail, outlook, whatever, your email server (abc.tld) can't just start sending out emails for gmail, outlook, etc. Most of the times, these emails will be marked as spam and your server runs the risk of being put onto blacklists for spamming.

...  and our options:
- add an option for admins that allows them to send all emails (or at least emails from the same domain) via the abc.tld email server but with the real user email address. (user1@abc.tld). This should come with a big fat warning that if you enable it despite your users having email addresses from plenty different providers, you might run at the risk of being put onto spam blacklists
- integrate even better with the mail app. Allow the mail app to hook into the IMipPlugin and send out emails if the currently logged in user has an account registered for the email of the Organizer given in the calendar data. If there is no email registered, fallback to the current behaviour. cc @ChristophWurst

**Comment by ChristophWurst** [comment]
>     * integrate even better with the mail app. Allow the mail app to hook into the IMipPlugin and send out emails if the currently logged in user has an account registered for the email of the Organizer given in the calendar data. If there is no email registered, fallback to the current behaviour. cc @ChristophWurst

Sounds like a good idea in general.

**Comment by jancborchardt** [comment]
Sounds good and seems we should do both options?

Everyone who commented in the thread: Would this solve your issue?

**Comment by biva** [comment]
To be sure to understand the proposal of @georgehrke above:
1. User1, with email address user1@xyz.com will be able to send an invite with his own email address as organizer (and not noreply@abc.tld anymore). This has the risk to be considered as spam. This risk is lower if the email address of User1 is user1@abc.tld, but the risk still exists.
2. If User1 configures the mail app with his setup (his credentials + imap.xyz.com for example), the calendar app will be able to send an invite directly from the mail app.

It sounds good :)

Now, what happens if I use Thunderbird for my emails? Will it also work?

**Comment by georgehrke** [comment]
I'm super sorry, but all the development power of @ChristophWurst and me are currently bound on other tickets, so this will have to wait for Nextcloud 19.

**Comment by gitterdoneplease** [comment]
I'm no dev, but you can get this done by editing *nextcloudroot*/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php

Change line 252 from:
`->setFrom([$fromEMail => $fromName])`
to:
`->setFrom([$sender => $senderName])`

And your invites will come from the email address of the user instead of the server.

**Comment by ChristophWurst** [comment]
@gitterdoneplease this is a bit weird. I'm sure some mail servers will either not allow you to send a message with a mismatching `from` header or the recipient's mail server will mark it as spam as it looks like someone tries to spoof a sender.

**Comment by robertoschwald** [comment]
If all users use the same email domain, why should it be blocked?

**Comment by georgehrke** [comment]
> If all users use the same email domain,

This is something we can't assume. See my comment above:
https://github.com/nextcloud/server/issues/5080#issuecomment-501158303

**Comment by gitterdoneplease** [comment]
Dunno gents. I run the mail server too so it’s not an issue for me. A big warning in the GUI should be enough, but this was necessary in my case to transition completely to NC. Spoofing a from header if you AUTH on a SMTP server is painless, but as pointed out may trigger spam/junk detectors.

**Comment by Findebug** [comment]
So not going to make Nextcloud 19?

**Comment by loibpet** [comment]
I am awarea about quite a few organisations with different email domains. This easily happens with mergers, different legal entities for parts of a company (e.g. regulated business vs. un-regulated business, ...). There are tons of situations where this can happen.

Just don't assume that this is always fixed. Adding flexibility does not hurt at all and eases the work of the admins.

**Comment by Ferdi265** [comment]
I also want to add that even if the mail server / domain is the same, the mail server will not necessarily allow you to send as some.user@my.tld with the credentials for the nextcloud notification mail (often something like `nextcloud@my.tld`).

Also, since normal non-admin users can usually add and change mail settings via the nextcloud mail app, whether overriding the From header with the notification mail server and credentials will work can even change easily just through a settings change by an unprivileged user!

So I would suggest:

- have a global check box in the admin panel:
  - [X] Allow sending Calendar Invitations from user mail addresses configured in the Mail app
- have a check box in the Mail app account settings, like this: (maybe disable / grey out this option if the global setting is disabled)
  - [X] Allow NextCloud to send Calendar Invititations from this address

and send out calendar invitations from the user mail address (using the user mail credentials!) only if both settings are enabled.

**Comment by JMoVS** [comment]
@ChristophWurst Has there been any progress on this? In my case, it seems that the emails sent by the server itself have a higher chance of ending in spam than the users' email addresses sending.

**Comment by gitterdoneplease** [comment]
> @ChristophWurst Has there been any progress on this? In my case, it seems that the emails sent by the server itself have a higher chance of ending in spam than the users' email addresses sending.

I've been modifying the code for all of the versions since my first post to make this work. Would be great to have individual email addresses send calendar invites the way other systems work.

**Comment by MaLiPi10** [comment]
I also have a requirement and would be happy to help with this. At least a mail server with two domains. More could be added. Postfix + Dovecot + MySQL + Spamasassin + ClamAV.

Also need synchronizations and sending invitations to calendars on smartphones.

**Comment by gitterdoneplease** [comment]
Hi all, with SPF and DKIM records set correctly this really all works painlessly now except for manually changing the code. Could we please get something in the UI? It would be really great. Thanks so much.

**Comment by keunes** [comment]
> with SPF and DKIM records set correctly this really all works painlessly now

Is there some guide that you followed?

**Comment by gitterdoneplease** [comment]
How to set DNS records correctly? There is a lot of help out there, but I’d look at MxToolBox.

**Comment by gitterdoneplease** [comment]
Every new version I come back here to find what needs to be changed again. It's still in nextcloudroot/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php, but now the line number is 244.

Change line 244 from:
`->setFrom([$fromEMail => $fromName])`
to:
`->setFrom([$sender => $senderName])`

**Comment by keunes** [comment]
Hi @komoricodrutz

> If your recipient has a nextcloud account on your own server and is registered with his private e-mail address, it seems that it doesnt' even send an e-mail. I performed these tests:

I think that'd deserve its own, dedicated issue. That'd probably more considered a bug than an enhancement/feature request.

**Comment by ChristophWurst** [comment]
See open work packages.

**Comment by susnux** [comment]
Question:
Is it planned to deprecate the old symphony mailer abstraction by adding a system provider?
Or should this just be an addition? Because now we have two ways to send  emails.

**Comment by SebastianKrupinski** [comment]
> Question: Is it planned to deprecate the old symphony mailer abstraction by adding a system provider? Or should this just be an addition? Because now we have two ways to send emails.

At the moment both code paths will exist. The mail provider at the moment will be used to solve the problem that because all messages up to this point have been sent from the system account, calendar invitation invite replies are never received by the user, and the system account can not be used to send messages on behalf of someone else especially if that user uses a different server.

But I have thought that we could use the mail provider to send most if not all user generated notification, lets say when a user shares a file with someone. And we could also implement the same mail provider for the system account that way when apps send a message both the user mail account and system account is available through the same interface/logic.

Hope that answers your question.

**Comment by susnux** [comment]
> And we could also implement the same mail provider for the system account that way when apps send a message both the user mail account and system account is available through the same interface/logic.

Yes that is what I meant, if it is indendet to provide a system provider with e.g. "id = system" or capability "systemMail" or what ever.

Basically if this is a second way to sent mail, or the old way should be deprecated in favor of one consistent way handling mail :)

**Comment by kesselb** [comment]
I second do idea to make the default mailer an "mail provider". 

We started with imip, but the same would be nice for sharebyemail, inviting guests users, other apps, etc.

**Comment by leknoppix** [comment]
@SebastianKrupinski Thank you very much for the feature you're proposing.
Could you explain how it will work in practice? Will the user have the option to send invitations either from the default email address or from their own email address?

**Comment by ChristophWurst** [comment]
@leknoppix see https://github.com/nextcloud/server/issues/5080#issuecomment-2353065337. It will be an admin setting.

**Comment by leknoppix** [comment]
> @leknoppix see [#5080 (comment)](https://github.com/nextcloud/server/issues/5080#issuecomment-2353065337). It will be an admin setting.

Thanks you!

**Comment by ChristophWurst** [comment]
dear @SebastianKrupinski! could you please have a look at the open todos? let's get this task done 😎

**Comment by SebastianKrupinski** [comment]
@ChristophWurst the last part of this is stuck in PR review no mans land. Hasn't been approved. We can discuss in the morning.

**Comment by ChristophWurst** [comment]
@SebastianKrupinski what's the current status here?

**Comment by SebastianKrupinski** [comment]
@ChristophWurst Morning, last PR, finally got approved yesterday and merged. Back porting to 30.

**Comment by ChristophWurst** [comment]
could you update the list of work packages above? are admin docs done?

**Comment by SebastianKrupinski** [comment]
> could you update the list of work packages above? are admin docs done?

Done... and Admin docs will be done today, now that the wording is finalized.

**Comment by SebastianKrupinski** [comment]
Documentation https://github.com/nextcloud/documentation/pull/12372

**Comment by SebastianKrupinski** [comment]
Admin Documentation

https://github.com/nextcloud/documentation/pull/12372

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html#mail-providers

**Comment by SebastianKrupinski** [comment]
All task completed

**Comment by TheDom42** [comment]
Thank you very much for implementing this great and helpful feature! I wanted to try it out on my server today but I couldn't manage to set it up (maybe because I was looking at the wrong setting or because the current stable Mail App is <4.1 as required by the docs):

Current config: NC server 30.0.2, Calendar 5.0.6, Mail 4.0.7.

My NC is in German, so I don't know if the "Kontenbereitstellung" in `/settings/admin/groupware` is the area where this should be configured. I find the documentation at https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html#mail-providers a bit unclear at this point (I was first looking for a new app in the NC Store and then I was looking for an easy toggle somewhere in the admin or personal settings - like discussed in https://github.com/nextcloud/server/issues/5080#issuecomment-725597208). 

If this "Kontenbereitstellung" is actually the right setting, I don't know how to set it up: All our users already have a working personal email account set up in the Mail App, so I currently would not have the need to configure an "overall" server for the whole instance. Also, I don't know how to work with the placeholders for my current configuration - our NC accounts have the format of `initialfirstname.lastname` while the emails have the format of `fullfirstname.lastname@example.org`. So the `%USERID%` cannot be used as a placeholder for matching. We don't use LDAP.

Maybe, I am just looking for that easy toggle in the settings: "Use personal email if available". Would it be possible to get a "how-to setup the mail provider _for dummies_"?

**Comment by kesselb** [comment]
The toggle you are looking for will be part of Nextcloud 30.0.3.

Basic Settings (/settings/admin)

![Image](https://github.com/user-attachments/assets/6a0394ca-d538-4b25-9a74-3cba66d0df9d)

**Comment by ccbeorn** [comment]
Is this feature working for someone? 

Sorry for asking so generically, but on our end, we have set the toggle "Send emails using" to "User's email account", but for calendar invitations, the notification to the invited person is still coming from "[calender account name as per profile setting] via [system cloud name] Nextcloud <webmaster@[clouddomain.tld]>"

The conditions that are described next to the toggle setting are met (as far as we understand them). The calendar is from a nextcloud user account for which an email-account is existing and linked. Using the "email" function in the cloud webinterface has that mail account fully working and integrated.

We are using NC 30.0.5 and NC Mail 4.1.2

**Comment by SebastianKrupinski** [comment]
@ccbeorn 

This feature was temporarily disabled on the mail app side due to some issues we discovered with the formatting of the messages that where sent using the mail app, they issues are almost fixed and this should be re-enalbed soon.

**Comment by Smig0l** [comment]
come across this thread:
i have Nextcloud 33.0.1 and added Talk and Calendar apps. 
when i share a file/folder via FIles app the email is sent as configured in the settings (noreply@example.com).
but when i create a calendar/talk invite it gets sent 'userwhoinvited@example.com on behalf of noreply@example.com'.
so in the mail provider settings above i selected "use system email accounts".

basically i expected to send emails using only the system accounts and not appending headers or using on behalf.
is it correct? do i need the nexcloud Email app??

**Comment by SebastianKrupinski** [comment]
@Smig0l 

The mail provider sends emails from the users account, which means the user needs the mail app and a configured mail account.

If you want to only use the system email then you do not need the mail app.

**Comment by Smig0l** [comment]
Yeah but even after selecting the 'mail providers ->send email -> use system account' emails from talk invites are sent using user@email.com behalf of system@email.com, so this toggle is not working as expected?

**Comment by SebastianKrupinski** [comment]
> Yeah but even after selecting the 'mail providers ->send email -> use system account' emails from talk invites are sent using [user@email.com](mailto:user@email.com) behalf of [system@email.com](mailto:system@email.com), so this toggle is not working as expected?

Yes the toggle is working as expected. we use the on behalf so that responses come back to the user event if they are sent from the system account.
