### ISSUE TITLE
Implement missing checks for the workflow engine

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#617]
### [Checks](https://doc.owncloud.org/server/9.0/admin_manual/enterprise_firewall/file_firewall.html)
- [x] User Group Membership #565 
- [x] User Agent #611
- [x] User Device - Quick control for User Agent #611
- [x] Request Time #611 
- [x] Request URL #611
- [x] Request Type - Quick control for Request URL #611
- [x] Request IP Range (IPv4) and IP Range (IPv6) #611
- [x] File Size Upload #611
- [x] File Mimetype Upload #611
- [x] System File Tag #611
- [x] ~~Regular Expression~~ - Implemented as "operator" instead of being an extra rule type.
