### ISSUE TITLE
E2E meta issue

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#6698]
# Components (check them if they are done up to milestone 2)

- [ ] Android: 	https://github.com/nextcloud/android/issues/1599
- [ ] Desktop:	https://github.com/nextcloud/client/pull/87 (PR)
- [ ] iOS:		
- [x] Server: 	https://github.com/nextcloud/end_to_end_encryption/issues/2

## Milestone 1 (beta) Deadline: End of October
- working encrypt/decrypt of files across all platforms 

## Milestone 2 (release with NC13) Deadline: End of November
- support all file operations (move, copy, delete, rename)
- new folders within encrypted folders
- sharing

## Milestone 3 (after NC13) Deadline: End of December
- handle admin key

@schiessle @marinofaggiana @tcanabrava @LukasReschke

**Comment by schiessle** [comment]
Thanks @tobiasKaminsky 

@marinofaggiana @tcanabrava would be great if you could create a overview ticket for your task on the road to a first version and link to it here. Thanks!

**Comment by MorrisJobke** [comment]
@schiessle @marinofaggiana @tobiasKaminsky @tcanabrava What is the status here?

**Comment by tobiasKaminsky** [comment]
Well, even milestone 1 is not really completed as we did not tested it yet.
On android I did not started to work any further.

**Comment by marinofaggiana** [comment]
A few tests and many doubts ... for me the lock system remains too much dangerous... and the metadata file becomes enormous ... :(

**Comment by tobiasKaminsky** [comment]
> enormous?

Well, 1 files entry per file. This cannot be any smaller. And if you do not have thousands of files in one encrypted folder, it should not be that big. Files in a subfolder have their own metadata file.
So where is it getting this big?

**Comment by marinofaggiana** [comment]
for me (see crypto cloud) : 

1 file metadata for encrypted file : 

- insert thumbnail (encrypted) in metadata 
- small size 
- if corrupt the metadata (never happened) is corrupt only 1 file 
- do not required lock for directory 

for me this is the best solution ... but for me :-)

**Comment by e-alfred** [comment]
Seems like this should be added to the initial post:

https://github.com/nextcloud/ios/issues/449

**Comment by MorrisJobke** [comment]
As the basics are done for 13: I will close this ticket here and we continue in the repos where the problem happens then with more specific tickets.
